<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\AlertContact;
use GoSuccess\UptimeRobot\Model\AlertContactCreate;
use GoSuccess\UptimeRobot\Model\AlertContactUpdate;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Personal alert contacts: the e-mail addresses, phone numbers and mobile app devices of the account that monitors alert. Team channels such as Slack are integrations.
 */
final class AlertContactResource extends AbstractResource
{
    /**
     * List personal alert contacts
     *
     * List the personal alert contacts (email, Pro SMS, voice, iOS/Android push) owned by the authenticated user. Integrations are managed separately through /v3/integrations.
     *
     * Ascending by ID; the cursor is the ID of the last contact of the previous page, and the contacts with greater IDs follow. The page size is not documented: all 6 contacts of the test account came on one page without nextLink. The lists of contacts differ: this one left out the mobile app contacts awaiting migration (status ToMigrate), which UserResource::alertContacts() lists, while IntegrationResource::list() with includeOrgMembers listed every contact (all verified live).
     *
     * `GET /alert-contacts`
     *
     * @param int|null $cursor The cursor of the page to return, as the previous page reported it; null for the first page.
     *
     * @return Page<AlertContact>
     */
    public function list(?int $cursor = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'alert-contacts', [
            'cursor' => $cursor,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(AlertContact::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Ascending by ID; the cursor is the ID of the last contact of the previous page, and the contacts with greater IDs follow. The page size is not documented: all 6 contacts of the test account came on one page without nextLink. The lists of contacts differ: this one left out the mobile app contacts awaiting migration (status ToMigrate), which UserResource::alertContacts() lists, while IntegrationResource::list() with includeOrgMembers listed every contact (all verified live).
     *
     * `GET /alert-contacts`
     *
     * @return Paginator<AlertContact>
     */
    public function all(): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
        ));
    }

    /**
     * Get a personal alert contact by ID
     *
     * Get a personal alert contact details by ID
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `GET /alert-contacts/{id}`
     *
     * @param int $id ID of the personal alert contact
     */
    public function get(int $id): AlertContact
    {
        $data = $this->connection->json(Method::Get, "alert-contacts/{$id}");

        return self::toModel(AlertContact::class, $data);
    }

    /**
     * Create a personal alert contact
     *
     * Create a personal alert contact. Email and push (iOS/Android) are supported; Pro SMS and voice require phone verification and are not creatable here.
     *
     * Email contacts need value. Mobile app contacts need platform, oneSignalSubscriptionId, oneSignalUserId and deviceFingerprint, which the official Terraform provider checks before it sends them along with deviceName and pushToken. sslExpirationReminder and isActive can only be set with update(). Not verified live beyond the validator: the owner of the test account allows no contacts to be created.
     *
     * `POST /alert-contacts`
     *
     * @param AlertContactCreate $contact
     */
    public function create(AlertContactCreate $contact): AlertContact
    {
        $data = $this->connection->json(Method::Post, 'alert-contacts', body: $contact->toArray());

        return self::toModel(AlertContact::class, $data);
    }

    /**
     * Update a personal alert contact
     *
     * Only the properties that are set are sent. The validator runs before the contact is looked up, so an invalid change to an unknown ID raises a BadRequestException, a valid one a NotFoundException (verified live). Not verified live beyond that: the owner of the test account allows no contacts to be changed.
     *
     * `PATCH /alert-contacts/{id}`
     *
     * @param int                $id      ID of the personal alert contact
     * @param AlertContactUpdate $changes
     */
    public function update(int $id, AlertContactUpdate $changes): AlertContact
    {
        $data = $this->connection->json(Method::Patch, "alert-contacts/{$id}", body: $changes->toArray());

        return self::toModel(AlertContact::class, $data);
    }

    /**
     * Delete a personal alert contact
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `DELETE /alert-contacts/{id}`
     *
     * @param int $id ID of the personal alert contact
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "alert-contacts/{$id}");
    }
}
