<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Enum\AnnouncementStatusFilter;
use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Announcement;
use GoSuccess\UptimeRobot\Model\AnnouncementCreate;
use GoSuccess\UptimeRobot\Model\AnnouncementUpdate;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Announcements on status pages: information, maintenance and issue notices, which subscribers receive by e-mail. Requires the plan feature psp-subscribers.
 */
final class AnnouncementResource extends AbstractResource
{
    /**
     * List announcements
     *
     * List all announcements for a Public Status Page. Results are sorted by creation date (newest first) and can be filtered by status.
     *
     * Newest first, according to the specification. The status filter takes the upper-case values of the specification (AnnouncementStatusFilter), unlike the title-case AnnouncementStatus of the requests. Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `GET /psps/{pspId}/announcements`
     *
     * @param int                           $statusPageId ID of the Public Status Page
     * @param int|null                      $cursor       The cursor of the page to return, as the previous page reported it; null for the first page.
     * @param AnnouncementStatusFilter|null $status       Filter announcements by status
     *
     * @return Page<Announcement>
     */
    public function list(int $statusPageId, ?int $cursor = null, ?AnnouncementStatusFilter $status = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, "psps/{$statusPageId}/announcements", [
            'cursor' => $cursor,
            'status' => $status,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(Announcement::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Newest first, according to the specification. The status filter takes the upper-case values of the specification (AnnouncementStatusFilter), unlike the title-case AnnouncementStatus of the requests. Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `GET /psps/{pspId}/announcements`
     *
     * @param int                           $statusPageId ID of the Public Status Page
     * @param AnnouncementStatusFilter|null $status       Filter announcements by status
     *
     * @return Paginator<Announcement>
     */
    public function all(int $statusPageId, ?AnnouncementStatusFilter $status = null): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            statusPageId: $statusPageId,
            cursor: \is_int($cursor) ? $cursor : null,
            status: $status,
        ));
    }

    /**
     * Get an announcement by ID
     *
     * Retrieve a single announcement for a Public Status Page
     *
     * Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `GET /psps/{pspId}/announcements/{id}`
     *
     * @param int $statusPageId ID of the Public Status Page
     * @param int $id           ID of the announcement
     */
    public function get(int $statusPageId, int $id): Announcement
    {
        $data = $this->connection->json(Method::Get, "psps/{$statusPageId}/announcements/{$id}");

        return self::toModel(Announcement::class, $data);
    }

    /**
     * Create an announcement
     *
     * Create a new announcement for a Public Status Page
     *
     * The specification marks no property as required, not even title and content. Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `POST /psps/{pspId}/announcements`
     *
     * @param int                $statusPageId ID of the Public Status Page
     * @param AnnouncementCreate $announcement
     */
    public function create(int $statusPageId, AnnouncementCreate $announcement): Announcement
    {
        $data = $this->connection->json(Method::Post, "psps/{$statusPageId}/announcements", body: $announcement->toArray());

        return self::toModel(Announcement::class, $data);
    }

    /**
     * Update an announcement
     *
     * Update an existing announcement for a Public Status Page
     *
     * Only the properties that are set are sent. Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `PATCH /psps/{pspId}/announcements/{id}`
     *
     * @param int                $statusPageId ID of the Public Status Page
     * @param int                $id           ID of the announcement to update
     * @param AnnouncementUpdate $changes
     */
    public function update(int $statusPageId, int $id, AnnouncementUpdate $changes): Announcement
    {
        $data = $this->connection->json(Method::Patch, "psps/{$statusPageId}/announcements/{$id}", body: $changes->toArray());

        return self::toModel(Announcement::class, $data);
    }

    /**
     * Pin an announcement
     *
     * Pin an announcement to the Public Status Page. This operation is idempotent.
     *
     * Sends an empty JSON object, which the API insists on although the specification declares no body (verified live). Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `POST /psps/{pspId}/announcements/{id}/pin`
     *
     * @param int $statusPageId ID of the Public Status Page
     * @param int $id           ID of the announcement to pin
     */
    public function pin(int $statusPageId, int $id): void
    {
        $this->connection->json(Method::Post, "psps/{$statusPageId}/announcements/{$id}/pin", body: []);
    }

    /**
     * Unpin an announcement
     *
     * Unpin an announcement from the Public Status Page. This operation is idempotent.
     *
     * Sends an empty JSON object, which the API insists on although the specification declares no body (verified live). Requires the plan feature psp-subscribers; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the status page or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `POST /psps/{pspId}/announcements/{id}/unpin`
     *
     * @param int $statusPageId ID of the Public Status Page
     * @param int $id           ID of the announcement to unpin
     */
    public function unpin(int $statusPageId, int $id): void
    {
        $this->connection->json(Method::Post, "psps/{$statusPageId}/announcements/{$id}/unpin", body: []);
    }
}
