<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Resource\Handwritten\BulkMonitorOperations;

/** Pause, start or change the monitors of a monitor group and/or with a tag at once. */
final class BulkMonitorResource extends AbstractResource
{
    use BulkMonitorOperations;
}
