<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use DateTimeInterface;
use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\ActivityLogEntry;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\CommentActivity;
use GoSuccess\UptimeRobot\Model\Incident;
use GoSuccess\UptimeRobot\Model\IncidentSummary;
use GoSuccess\UptimeRobot\Model\NotificationActivity;
use GoSuccess\UptimeRobot\Model\SentAlert;
use GoSuccess\UptimeRobot\Model\StatusUpdateActivity;
use GoSuccess\UptimeRobot\Model\UnknownActivityLogEntry;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Incidents: the downtimes and slow responses of the monitors, with their root cause, activity log and the alerts sent. Incident IDs are strings of digits.
 */
final class IncidentResource extends AbstractResource
{
    /**
     * List incidents
     *
     * List all incidents in a user's account with optional filtering. Values can be paginated with the cursor parameter.
     *
     * Newest first. The cursor is the ID of the last incident of the previous page; the incidents that started before it follow. monitorName matches part of the name, ignoring case; startedAfter and startedBefore bound startedAt. The page size is not documented: all 14 incidents of the test account came on one page (all verified live).
     *
     * `GET /incidents`
     *
     * @param string|null            $cursor        The cursor of the page to return, as the previous page reported it; null for the first page.
     * @param int|null               $monitorId     Filter incidents by monitor ID
     * @param string|null            $monitorName   Filter incidents by monitor name (partial match)
     * @param DateTimeInterface|null $startedAfter  Only incidents that started at or after this time, compared to the millisecond (verified live); sent as ISO 8601 in UTC. To continue after an incident, pass its startedAt plus one millisecond.
     * @param DateTimeInterface|null $startedBefore Only incidents that started at or before this time, compared to the millisecond (verified live); sent as ISO 8601 in UTC.
     *
     * @return Page<IncidentSummary>
     */
    public function list(
        ?string $cursor = null,
        ?int $monitorId = null,
        ?string $monitorName = null,
        ?DateTimeInterface $startedAfter = null,
        ?DateTimeInterface $startedBefore = null,
    ): Page {
        $data = self::expectObject($this->connection->json(Method::Get, 'incidents', [
            'cursor' => $cursor,
            'monitor_id' => $monitorId,
            'monitor_name' => $monitorName,
            'started_after' => $startedAfter,
            'started_before' => $startedBefore,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(IncidentSummary::class, $data['data'] ?? null), integerCursor: false);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Newest first. The cursor is the ID of the last incident of the previous page; the incidents that started before it follow. monitorName matches part of the name, ignoring case; startedAfter and startedBefore bound startedAt. The page size is not documented: all 14 incidents of the test account came on one page (all verified live).
     *
     * `GET /incidents`
     *
     * @param int|null               $monitorId     Filter incidents by monitor ID
     * @param string|null            $monitorName   Filter incidents by monitor name (partial match)
     * @param DateTimeInterface|null $startedAfter  Only incidents that started at or after this time, compared to the millisecond (verified live); sent as ISO 8601 in UTC. To continue after an incident, pass its startedAt plus one millisecond.
     * @param DateTimeInterface|null $startedBefore Only incidents that started at or before this time, compared to the millisecond (verified live); sent as ISO 8601 in UTC.
     *
     * @return Paginator<IncidentSummary>
     */
    public function all(
        ?int $monitorId = null,
        ?string $monitorName = null,
        ?DateTimeInterface $startedAfter = null,
        ?DateTimeInterface $startedBefore = null,
    ): Paginator {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_string($cursor) ? $cursor : null,
            monitorId: $monitorId,
            monitorName: $monitorName,
            startedAfter: $startedAfter,
            startedBefore: $startedBefore,
        ));
    }

    /**
     * Get an incident by ID
     *
     * Get incident details including root cause information
     *
     * Unlike the items of list(), an incident has neither type nor monitor; cause 0 marks a slow response. rootCause, null according to the specification, was present on every incident read, with an empty url and null headers for a slow response; assertionDiagnostics is only expected for API monitors and was always null. An unknown ID raises a NotFoundException (all verified live).
     *
     * `GET /incidents/{id}`
     *
     * @param string $id The incident ID
     */
    public function get(string $id): Incident
    {
        $data = $this->connection->json(Method::Get, "incidents/{$this->segment($id)}");

        return self::toModel(Incident::class, $data);
    }

    /**
     * Get incident activity log
     *
     * Returns the activity log for an incident, including status updates, comments, and notifications. Sorted by date descending.
     *
     * Newest first: status updates of the checks (remoteNode is null on Up entries, responseTime only set on Slow ones), notifications and, with the plan feature incident-comments, comments. Only the first page is available: the API reports a nextLink, but ignores cursor and limit (verified live). No incident read had more than 6 entries, and nextLink was always null.
     *
     * `GET /incidents/{id}/activity-log`
     *
     * @param string $id ID of the incident
     *
     * @return list<ActivityLogEntry>
     */
    public function activityLog(string $id): array
    {
        $data = $this->connection->json(Method::Get, "incidents/{$this->segment($id)}/activity-log");

        return Cast::listOf(self::expectObject($data)['data'] ?? null, static fn(mixed $value): ?ActivityLogEntry => Cast::union($value, 'type', [StatusUpdateActivity::TYPE => StatusUpdateActivity::class, CommentActivity::TYPE => CommentActivity::class, NotificationActivity::TYPE => NotificationActivity::class], UnknownActivityLogEntry::class));
    }

    /**
     * Get incident sent alerts
     *
     * Returns all alerts that were sent for a specific incident, including recipient information and delivery status.
     *
     * Oldest first, all in one response; empty if no alert was sent (verified live).
     *
     * `GET /incidents/{id}/alerts`
     *
     * @param string $id ID of the incident
     *
     * @return list<SentAlert>
     */
    public function alerts(string $id): array
    {
        $data = $this->connection->json(Method::Get, "incidents/{$this->segment($id)}/alerts");

        return Cast::modelList(SentAlert::class, self::expectObject($data)['data'] ?? null);
    }
}
