<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\IncidentComment;
use GoSuccess\UptimeRobot\Model\IncidentCommentCreate;
use GoSuccess\UptimeRobot\Model\IncidentCommentUpdate;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Comments on incidents, optionally published on the status page. Requires the plan feature incident-comments.
 */
final class IncidentCommentResource extends AbstractResource
{
    /**
     * List incident comments
     *
     * Returns paginated comments for a specific incident, ordered by creation date ascending (oldest first).
     *
     * Oldest first, according to the specification. The cursor is the ID of the last comment of the previous page. all() requests pages of 100 comments, the most the specification allows. Requires the plan feature incident-comments; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the incident or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `GET /incidents/{id}/comments`
     *
     * @param string   $incidentId The incident ID
     * @param int|null $cursor     The cursor of the page to return, as the previous page reported it; null for the first page.
     * @param int|null $limit      Comments per page, from 1 to 100; the specification gives 50 as the default.
     *
     * @return Page<IncidentComment>
     */
    public function list(string $incidentId, ?int $cursor = null, ?int $limit = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, "incidents/{$this->segment($incidentId)}/comments", [
            'cursor' => $cursor,
            'limit' => $limit,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(IncidentComment::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Oldest first, according to the specification. The cursor is the ID of the last comment of the previous page. all() requests pages of 100 comments, the most the specification allows. Requires the plan feature incident-comments; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the incident or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `GET /incidents/{id}/comments`
     *
     * @param string $incidentId The incident ID
     * @param int    $limit      Comments per page, from 1 to 100; the specification gives 50 as the default.
     *
     * @return Paginator<IncidentComment>
     */
    public function all(string $incidentId, int $limit = 100): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            incidentId: $incidentId,
            cursor: \is_int($cursor) ? $cursor : null,
            limit: $limit,
        ));
    }

    /**
     * Create incident comment
     *
     * Create a new comment on an incident
     *
     * The specification documents no response body. This returns the comment if the API sends one, as UptimeRobot's incident-response guide for its MCP server takes the commentId "from the create response", and null for an empty response. Requires the plan feature incident-comments; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the incident or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `POST /incidents/{id}/comments`
     *
     * @param string                $incidentId ID of the incident
     * @param IncidentCommentCreate $comment
     */
    public function create(string $incidentId, IncidentCommentCreate $comment): ?IncidentComment
    {
        $data = $this->connection->json(Method::Post, "incidents/{$this->segment($incidentId)}/comments", body: $comment->toArray());

        return $data === null ? null : self::toModel(IncidentComment::class, $data);
    }

    /**
     * Update an incident comment
     *
     * Updates an existing comment on an incident
     *
     * content is required, so the text is always replaced. Requires the plan feature incident-comments; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the incident or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `PATCH /incidents/{id}/comments/{commentId}`
     *
     * @param string                $incidentId The incident ID
     * @param int                   $id         The comment ID
     * @param IncidentCommentUpdate $changes
     */
    public function update(string $incidentId, int $id, IncidentCommentUpdate $changes): IncidentComment
    {
        $data = $this->connection->json(Method::Patch, "incidents/{$this->segment($incidentId)}/comments/{$id}", body: $changes->toArray());

        return self::toModel(IncidentComment::class, $data);
    }

    /**
     * Delete incident comment
     *
     * Delete a comment from an incident
     *
     * Requires the plan feature incident-comments; without it, the API raises a ForbiddenException with the code 000-003 before it looks at the incident or the request (verified live). Not verified live beyond that: the test account lacks the feature.
     *
     * `DELETE /incidents/{id}/comments/{commentId}`
     *
     * @param string $incidentId ID of the incident
     * @param int    $id         ID of the comment
     */
    public function delete(string $incidentId, int $id): void
    {
        $this->connection->json(Method::Delete, "incidents/{$this->segment($incidentId)}/comments/{$id}");
    }
}
