<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\Integration;
use GoSuccess\UptimeRobot\Model\IntegrationCreate;
use GoSuccess\UptimeRobot\Model\IntegrationUpdate;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Integrations: the team channels that monitors alert, such as Slack, Microsoft Teams, PagerDuty or webhooks. Monitors assign them like personal alert contacts, by ID.
 */
final class IntegrationResource extends AbstractResource
{
    /**
     * List Integrations
     *
     * Ascending by ID; the cursor is the ID of the last item of the previous page. Without includeOrgMembers only integrations are listed (verified live).
     *
     * `GET /integrations`
     *
     * @param int|null  $cursor            The cursor of the page to return, as the previous page reported it; null for the first page.
     * @param bool|null $includeOrgMembers With true, the personal alert contacts are listed along with the integrations, in the same shape. Verified live on an account in no organization, which got all its own contacts, mobile app contacts included; the specification promises the contacts of the members of an organization the caller owns.
     *
     * @return Page<Integration>
     */
    public function list(?int $cursor = null, ?bool $includeOrgMembers = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'integrations', [
            'cursor' => $cursor,
            'includeOrgMembers' => $includeOrgMembers,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(Integration::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Ascending by ID; the cursor is the ID of the last item of the previous page. Without includeOrgMembers only integrations are listed (verified live).
     *
     * `GET /integrations`
     *
     * @param bool|null $includeOrgMembers With true, the personal alert contacts are listed along with the integrations, in the same shape. Verified live on an account in no organization, which got all its own contacts, mobile app contacts included; the specification promises the contacts of the members of an organization the caller owns.
     *
     * @return Paginator<Integration>
     */
    public function all(?bool $includeOrgMembers = null): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
            includeOrgMembers: $includeOrgMembers,
        ));
    }

    /**
     * Get an integration by ID
     *
     * Get an integration details by ID
     *
     * An unknown ID raises a NotFoundException with the code 000-004, the ID of a personal contact one with the code 021-005 (verified live).
     *
     * `GET /integrations/{id}`
     *
     * @param int $id ID of the integration
     */
    public function get(int $id): Integration
    {
        $data = $this->connection->json(Method::Get, "integrations/{$id}");

        return self::toModel(Integration::class, $data);
    }

    /**
     * Create an Integration
     *
     * Pass the model of the integration type, e.g. SlackIntegrationCreate, which sends its type. The API matches the type ignoring case; a type the plan lacks raises a ForbiddenException with the code 021-003 (verified live for update() with PagerDuty on the Solo plan). The specification gives Telegram no chat setting. Not verified live beyond the type: the owner of the test account allows no integrations to be created.
     *
     * `POST /integrations`
     *
     * @param IntegrationCreate $integration
     */
    public function create(IntegrationCreate $integration): Integration
    {
        $data = $this->connection->json(Method::Post, 'integrations', body: $integration->toArray());

        return self::toModel(Integration::class, $data);
    }

    /**
     * Update an Integration
     *
     * Pass the model of the integration's type, which sends it: the API requires the type, although the specification makes it optional (verified live). Only the settings that are set are sent; whether the API keeps the others is not documented, and the official Terraform provider always sends all of them. The API checks the type first, then whether the plan includes it (ForbiddenException with the code 021-003), then looks up the integration; invalid settings still reached the lookup (all verified live). Not verified live beyond that: the test account has no integrations.
     *
     * `PATCH /integrations/{id}`
     *
     * @param int               $id      ID of the integration
     * @param IntegrationUpdate $changes
     */
    public function update(int $id, IntegrationUpdate $changes): Integration
    {
        $data = $this->connection->json(Method::Patch, "integrations/{$id}", body: $changes->toArray());

        return self::toModel(Integration::class, $data);
    }

    /**
     * Delete an Integration
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `DELETE /integrations/{id}`
     *
     * @param int $id ID of the integration
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "integrations/{$id}");
    }
}
