<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\MaintenanceWindow;
use GoSuccess\UptimeRobot\Model\MaintenanceWindowCreate;
use GoSuccess\UptimeRobot\Model\MaintenanceWindowUpdate;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Maintenance windows: one-time or recurring periods that suppress the alerts of the monitors assigned to them.
 */
final class MaintenanceWindowResource extends AbstractResource
{
    /**
     * List maintenance windows
     *
     * The cursor is the ID of the last window of the previous page, as the official Terraform provider sends it. Only a single page was observable: an account without windows gets {"data": []} without nextLink (verified live).
     *
     * `GET /maintenance-windows`
     *
     * @param int|null $cursor The cursor of the page to return, as the previous page reported it; null for the first page.
     *
     * @return Page<MaintenanceWindow>
     */
    public function list(?int $cursor = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'maintenance-windows', [
            'cursor' => $cursor,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(MaintenanceWindow::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * The cursor is the ID of the last window of the previous page, as the official Terraform provider sends it. Only a single page was observable: an account without windows gets {"data": []} without nextLink (verified live).
     *
     * `GET /maintenance-windows`
     *
     * @return Paginator<MaintenanceWindow>
     */
    public function all(): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
        ));
    }

    /**
     * Get a maintenance window by ID
     *
     * An unknown ID raises a NotFoundException, the ID of another account's window a ForbiddenException with the code 000-006 (both verified live).
     *
     * `GET /maintenance-windows/{id}`
     *
     * @param int $id ID of the maintenance window
     */
    public function get(int $id): MaintenanceWindow
    {
        $data = $this->connection->json(Method::Get, "maintenance-windows/{$id}");

        return self::toModel(MaintenanceWindow::class, $data);
    }

    /**
     * Create a maintenance window
     *
     * Weekly and monthly windows need days. The specification requires date for every interval, although the API's validator does not ask for it (verified live). There is no status here; update() pauses a window.
     *
     * `POST /maintenance-windows`
     *
     * @param MaintenanceWindowCreate $window
     */
    public function create(MaintenanceWindowCreate $window): MaintenanceWindow
    {
        $data = $this->connection->json(Method::Post, 'maintenance-windows', body: $window->toArray());

        return self::toModel(MaintenanceWindow::class, $data);
    }

    /**
     * Update a maintenance window
     *
     * Only the properties that are set are sent. The validator runs before the window is looked up (verified live), so an invalid change to an unknown ID raises a BadRequestException, a valid one a NotFoundException.
     *
     * `PATCH /maintenance-windows/{id}`
     *
     * @param int                     $id      ID of the maintenance window
     * @param MaintenanceWindowUpdate $changes
     */
    public function update(int $id, MaintenanceWindowUpdate $changes): MaintenanceWindow
    {
        $data = $this->connection->json(Method::Patch, "maintenance-windows/{$id}", body: $changes->toArray());

        return self::toModel(MaintenanceWindow::class, $data);
    }

    /**
     * Delete a maintenance window
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `DELETE /maintenance-windows/{id}`
     *
     * @param int $id
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "maintenance-windows/{$id}");
    }
}
