<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\MonitorGroup;
use GoSuccess\UptimeRobot\Model\MonitorGroupCreate;
use GoSuccess\UptimeRobot\Model\MonitorGroupUpdate;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/**
 * Monitor groups: named sets of monitors. A monitor is in one group at most; the monitors in none report the groupId 0.
 */
final class MonitorGroupResource extends AbstractResource
{
    /**
     * List monitor groups
     *
     * List all monitor groups in a user's account. Values can be paginated with the cursor parameter.
     *
     * The groups carry neither their monitors nor their number; MonitorResource::list() with groupId lists the monitors of a group (verified live).
     *
     * `GET /monitor-groups`
     *
     * @param int|null $cursor The cursor of the page to return, as the previous page reported it; null for the first page.
     *
     * @return Page<MonitorGroup>
     */
    public function list(?int $cursor = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'monitor-groups', [
            'cursor' => $cursor,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(MonitorGroup::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * The groups carry neither their monitors nor their number; MonitorResource::list() with groupId lists the monitors of a group (verified live).
     *
     * `GET /monitor-groups`
     *
     * @return Paginator<MonitorGroup>
     */
    public function all(): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
        ));
    }

    /**
     * Get a monitor group by ID
     *
     * Get monitor group details by ID
     *
     * An unknown ID raises a NotFoundException, and so does 0, the groupId of the monitors in no group (verified live).
     *
     * `GET /monitor-groups/{id}`
     *
     * @param int $id The monitor group ID
     */
    public function get(int $id): MonitorGroup
    {
        $data = $this->connection->json(Method::Get, "monitor-groups/{$id}");

        return self::toModel(MonitorGroup::class, $data);
    }

    /**
     * Create a monitor group
     *
     * Create a new monitor group with optional initial monitors. Monitors can be assigned by providing their IDs or by specifying existing group IDs whose monitors should be moved.
     *
     * The monitors of monitorIds and of the groups in groupIds are moved into the new group.
     *
     * `POST /monitor-groups`
     *
     * @param MonitorGroupCreate $group
     */
    public function create(MonitorGroupCreate $group): MonitorGroup
    {
        $data = $this->connection->json(Method::Post, 'monitor-groups', body: $group->toArray());

        return self::toModel(MonitorGroup::class, $data);
    }

    /**
     * Update a monitor group
     *
     * Update (rename) an existing monitor group
     *
     * Only the name can be changed; MonitorResource::update() moves a monitor to another group with groupId.
     *
     * `PATCH /monitor-groups/{id}`
     *
     * @param int                $id      The monitor group ID
     * @param MonitorGroupUpdate $changes
     */
    public function update(int $id, MonitorGroupUpdate $changes): MonitorGroup
    {
        $data = $this->connection->json(Method::Patch, "monitor-groups/{$id}", body: $changes->toArray());

        return self::toModel(MonitorGroup::class, $data);
    }

    /**
     * Delete a monitor group
     *
     * Delete a monitor group. Monitors in the deleted group will be moved to the specified group or to the default group (ID: 0).
     *
     * The monitors of the group are moved to monitorsNewGroupId, or to no group (groupId 0) without it; monitorsNewGroupId 0 is rejected with a BadRequestException. An unknown ID raises a NotFoundException (both verified live).
     *
     * `DELETE /monitor-groups/{id}`
     *
     * @param int      $id                 The monitor group ID to delete
     * @param int|null $monitorsNewGroupId Optional group ID to move monitors to. If not provided, monitors will be moved to default group (ID: 0).
     */
    public function delete(int $id, ?int $monitorsNewGroupId = null): void
    {
        $this->connection->json(Method::Delete, "monitor-groups/{$id}", [
            'monitorsNewGroupId' => $monitorsNewGroupId,
        ]);
    }
}
