<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use DateTimeInterface;
use GoSuccess\UptimeRobot\Enum\MonitorStatus;
use GoSuccess\UptimeRobot\Enum\ResponseTimeRegion;
use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\Monitor;
use GoSuccess\UptimeRobot\Model\MonitorCreate;
use GoSuccess\UptimeRobot\Model\MonitorUpdate;
use GoSuccess\UptimeRobot\Model\MonitorUptimeStats;
use GoSuccess\UptimeRobot\Model\RegionalResponseTimeStats;
use GoSuccess\UptimeRobot\Model\ResponseTimeStats;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;
use GoSuccess\UptimeRobot\Resource\Handwritten\MonitorOperations;

/**
 * Monitors: create, read, change, pause, start and delete them, and read their uptime and response time statistics.
 */
final class MonitorResource extends AbstractResource
{
    use MonitorOperations;

    /**
     * List monitors
     *
     * List all monitors in a user's account. Values can be paginated with the cursor parameter. Optionally filter by tags, URL, name, status, groupId, or limit. All filters use AND logic when combined.
     *
     * Filters combine with AND; status and tags match any of their values, while every customField entry ("key:value") must match, and the groupId 0 selects the monitors in no group (verified live). all() requests pages of 200 monitors, the most the API allows.
     *
     * `GET /monitors`
     *
     * @param int|null                 $cursor      The cursor of the page to return, as the previous page reported it; null for the first page.
     * @param int|null                 $limit       Maximum number of monitors to return per page. Default: 50, Min: 1, Max: 200.
     * @param list<string>|null        $customField Filter monitors by custom field key:value pairs. Format: customField=key:value. Multiple filters use AND logic. Split on first colon only.
     * @param int|null                 $groupId     Filter monitors by monitor group ID.
     * @param list<MonitorStatus>|null $status      Comma-separated list of status values to filter monitors. Uses OR logic (matches any specified status). Case-insensitive. Allowed values: PAUSED, STARTED, UP, LOOKS_DOWN, DOWN.
     * @param string|null              $name        Filter monitors by name. Case-insensitive partial match on the monitor friendly name.
     * @param string|null              $url         Filter monitors by URL. Case-insensitive partial match on the monitor URL.
     * @param list<string>|null        $tags        Comma-separated list of tag names to filter monitors. Uses OR logic (matches any specified tag). Case-sensitive.
     *
     * @return Page<Monitor>
     */
    public function list(
        ?int $cursor = null,
        ?int $limit = null,
        ?array $customField = null,
        ?int $groupId = null,
        ?array $status = null,
        ?string $name = null,
        ?string $url = null,
        ?array $tags = null,
    ): Page {
        $data = self::expectObject($this->connection->json(Method::Get, 'monitors', [
            'cursor' => $cursor,
            'limit' => $limit,
            'customField' => $customField,
            'groupId' => $groupId,
            'status' => $status === null || $status === [] ? null : implode(',', array_map(static fn(MonitorStatus $item): string => $item->value, $status)),
            'name' => $name,
            'url' => $url,
            'tags' => $tags === null || $tags === [] ? null : implode(',', $tags),
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(Monitor::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * Filters combine with AND; status and tags match any of their values, while every customField entry ("key:value") must match, and the groupId 0 selects the monitors in no group (verified live). all() requests pages of 200 monitors, the most the API allows.
     *
     * `GET /monitors`
     *
     * @param int                      $limit       Maximum number of monitors to return per page. Default: 50, Min: 1, Max: 200.
     * @param list<string>|null        $customField Filter monitors by custom field key:value pairs. Format: customField=key:value. Multiple filters use AND logic. Split on first colon only.
     * @param int|null                 $groupId     Filter monitors by monitor group ID.
     * @param list<MonitorStatus>|null $status      Comma-separated list of status values to filter monitors. Uses OR logic (matches any specified status). Case-insensitive. Allowed values: PAUSED, STARTED, UP, LOOKS_DOWN, DOWN.
     * @param string|null              $name        Filter monitors by name. Case-insensitive partial match on the monitor friendly name.
     * @param string|null              $url         Filter monitors by URL. Case-insensitive partial match on the monitor URL.
     * @param list<string>|null        $tags        Comma-separated list of tag names to filter monitors. Uses OR logic (matches any specified tag). Case-sensitive.
     *
     * @return Paginator<Monitor>
     */
    public function all(
        int $limit = 200,
        ?array $customField = null,
        ?int $groupId = null,
        ?array $status = null,
        ?string $name = null,
        ?string $url = null,
        ?array $tags = null,
    ): Paginator {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
            limit: $limit,
            customField: $customField,
            groupId: $groupId,
            status: $status,
            name: $name,
            url: $url,
            tags: $tags,
        ));
    }

    /**
     * Get a monitor by ID
     *
     * Get a monitor details by ID
     *
     * `GET /monitors/{id}`
     *
     * @param int $id
     */
    public function get(int $id): Monitor
    {
        $data = $this->connection->json(Method::Get, "monitors/{$id}");

        return self::toModel(Monitor::class, $data);
    }

    /**
     * Create a monitor
     *
     * New monitors of any type can be created using this endpoint. The request body is documented as one schema per monitor type — pick the one matching the `type` you are creating.
     *
     * Pass the model of the monitor type, e.g. HttpMonitorCreate, which sends its type. A new monitor is STARTED until its first check and, unless they are set, reports authType HTTP_BASIC and httpMethodType null (verified live). The deprecated region string regionalData is left out; set the regions with regionData.
     *
     * `POST /monitors`
     *
     * @param MonitorCreate $monitor
     */
    public function create(MonitorCreate $monitor): Monitor
    {
        $data = $this->connection->json(Method::Post, 'monitors', body: $monitor->toArray());

        return self::toModel(Monitor::class, $data);
    }

    /**
     * Update a monitor
     *
     * Only the properties that are set are sent. config is merged into the current settings key by key (see MonitorConfigUpdate; null clears them), while customHttpHeaders, customFields and successHttpResponseCodes replace the current values (verified live).
     *
     * `PATCH /monitors/{id}`
     *
     * @param int           $id
     * @param MonitorUpdate $changes
     */
    public function update(int $id, MonitorUpdate $changes): Monitor
    {
        $data = $this->connection->json(Method::Patch, "monitors/{$id}", body: $changes->toArray());

        return self::toModel(Monitor::class, $data);
    }

    /**
     * Delete a monitor
     *
     * The monitor is gone at once; later calls for it fail with a NotFoundException (verified live).
     *
     * `DELETE /monitors/{id}`
     *
     * @param int $id
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "monitors/{$id}");
    }

    /**
     * Pause a monitor
     *
     * Pauses a single monitor by ID. The monitor will stop being checked until it is resumed. This operation is idempotent - pausing an already paused monitor will return successfully.
     *
     * Returns the monitor with the status PAUSED.
     *
     * `POST /monitors/{id}/pause`
     *
     * @param int $id
     */
    public function pause(int $id): Monitor
    {
        $data = $this->connection->json(Method::Post, "monitors/{$id}/pause", body: []);

        return self::toModel(Monitor::class, $data);
    }

    /**
     * Start a monitor
     *
     * Starts a paused monitor by ID. The monitor will resume being checked. This operation is idempotent - starting an already active monitor will return successfully.
     *
     * Returns the monitor, with the status STARTED until its next check (verified live).
     *
     * `POST /monitors/{id}/start`
     *
     * @param int $id
     */
    public function start(int $id): Monitor
    {
        $data = $this->connection->json(Method::Post, "monitors/{$id}/start", body: []);

        return self::toModel(Monitor::class, $data);
    }

    /**
     * Reset stats for a monitor
     *
     * Resets stats for a monitor. This includes the stats for incidents and alerts.
     *
     * `POST /monitors/{id}/reset`
     *
     * @param int $id
     */
    public function reset(int $id): void
    {
        $this->connection->json(Method::Post, "monitors/{$id}/reset", body: []);
    }

    /**
     * Get monitor uptime statistics
     *
     * Returns uptime statistics for a specific monitor within a configurable date range. Defaults to the last 24 hours. Maximum range is 90 days.
     *
     * The uptime is a percentage from 0 to 100, unlike the fraction that uptimeStats() reports. to without from is rejected with "Maximum range is 90 days" (both verified live).
     *
     * `GET /monitors/{id}/stats/uptime`
     *
     * @param int                    $id   The monitor ID
     * @param DateTimeInterface|null $from Start date for statistics (ISO 8601 format). Defaults to 24 hours ago.
     * @param DateTimeInterface|null $to   End date for statistics (ISO 8601 format). Defaults to now.
     */
    public function uptime(int $id, ?DateTimeInterface $from = null, ?DateTimeInterface $to = null): MonitorUptimeStats
    {
        $data = $this->connection->json(Method::Get, "monitors/{$id}/stats/uptime", [
            'from' => $from,
            'to' => $to,
        ]);

        return self::toModel(MonitorUptimeStats::class, $data);
    }

    /**
     * Get monitor response time statistics
     *
     * Returns response time statistics for a specific monitor within a configurable date range. Defaults to the last 24 hours. Maximum range is 90 days. Optionally includes time series data. Optionally filter by region.
     *
     * Times are in milliseconds. Pass from and to together or neither: from alone is rejected with "to must be a Date instance", to alone with "Maximum range is 90 days". timeSeries is empty unless includeTimeSeries is true; its points summarize longer intervals for longer ranges (all verified live).
     *
     * `GET /monitors/{id}/stats/response-time`
     *
     * @param int                     $id                The monitor ID
     * @param DateTimeInterface|null  $from              Start date for statistics (ISO 8601 format). Defaults to 24 hours ago.
     * @param DateTimeInterface|null  $to                End date for statistics (ISO 8601 format). Defaults to now.
     * @param bool|null               $includeTimeSeries Whether to include time series data points in the response. Defaults to false.
     * @param ResponseTimeRegion|null $region            Filter by region code (na, eu, as, oc). When provided, only returns data for the specified region.
     */
    public function responseTimeStats(
        int $id,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
        ?bool $includeTimeSeries = null,
        ?ResponseTimeRegion $region = null,
    ): ResponseTimeStats {
        $data = $this->connection->json(Method::Get, "monitors/{$id}/stats/response-time", [
            'from' => $from,
            'to' => $to,
            'includeTimeSeries' => $includeTimeSeries,
            'region' => $region,
        ]);

        return self::toModel(ResponseTimeStats::class, $data);
    }

    /**
     * Get monitor response time statistics by region
     *
     * Returns response time statistics for a specific monitor grouped by region within a configurable date range. Defaults to the last 24 hours. Maximum range is 90 days. Optionally includes time series data.
     *
     * Times are in milliseconds. Pass from and to together or neither, as for responseTimeStats(). The regions the monitor is not checked from are null (verified live).
     *
     * `GET /monitors/{id}/stats/response-time/all`
     *
     * @param int                    $id                The monitor ID
     * @param DateTimeInterface|null $from              Start date for statistics (ISO 8601 format). Defaults to 24 hours ago.
     * @param DateTimeInterface|null $to                End date for statistics (ISO 8601 format). Defaults to now.
     * @param bool|null              $includeTimeSeries Whether to include time series data points in the response. Defaults to false.
     */
    public function responseTimeStatsByRegion(
        int $id,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
        ?bool $includeTimeSeries = null,
    ): RegionalResponseTimeStats {
        $data = $this->connection->json(Method::Get, "monitors/{$id}/stats/response-time/all", [
            'from' => $from,
            'to' => $to,
            'includeTimeSeries' => $includeTimeSeries,
        ]);

        return self::toModel(RegionalResponseTimeStats::class, $data);
    }
}
