<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\StatusPage;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;
use GoSuccess\UptimeRobot\Resource\Handwritten\StatusPageOperations;

/** Public status pages: the monitors they show, their design and whether they are published. */
final class StatusPageResource extends AbstractResource
{
    use StatusPageOperations;

    /**
     * List PSPs
     *
     * List Public Status Pages
     *
     * The cursor is the ID of the last status page of the previous page, as the official Terraform provider reads it from nextLink. Only a single page was observable: an account without status pages gets {"data": []} without nextLink (verified live).
     *
     * `GET /psps`
     *
     * @param int|null $cursor The cursor of the page to return, as the previous page reported it; null for the first page.
     *
     * @return Page<StatusPage>
     */
    public function list(?int $cursor = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'psps', [
            'cursor' => $cursor,
        ]));

        return Cursor::fromNextLink($data, Cast::modelList(StatusPage::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * The cursor is the ID of the last status page of the previous page, as the official Terraform provider reads it from nextLink. Only a single page was observable: an account without status pages gets {"data": []} without nextLink (verified live).
     *
     * `GET /psps`
     *
     * @return Paginator<StatusPage>
     */
    public function all(): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
        ));
    }

    /**
     * Get a PSP by ID
     *
     * Get a Public Status Page by ID
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `GET /psps/{id}`
     *
     * @param int $id
     */
    public function get(int $id): StatusPage
    {
        $data = $this->connection->json(Method::Get, "psps/{$id}");

        return self::toModel(StatusPage::class, $data);
    }

    /**
     * Delete a PSP
     *
     * Delete a Public Status Page
     *
     * An unknown ID raises a NotFoundException (verified live).
     *
     * `DELETE /psps/{id}`
     *
     * @param int $id
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "psps/{$id}");
    }
}
