<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\StormProtectionSettings;
use GoSuccess\UptimeRobot\Model\StormProtectionUpdate;

/** Storm protection: the account-wide grouping of alerts when many monitors go down at once. */
final class StormProtectionResource extends AbstractResource
{
    /**
     * Get storm protection settings
     *
     * Get the account-wide storm protection (alert grouping) settings. Returns defaults when not yet configured.
     *
     * `GET /monitors/storm-protection`
     */
    public function get(): StormProtectionSettings
    {
        $data = $this->connection->json(Method::Get, 'monitors/storm-protection');

        return self::toModel(StormProtectionSettings::class, $data);
    }

    /**
     * Update storm protection settings
     *
     * Update the account-wide storm protection (alert grouping) settings. Partial update — only provided fields are changed.
     *
     * `PATCH /monitors/storm-protection`
     *
     * @param StormProtectionUpdate $changes
     */
    public function update(StormProtectionUpdate $changes): StormProtectionSettings
    {
        $data = $this->connection->json(Method::Patch, 'monitors/storm-protection', body: $changes->toArray());

        return self::toModel(StormProtectionSettings::class, $data);
    }
}
