<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\Cast;
use GoSuccess\UptimeRobot\Model\Tag;
use GoSuccess\UptimeRobot\Pagination\Cursor;
use GoSuccess\UptimeRobot\Pagination\Page;
use GoSuccess\UptimeRobot\Pagination\Paginator;

/** Tags of monitors. They are created by naming them on a monitor. */
final class TagResource extends AbstractResource
{
    /**
     * List user tags
     *
     * Get a paginated list of tags for the authenticated user, sorted by ID in ascending order
     *
     * `GET /tags`
     *
     * @param int|null $cursor The cursor of the page to return, as the previous page reported it; null for the first page.
     *
     * @return Page<Tag>
     */
    public function list(?int $cursor = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'tags', [
            'cursor' => $cursor,
        ]));

        return Cursor::fromNextCursorId($data, Cast::modelList(Tag::class, $data['data'] ?? null), integerCursor: true);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /tags`
     *
     * @return Paginator<Tag>
     */
    public function all(): Paginator
    {
        return new Paginator(fn(int|string|null $cursor): Page => $this->list(
            cursor: \is_int($cursor) ? $cursor : null,
        ));
    }

    /**
     * Delete a tag
     *
     * Delete a tag and remove it from all monitors
     *
     * `DELETE /tags/{id}`
     *
     * @param int $id Tag ID to delete
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "tags/{$id}");
    }
}
