<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Resource;

use GoSuccess\UptimeRobot\Http\Method;
use GoSuccess\UptimeRobot\Model\AlertContact;
use GoSuccess\UptimeRobot\Model\AllAlertContact;
use GoSuccess\UptimeRobot\Model\User;

/** The account the API key belongs to: its plan and its alert contacts. */
final class UserResource extends AbstractResource
{
    /**
     * Get current user
     *
     * `GET /user/me`
     */
    public function me(): User
    {
        $data = $this->connection->json(Method::Get, 'user/me');

        return self::toModel(User::class, $data);
    }

    /**
     * Get alert contacts
     *
     * `GET /user/alert-contacts`
     *
     * @return list<AlertContact>
     */
    public function alertContacts(): array
    {
        $data = $this->connection->json(Method::Get, 'user/alert-contacts');

        return self::toModelList(AlertContact::class, $data);
    }

    /**
     * Get all alert contacts
     *
     * Get all alert contacts including personal, notify-only, and organization members alert contacts
     *
     * `GET /user/all-alert-contacts`
     *
     * @return list<AllAlertContact>
     */
    public function allAlertContacts(): array
    {
        $data = $this->connection->json(Method::Get, 'user/all-alert-contacts');

        return self::toModelList(AllAlertContact::class, $data);
    }
}
