<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

use Deprecated;

/**
 * The kind of contact. E-mail and mobile app contacts can be created here; text message and voice contacts need a phone number verified in the dashboard.
 *
 * Schema: CreatePersonalAlertContactDto.type
 */
enum AlertContactType: string
{
    /** An e-mail address, given as value. */
    case Email = 'Email';

    /**
     * Text messages; cannot be created here, as the phone number must be verified in the dashboard (the specification).
     */
    case ProSms = 'ProSms';

    /**
     * Voice calls; cannot be created here, as the phone number must be verified in the dashboard (the specification).
     */
    case Voice = 'Voice';

    /** Push notifications to the iOS app. */
    case MobileAppIos = 'MobileAppIOS';

    /** Push notifications to the Android app. */
    case MobileAppAndroid = 'MobileAppAndroid';

    /**
     * Use MobileAppIos: the API accepts MobileAppOld for the iOS app through October 10, 2026, and rejects it after that date.
     *
     * @deprecated
     */
    #[Deprecated('Use MobileAppIos: the API accepts MobileAppOld for the iOS app through October 10, 2026, and rejects it after that date.')]
    case MobileAppOld = 'MobileAppOld';

    /**
     * Use MobileAppAndroid: the API accepts MobileApp for the Android app through October 10, 2026, and rejects it after that date.
     *
     * @deprecated
     */
    #[Deprecated('Use MobileAppAndroid: the API accepts MobileApp for the Android app through October 10, 2026, and rejects it after that date.')]
    case MobileApp = 'MobileApp';
}
