<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Schema: ActivityLogResponseDto.data[]<NOTIFICATION>.notificationStatus, PublicSentAlertsResponseDto.data[].status
 */
enum AlertDeliveryStatus: string
{
    case Success = 'SUCCESS';
    case NotDelivered = 'NOT_DELIVERED';
}
