<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Device platform (push)
 *
 * Schema: CreatePersonalAlertContactDto.platform
 */
enum AlertContactPlatform: string
{
    case Ios = 'ios';
    case Android = 'android';
}
