<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * An announcement status as the list filter takes it, in upper case, unlike AnnouncementStatus (per the specification; not verified live).
 *
 * Schema: PspAnnouncementsController_list.status
 */
enum AnnouncementStatusFilter: string
{
    case Offline = 'OFFLINE';
    case Pending = 'PENDING';
    case Published = 'PUBLISHED';
    case Archived = 'ARCHIVED';
}
