<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Type of the announcement. Possible values: Info (general information), Maintenance (scheduled maintenance notification), Issue (incident or issue notification)
 *
 * Schema: CreatePspAnnouncementRequestDto.type, UpdatePspAnnouncementRequestDto.type
 */
enum AnnouncementType: string
{
    case Info = 'Info';
    case Maintenance = 'Maintenance';
    case Issue = 'Issue';
}
