<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Status of the announcement. Possible values: Offline (draft, not visible on status page), Pending (scheduled for publication), Published (currently visible on status page), Archived (historical record, no longer visible)
 *
 * Schema: CreatePspAnnouncementRequestDto.status, UpdatePspAnnouncementRequestDto.status
 */
enum AnnouncementStatus: string
{
    case Offline = 'Offline';
    case Pending = 'Pending';
    case Published = 'Published';
    case Archived = 'Archived';
}
