<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Schema: IncidentDetailDto.rootCause.assertionDiagnostics.results[].actualTypes[], IncidentDetailDto.rootCause.assertionDiagnostics.results[].targetType
 */
enum AssertionValueType: string
{
    case Missing = 'missing';
    case Null = 'null';
    case Boolean = 'boolean';
    case Number = 'number';
    case String = 'string';
    case Array = 'array';
    case Object = 'object';
}
