<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Logic for combining assertions
 *
 * Schema: PublicApiAssertionsDto.logic
 */
enum AssertionLogic: string
{
    case And = 'AND';
    case Or = 'OR';
}
