<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Comparison operator
 *
 * Schema: PublicApiAssertionCheckDto.comparison
 */
enum AssertionComparison: string
{
    case Equals = 'equals';
    case NotEquals = 'not_equals';
    case Contains = 'contains';
    case NotContains = 'not_contains';
    case GreaterThan = 'greater_than';
    case LessThan = 'less_than';
    case IsNull = 'is_null';
    case IsNotNull = 'is_not_null';
    case IsString = 'is_string';
    case IsNumber = 'is_number';
    case IsBoolean = 'is_boolean';
    case IsArray = 'is_array';
    case IsObject = 'is_object';
    case IsEmpty = 'is_empty';
    case IsNotEmpty = 'is_not_empty';
    case LengthEquals = 'length_equals';
    case LengthNotEquals = 'length_not_equals';
    case LengthGreaterThan = 'length_greater_than';
    case LengthLessThan = 'length_less_than';
    case Exists = 'exists';
    case NotExists = 'not_exists';
}
