<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics.results[].failureReason */
enum AssertionFailureReason: string
{
    case NoMatch = 'no_match';
    case ValuePresent = 'value_present';
    case ResponseNotJson = 'response_not_json';
    case TypeMismatch = 'type_mismatch';
    case ComparisonFailed = 'comparison_failed';
    case InvalidJsonpath = 'invalid_jsonpath';
    case TooManyMatches = 'too_many_matches';
    case EvaluationLimitExceeded = 'evaluation_limit_exceeded';
    case UnsupportedValueType = 'unsupported_value_type';
    case DiagnosticPayloadTruncated = 'diagnostic_payload_truncated';
}
