<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics.results[].source */
enum AssertionSource: string
{
    case BodyJson = 'body_json';
    case Header = 'header';
    case StatusCode = 'status_code';
    case BodyText = 'body_text';
}
