<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: BulkOperationResponseDto.results[].status */
enum BulkOperationStatus: string
{
    case Success = 'success';
    case Error = 'error';
}
