<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The HTTP method of the check; null for HTTP and keyword monitors created without one, which use HEAD then (the documented default).
 *
 * Schema: MonitorDto.httpMethodType, CreateHttpMonitorDto.httpMethodType, CreateKeywordMonitorDto.httpMethodType, CreateApiMonitorDto.httpMethodType, UpdateMonitorDto.httpMethodType
 */
enum HttpMethod: string
{
    case Head = 'HEAD';
    case Get = 'GET';
    case Post = 'POST';
    case Put = 'PUT';
    case Patch = 'PATCH';
    case Delete = 'DELETE';
    case Options = 'OPTIONS';
    case Query = 'QUERY';
}
