<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The authentication of the check. Monitors created without one report HTTP_BASIC with empty credentials, whatever their type (verified live).
 *
 * Schema: MonitorDto.authType, CreateHttpMonitorDto.authType, CreateKeywordMonitorDto.authType, CreateApiMonitorDto.authType, UpdateMonitorDto.authType
 */
enum HttpAuthType: string
{
    case None = 'NONE';
    case HttpBasic = 'HTTP_BASIC';
    case Digest = 'DIGEST';
    case Bearer = 'BEARER';
}
