<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Schema: MonitorDto.config.ipVersion, HttpKeywordMonitorConfigDto.ipVersion, IpVersionMonitorConfigDto.ipVersion, ApiMonitorConfigDto.ipVersion, UdpMonitorConfigDto.ipVersion, UpdateMonitorConfigDto.ipVersion
 */
enum IpVersion: string
{
    case Ipv4Only = 'ipv4Only';
    case Ipv6Only = 'ipv6Only';
}
