<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Whether to alert when the keyword exists or when it does not; null on monitors of other types (verified live).
 *
 * Schema: MonitorDto.keywordType, CreateKeywordMonitorDto.keywordType, UpdateMonitorDto.keywordType
 */
enum KeywordType: string
{
    case AlertExists = 'ALERT_EXISTS';
    case AlertNotExists = 'ALERT_NOT_EXISTS';
}
