<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Whether the keyword match is case sensitive; CaseSensitive on monitors of other types (verified live).
 *
 * Schema: MonitorDto.keywordCaseType, CreateKeywordMonitorDto.keywordCaseType, UpdateMonitorDto.keywordCaseType
 */
enum KeywordCaseType: int
{
    case CaseSensitive = 0;
    case CaseInsensitive = 1;
}
