<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * active: the window suppresses the alerts of its monitors during its periods; paused: it does not.
 *
 * Schema: MaintenanceWindowDto.status, UpdateMaintenanceWindowDto.status
 */
enum MaintenanceWindowStatus: string
{
    case Active = 'active';
    case Paused = 'paused';
}
