<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The status of the monitor: UP, DOWN, LOOKS_DOWN, PAUSED, or STARTED, which a new or restarted monitor reports until its first check (verified live).
 *
 * Schema: MonitorsController_list.status[], MonitorDto.status, MonitorDto.tags[].monitors[].status
 */
enum MonitorStatus: string
{
    case Paused = 'PAUSED';
    case Started = 'STARTED';
    case Up = 'UP';
    case LooksDown = 'LOOKS_DOWN';
    case Down = 'DOWN';
}
