<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: MonitorDto.type, UpdateMonitorDto.type */
enum MonitorType: string
{
    case Http = 'HTTP';
    case Keyword = 'KEYWORD';
    case Ping = 'PING';
    case Port = 'PORT';
    case Heartbeat = 'HEARTBEAT';
    case Dns = 'DNS';
    case Api = 'API';
    case Udp = 'UDP';
    case VisualComparison = 'VISUAL_COMPARISON';
}
