<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Which status changes of its monitors the contact is alerted of.
 *
 * Schema: AlertContactDto.enableNotificationsFor, CreatePersonalAlertContactDto.enableNotificationsFor, UpdatePersonalAlertContactDto.enableNotificationsFor, IntegrationDto.enableNotificationsFor, SlackBaseIntegrationDto.enableNotificationsFor, TelegramBaseIntegrationDto.enableNotificationsFor, MsTeamsBaseIntegrationDto.enableNotificationsFor, WebhookBaseIntegrationDto.enableNotificationsFor, ZapierBaseIntegrationDto.enableNotificationsFor, CreatePagerdutyBaseIntegrationDto.enableNotificationsFor, GoogleChatBaseIntegrationDto.enableNotificationsFor, DiscordBaseIntegrationDto.enableNotificationsFor, SplunkBaseIntegrationDto.enableNotificationsFor, PushbulletBaseIntegrationDto.enableNotificationsFor, CreatePushoverBaseIntegrationDto.enableNotificationsFor, MattermostBaseIntegrationDto.enableNotificationsFor, UpdateSlackIntegrationDataDto.enableNotificationsFor, UpdateTelegramIntegrationDataDto.enableNotificationsFor, UpdateMsTeamsIntegrationDataDto.enableNotificationsFor, UpdateWebhookIntegrationDataDto.enableNotificationsFor, UpdateZapierIntegrationDataDto.enableNotificationsFor, UpdatePagerdutyIntegrationDataDto.enableNotificationsFor, PartialTypeClass.enableNotificationsFor, UpdateDiscordIntegrationDataDto.enableNotificationsFor, UpdateSplunkIntegrationDataDto.enableNotificationsFor, UpdatePushbulletIntegrationDataDto.enableNotificationsFor, UpdatePushoverIntegrationDataDto.enableNotificationsFor, UpdateMattermostIntegrationDataDto.enableNotificationsFor
 */
enum NotificationEvent: string
{
    case UpAndDown = 'UpAndDown';
    case Down = 'Down';
    case Up = 'Up';
    case None = 'None';
}
