<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: AlertContactDto.enableNotificationsFor */
enum NotificationEvent: string
{
    case UpAndDown = 'UpAndDown';
    case Down = 'Down';
    case Up = 'Up';
    case None = 'None';
}
