<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The PagerDuty Service region
 *
 * Schema: CreatePagerdutyBaseIntegrationDto.location, UpdatePagerdutyIntegrationDataDto.location
 */
enum PagerDutyLocation: string
{
    case UnitedStates = 'us';
    case Europe = 'eu';
}
