<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Schema: MonitorDto.postValueType, CreateHttpMonitorDto.postValueType, CreateKeywordMonitorDto.postValueType, CreateApiMonitorDto.postValueType, UpdateMonitorDto.postValueType
 */
enum PostValueType: string
{
    case KeyValue = 'KEY_VALUE';
    case RawJson = 'RAW_JSON';
}
