<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The Pushover priority of the notifications.
 *
 * Schema: CreatePushoverBaseIntegrationDto.priority, UpdatePushoverIntegrationDataDto.priority
 */
enum PushoverPriority: string
{
    case Lowest = 'Lowest';
    case Low = 'Low';
    case Normal = 'Normal';
    case High = 'High';
    case Emergency = 'Emergency';
}
