<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The checking infrastructure, set by the API (verified live: New).
 *
 * Schema: RegionalDataDto.INFRASTRUCTURE
 */
enum RegionInfrastructure: string
{
    case Legacy = 'Legacy';
    case New = 'New';
}
