<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: RegionalDataDto.REGION[] */
enum Region: string
{
    case NorthAmerica = 'na';
    case Europe = 'eu';
    case Asia = 'as';
    case Oceania = 'oc';
}
