<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The density of the page. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
 *
 * Schema: PspDto.customSettings.page.density, PageCustomSettingsDto.density
 */
enum StatusPageDensity: string
{
    case Normal = 'normal';
    case Compact = 'compact';
}
