<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * The color theme. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
 *
 * Schema: PspDto.customSettings.page.theme, PageCustomSettingsDto.theme
 */
enum StatusPageTheme: string
{
    case Light = 'light';
    case Dark = 'dark';
}
