<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * ENABLED publishes the page, PAUSED takes it offline.
 *
 * Schema: CreatePsPDto.status, UpdatePspDto.status
 */
enum StatusPageStatus: string
{
    case Enabled = 'ENABLED';
    case Paused = 'PAUSED';
}
