<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * How the monitors are ordered on the page. A manual order can only be arranged in the dashboard. Responses do not report the order.
 *
 * Schema: CreatePsPDto.sort, UpdatePspDto.sort
 */
enum StatusPageSort: string
{
    case FriendlyNameAsc = 'FriendlyNameAsc';
    case FriendlyNameDesc = 'FriendlyNameDesc';
    case StatusUpDownPaused = 'StatusUpDownPaused';
    case StatusDownUpPaused = 'StatusDownUpPaused';
}
