<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/**
 * Where the logo sits. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
 *
 * Schema: PspDto.customSettings.page.layout, PageCustomSettingsDto.layout
 */
enum StatusPageLayout: string
{
    case LogoOnLeft = 'logo_on_left';
    case LogoOnCenter = 'logo_on_center';
}
