<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: StormProtectionSettingsResponseDto.thresholdType, UpdateStormProtectionDto.thresholdType */
enum StormProtectionThresholdType: string
{
    case Count = 'count';
    case Percentage = 'percentage';
}
