<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: UptimeStatsDto.logs[].type */
enum UptimeLogType: string
{
    case Downtime = 'DOWNTIME';
    case SlowResponse = 'SLOW_RESPONSE';
}
