<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: MonitorsController_getUptimeStats.timeFrame */
enum UptimeTimeFrame: string
{
    case Day = 'DAY';
    case Week = 'WEEK';
    case Month = 'MONTH';
    case Days30 = 'DAYS_30';
    case Year = 'YEAR';
    case All = 'ALL';
    case Custom = 'CUSTOM';
}
