<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Enum;

/** Schema: MonitorDto.config.visualComparison.viewport, VisualComparisonFieldsDto.viewport */
enum VisualComparisonViewport: string
{
    case Desktop = 'desktop';
    case Mobile = 'mobile';
}
