<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * An entry of the activity log of an incident: a status update of the checks, a comment or a notification.
 *
 * Implemented by one model per "type": {@see StatusUpdateActivity}, {@see CommentActivity}, {@see
 * NotificationActivity}. A value this client does not know yet is read as {@see
 * UnknownActivityLogEntry}.
 *
 * Schema: ActivityLogResponseDto.data[]
 */
interface ActivityLogEntry extends ResponseModel {}
