<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\Region;

/**
 * An entry of the activity log of an incident: a status update of the checks, a comment or a notification.
 *
 * Implemented by one model per "type": {@see StatusUpdateActivity}, {@see CommentActivity}, {@see
 * NotificationActivity}. A value this client does not know yet is read as {@see
 * UnknownActivityLogEntry}. Each of them has the properties declared here; the others need an
 * instanceof check.
 *
 * Schema: ActivityLogResponseDto.data[]
 */
interface ActivityLogEntry extends ResponseModel
{
    public ?DateTimeImmutable $date { get; }

    public ?Region $region { get; }
}
