<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: AlertContactDto.config */
final readonly class AlertContactConfig implements ResponseModel
{
    public function __construct(
        public string $androidPushUpChannel = '',
        public string $androidPushDownChannel = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            androidPushUpChannel: Cast::string($data['android_push_up_channel'] ?? null) ?? '',
            androidPushDownChannel: Cast::string($data['android_push_down_channel'] ?? null) ?? '',
        );
    }
}
