<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/**
 * AlertContactPublic
 *
 * Schema: AlertContactDto
 */
final readonly class AlertContact implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $friendlyName = null,
        /**
         * Alert-contact type. Mobile push responses retain MobileAppOld (iOS) and MobileApp (Android) through October 10, 2026; consumers should also accept MobileAppIOS and MobileAppAndroid before responses switch to those canonical names after the deadline.
         */
        public string $type = '',
        public ?string $value = null,
        public ?string $customValue = null,
        public ?NotificationEvent $enableNotificationsFor = null,
        public ?bool $sslExpirationReminder = null,
        public ?string $httpUsername = null,
        public ?string $httpPassword = null,
        public ?bool $authType = null,
        /** @var array<array-key, string> */
        public array $customHeaders = [],
        public ?int $mobileProviderId = null,
        public string $status = '',
        public ?int $orgAlertContactId = null,
        public ?AlertContactConfig $config = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            friendlyName: Cast::string($data['friendlyName'] ?? null),
            type: Cast::string($data['type'] ?? null) ?? '',
            value: Cast::string($data['value'] ?? null),
            customValue: Cast::string($data['customValue'] ?? null),
            enableNotificationsFor: Cast::stringEnum(NotificationEvent::class, $data['enableNotificationsFor'] ?? null),
            sslExpirationReminder: Cast::bool($data['sslExpirationReminder'] ?? null),
            httpUsername: Cast::string($data['httpUsername'] ?? null),
            httpPassword: Cast::string($data['httpPassword'] ?? null),
            authType: Cast::bool($data['authType'] ?? null),
            customHeaders: Cast::mapOf($data['customHeaders'] ?? null, Cast::string(...)),
            mobileProviderId: Cast::int($data['mobileProviderId'] ?? null),
            status: Cast::string($data['status'] ?? null) ?? '',
            orgAlertContactId: Cast::int($data['orgAlertContactId'] ?? null),
            config: Cast::model(AlertContactConfig::class, $data['config'] ?? null),
        );
    }
}
