<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: AlertContactConfigDto */
final readonly class AlertContactConfig implements RequestModel, ResponseModel
{
    /**
     * The Android notification channel of up alerts, e.g. default_dnd (verified live); only for the Android app.
     */
    public string $androidPushUpChannel;

    /**
     * The Android notification channel of down alerts, e.g. default_dnd (verified live); only for the Android app.
     */
    public string $androidPushDownChannel;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined $androidPushUpChannel = Undefined::Value,
        string|Undefined $androidPushDownChannel = Undefined::Value,
    ) {
        $this->androidPushUpChannel = $androidPushUpChannel instanceof Undefined ? '' : $androidPushUpChannel;
        $this->androidPushDownChannel = $androidPushDownChannel instanceof Undefined ? '' : $androidPushDownChannel;
        $this->provided = array_filter([
            'android_push_up_channel' => !$androidPushUpChannel instanceof Undefined,
            'android_push_down_channel' => !$androidPushDownChannel instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            androidPushUpChannel: Cast::string($data['android_push_up_channel'] ?? null) ?? Undefined::Value,
            androidPushDownChannel: Cast::string($data['android_push_down_channel'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['android_push_up_channel'])) {
            $data['android_push_up_channel'] = $this->androidPushUpChannel;
        }

        if (isset($this->provided['android_push_down_channel'])) {
            $data['android_push_down_channel'] = $this->androidPushDownChannel;
        }

        return $data;
    }
}
