<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: UpdatePersonalAlertContactDto */
final readonly class AlertContactUpdate implements RequestModel
{
    public function __construct(
        /** Display name of the personal alert contact */
        public string|Undefined $friendlyName = Undefined::Value,
        /**
         * Which status changes of its monitors the contact is alerted of; sent by name, which the API turns into its number (verified live).
         */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Whether to send SSL certificate expiration reminders */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /**
         * true activates the contact (status Active), false pauses it (status Paused), so that it receives no alerts.
         */
        public bool|Undefined $isActive = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->isActive instanceof Undefined) {
            $data['isActive'] = $this->isActive;
        }

        return $data;
    }
}
