<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\AlertContactPlatform;
use GoSuccess\UptimeRobot\Enum\AlertContactType;
use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: CreatePersonalAlertContactDto */
final readonly class AlertContactCreate implements RequestModel
{
    public function __construct(
        /**
         * The kind of contact. E-mail and mobile app contacts can be created here; text message and voice contacts need a phone number verified in the dashboard.
         */
        public AlertContactType $type,
        /** Display name of the alert contact */
        public string|Undefined $friendlyName = Undefined::Value,
        /**
         * Which status changes of its monitors the contact is alerted of; sent by name, which the API turns into its number. The create request did not object to an invalid value (verified live), and the official Terraform provider sets it again with update() right after the create.
         */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /**
         * The e-mail address; required for Email contacts. Mobile app contacts are identified by the push fields instead.
         */
        public string|Undefined $value = Undefined::Value,
        /** Device name (push) */
        public string|Undefined $deviceName = Undefined::Value,
        /** OneSignal subscription ID (push) */
        public string|Undefined $oneSignalSubscriptionId = Undefined::Value,
        /** OneSignal user ID (push) */
        public string|Undefined $oneSignalUserId = Undefined::Value,
        /** Device fingerprint (push) */
        public string|Undefined $deviceFingerprint = Undefined::Value,
        /** Push notification token (push) */
        public string|Undefined $pushToken = Undefined::Value,
        /** Device platform (push) */
        public AlertContactPlatform|Undefined $platform = Undefined::Value,
        /** The notification channels of the Android app. */
        public AlertContactConfig|Undefined $config = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['type'] = $this->type->value;

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->value instanceof Undefined) {
            $data['value'] = $this->value;
        }

        if (!$this->deviceName instanceof Undefined) {
            $data['deviceName'] = $this->deviceName;
        }

        if (!$this->oneSignalSubscriptionId instanceof Undefined) {
            $data['oneSignalSubscriptionId'] = $this->oneSignalSubscriptionId;
        }

        if (!$this->oneSignalUserId instanceof Undefined) {
            $data['oneSignalUserId'] = $this->oneSignalUserId;
        }

        if (!$this->deviceFingerprint instanceof Undefined) {
            $data['deviceFingerprint'] = $this->deviceFingerprint;
        }

        if (!$this->pushToken instanceof Undefined) {
            $data['pushToken'] = $this->pushToken;
        }

        if (!$this->platform instanceof Undefined) {
            $data['platform'] = $this->platform->value;
        }

        if (!$this->config instanceof Undefined) {
            $data['config'] = Json::map($this->config->toArray());
        }

        return $data;
    }
}
