<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * AllAlertContactItem
 *
 * Schema: AllAlertContactDto.alertContacts[]
 */
final readonly class AllAlertContactItem implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $name = '',
        public string $value = '',
        /**
         * Alert-contact type. Mobile push responses retain MobileAppOld (iOS) and MobileApp (Android) through October 10, 2026; consumers should also accept MobileAppIOS and MobileAppAndroid before responses switch to those canonical names after the deadline.
         */
        public string $type = '',
        public string $status = '',
        public int $threshold = 0,
        public int $recurrence = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            value: Cast::string($data['value'] ?? null) ?? '',
            type: Cast::string($data['type'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            threshold: Cast::int($data['threshold'] ?? null) ?? 0,
            recurrence: Cast::int($data['recurrence'] ?? null) ?? 0,
        );
    }
}
