<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * AllAlertContactItem
 *
 * Schema: AllAlertContactDto.alertContacts[]
 */
final readonly class AllAlertContactItem implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $name = '',
        public string $value = '',
        /**
         * The kind of contact, e.g. Email, ProSms, Voice or MobileApp (verified live). The specification announces that mobile app contacts, reported as MobileAppOld (iOS) and MobileApp (Android) through October 10, 2026, become MobileAppIOS and MobileAppAndroid after that date; UptimeRobot's clients name further types such as EmailToSms, so this is a string.
         */
        public string $type = '',
        /**
         * Active, Paused, NotActivated or ToMigrate, the values UptimeRobot's guide for its MCP server (uptimerobot/ai, skills/list-integrations) and its Terraform provider name; only Active contacts deliver alerts. Verified live: Active, Paused and ToMigrate. A string, as the specification documents no values.
         */
        public string $status = '',
        public int $threshold = 0,
        public int $recurrence = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            value: Cast::string($data['value'] ?? null) ?? '',
            type: Cast::string($data['type'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            threshold: Cast::int($data['threshold'] ?? null) ?? 0,
            recurrence: Cast::int($data['recurrence'] ?? null) ?? 0,
        );
    }
}
