<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * AllAlertContact
 *
 * Schema: AllAlertContactDto
 */
final readonly class AllAlertContact implements ResponseModel
{
    public function __construct(
        public bool $notifyOnly = false,
        public ?int $orgAlertContactId = null,
        /** AllAlertContactUser */
        public AllAlertContactUser $user = new AllAlertContactUser(),
        /** @var list<AllAlertContactItem> */
        public array $alertContacts = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            notifyOnly: Cast::bool($data['notifyOnly'] ?? null) ?? false,
            orgAlertContactId: Cast::int($data['orgAlertContactId'] ?? null),
            user: Cast::model(AllAlertContactUser::class, $data['user'] ?? null) ?? new AllAlertContactUser(),
            alertContacts: Cast::modelList(AllAlertContactItem::class, $data['alertContacts'] ?? null),
        );
    }
}
