<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: PspAnnouncementResponseDto */
final readonly class Announcement implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        /** The status page. */
        public ?int $pspId = null,
        public ?int $userId = null,
        public ?string $title = null,
        public ?string $content = null,
        /**
         * The status: Offline (a draft, not shown), Pending (scheduled), Published (shown on the status page) or Archived (no longer shown). The specification documents the values in its description only; their casing in responses was not verifiable live.
         */
        public ?string $status = null,
        /**
         * The kind of announcement: Info, Maintenance or Issue. The specification documents the values in its description only; their casing in responses was not verifiable live.
         */
        public ?string $type = null,
        /**
         * Whether the announcement reached the subscribers: CantSend, InQueue or Sent. The specification documents the values in its description only; their casing in responses was not verifiable live.
         */
        public ?string $deliveryStatus = null,
        /** When the announcement starts. */
        public ?DateTimeImmutable $startDate = null,
        /** When the announcement ends; null if open-ended. */
        public ?DateTimeImmutable $endDate = null,
        /** When the announcement was created. */
        public ?DateTimeImmutable $creationDate = null,
        /** When the announcement was submitted; the specification does not describe it further. */
        public ?DateTimeImmutable $submitDate = null,
        public ?int $sentCount = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            pspId: Cast::int($data['pspId'] ?? null),
            userId: Cast::int($data['userId'] ?? null),
            title: Cast::string($data['title'] ?? null),
            content: Cast::string($data['content'] ?? null),
            status: Cast::string($data['status'] ?? null),
            type: Cast::string($data['type'] ?? null),
            deliveryStatus: Cast::string($data['deliveryStatus'] ?? null),
            startDate: Cast::dateTime($data['startDate'] ?? null),
            endDate: Cast::dateTime($data['endDate'] ?? null),
            creationDate: Cast::dateTime($data['creationDate'] ?? null),
            submitDate: Cast::dateTime($data['submitDate'] ?? null),
            sentCount: Cast::int($data['sentCount'] ?? null),
        );
    }
}
