<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeInterface;
use GoSuccess\UptimeRobot\Enum\AnnouncementStatus;
use GoSuccess\UptimeRobot\Enum\AnnouncementType;

/** Schema: UpdatePspAnnouncementRequestDto */
final readonly class AnnouncementUpdate implements RequestModel
{
    public function __construct(
        /** The title, at most 255 characters. */
        public string|Undefined $title = Undefined::Value,
        /** The text, at most 2000 characters. */
        public string|Undefined $content = Undefined::Value,
        /**
         * Status of the announcement. Possible values: Offline (draft, not visible on status page), Pending (scheduled for publication), Published (currently visible on status page), Archived (historical record, no longer visible)
         */
        public AnnouncementStatus|Undefined $status = Undefined::Value,
        /**
         * Type of the announcement. Possible values: Info (general information), Maintenance (scheduled maintenance notification), Issue (incident or issue notification)
         */
        public AnnouncementType|Undefined $type = Undefined::Value,
        /** When the announcement starts. */
        public DateTimeInterface|Undefined $startDate = Undefined::Value,
        /** When the announcement ends; null for no end. */
        public DateTimeInterface|Undefined|null $endDate = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->title instanceof Undefined) {
            $data['title'] = $this->title;
        }

        if (!$this->content instanceof Undefined) {
            $data['content'] = $this->content;
        }

        if (!$this->status instanceof Undefined) {
            $data['status'] = $this->status->value;
        }

        if (!$this->type instanceof Undefined) {
            $data['type'] = $this->type->value;
        }

        if (!$this->startDate instanceof Undefined) {
            $data['startDate'] = Json::date($this->startDate);
        }

        if (!$this->endDate instanceof Undefined) {
            $data['endDate'] = $this->endDate === null ? null : Json::date($this->endDate);
        }

        return $data;
    }
}
