<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\AssertionLogic;
use stdClass;

/** Schema: PublicApiAssertionsDto */
final readonly class ApiAssertions implements RequestModel, ResponseModel
{
    /** Logic for combining assertions */
    public ?AssertionLogic $logic;

    /**
     * Array of assertion checks (1-5)
     *
     * @var list<ApiAssertionCheck>
     */
    public array $checks;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /** @param list<ApiAssertionCheck>|Undefined $checks */
    public function __construct(
        AssertionLogic|Undefined $logic = Undefined::Value,
        array|Undefined $checks = Undefined::Value,
    ) {
        $this->logic = $logic instanceof Undefined ? null : $logic;
        $this->checks = $checks instanceof Undefined ? [] : $checks;
        $this->provided = array_filter([
            'logic' => !$logic instanceof Undefined,
            'checks' => !$checks instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            logic: Cast::stringEnum(AssertionLogic::class, $data['logic'] ?? null) ?? Undefined::Value,
            checks: Cast::modelList(ApiAssertionCheck::class, $data['checks'] ?? null) ?: Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['logic'])) {
            $data['logic'] = $this->logic?->value;
        }

        if (isset($this->provided['checks'])) {
            $data['checks'] = array_map(static fn(ApiAssertionCheck $item): array|stdClass => Json::map($item->toArray()), $this->checks);
        }

        return $data;
    }
}
