<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\AssertionComparison;

/** Schema: PublicApiAssertionCheckDto */
final readonly class ApiAssertionCheck implements RequestModel, ResponseModel
{
    /** Assertion source: safe JSONPath, headers.<name>, status_code, or body */
    public string $property;

    /** Comparison operator */
    public ?AssertionComparison $comparison;

    /**
     * Expected native JSON value. Arrays and objects are supported for body-JSON equality and containment; omit target for null, type, existence, and empty comparisons.
     */
    public mixed $target;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined $property = Undefined::Value,
        AssertionComparison|Undefined $comparison = Undefined::Value,
        mixed $target = Undefined::Value,
    ) {
        $this->property = $property instanceof Undefined ? '' : $property;
        $this->comparison = $comparison instanceof Undefined ? null : $comparison;
        $this->target = $target instanceof Undefined ? null : $target;
        $this->provided = array_filter([
            'property' => !$property instanceof Undefined,
            'comparison' => !$comparison instanceof Undefined,
            'target' => !$target instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            property: Cast::string($data['property'] ?? null) ?? Undefined::Value,
            comparison: Cast::stringEnum(AssertionComparison::class, $data['comparison'] ?? null) ?? Undefined::Value,
            target: \array_key_exists('target', $data) ? $data['target'] : Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['property'])) {
            $data['property'] = $this->property;
        }

        if (isset($this->provided['comparison'])) {
            $data['comparison'] = $this->comparison?->value;
        }

        if (isset($this->provided['target'])) {
            $data['target'] = $this->target;
        }

        return $data;
    }
}
