<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\IpVersion;

/** Schema: ApiMonitorConfigDto */
final readonly class ApiMonitorConfig implements RequestModel
{
    public function __construct(
        /** API monitor assertions configuration */
        public ApiAssertions $apiAssertions,
        /**
         * SSL expiration period in days (0-365, max 10 items)
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $sslExpirationPeriodDays = Undefined::Value,
        /** IP version preference. Omit for default behavior (IPv4 priority, falls back to IPv6) */
        public IpVersion|Undefined $ipVersion = Undefined::Value,
        /**
         * Number of retries on application errors (HTTP 4xx/5xx). 0-3. Connection errors always retry 3 times regardless of this setting.
         */
        public int|Undefined $applicationErrorRetries = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['apiAssertions'] = Json::map($this->apiAssertions->toArray());

        if (!$this->sslExpirationPeriodDays instanceof Undefined) {
            $data['sslExpirationPeriodDays'] = $this->sslExpirationPeriodDays;
        }

        if (!$this->ipVersion instanceof Undefined) {
            $data['ipVersion'] = $this->ipVersion->value;
        }

        if (!$this->applicationErrorRetries instanceof Undefined) {
            $data['applicationErrorRetries'] = $this->applicationErrorRetries;
        }

        return $data;
    }
}
