<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\HttpAuthType;
use GoSuccess\UptimeRobot\Enum\HttpMethod;
use GoSuccess\UptimeRobot\Enum\PostValueType;
use stdClass;

/** Schema: CreateApiMonitorDto */
final readonly class ApiMonitorCreate implements MonitorCreate
{
    /** The "type" of this variant of {@see MonitorCreate}. */
    public const string TYPE = 'API';

    public function __construct(
        /** Friendly name of the monitor */
        public string $friendlyName,
        /** Interval of check in seconds */
        public int $interval,
        /** URL of the API endpoint to monitor */
        public string $url,
        /** Timeout of check in seconds */
        public int $timeout,
        /** API monitor configuration. `apiAssertions` is required — at least one check must be provided */
        public ApiMonitorConfig $config,
        /**
         * Alert contacts to be assigned to the monitor. Threshold and recurrence are only available in the paid plans, they are always 0 in the Free Plan
         *
         * @var list<AssignedAlertContact>|Undefined
         */
        public array|Undefined $assignedAlertContacts = Undefined::Value,
        /**
         * Tags to be assigned to the monitor
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $tagNames = Undefined::Value,
        /**
         * Maintenance windows to be assigned to the monitor
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $maintenanceWindowsIds = Undefined::Value,
        /** Regional data for monitoring */
        public RegionalData|Undefined $regionData = Undefined::Value,
        /**
         * Response time threshold in milliseconds. When provided, the value is applied to all active regions as regionData.THRESHOLD. Always returns 0 — use regionData.THRESHOLD for per-region control.
         */
        public int|Undefined $responseTimeThreshold = Undefined::Value,
        /** Monitor group ID to assign the monitor to. Default is 0 (no group). */
        public int|Undefined $groupId = Undefined::Value,
        /**
         * Custom key-value metadata for the monitor. Max 20 keys. Keys: alphanumeric + underscore + hyphen, max 64 chars. Values: max 255 chars. Paid plans only.
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customFields = Undefined::Value,
        /**
         * HTTP method to use for the request. Defaults to GET. HEAD is not allowed for API monitors because assertions need a response body
         */
        public HttpMethod|Undefined $httpMethodType = Undefined::Value,
        /** Authentication method to use for the request */
        public HttpAuthType|Undefined $authType = Undefined::Value,
        /** Username for HTTP Basic authentication */
        public string|Undefined $httpUsername = Undefined::Value,
        /** Password for HTTP Basic authentication */
        public string|Undefined $httpPassword = Undefined::Value,
        /**
         * The body the check sends: an array, sent as a JSON object, or a JSON string; the API stores either as an object (verified live). Not applicable for the HTTP method HEAD.
         */
        public mixed $postValueData = Undefined::Value,
        /**
         * Type of data payload to be sent in the request. Affects what data is accepted by "postValueData" field
         */
        public PostValueType|Undefined $postValueType = Undefined::Value,
        /**
         * Custom HTTP headers to be sent in the request. Must be sent as JSON object with key-value pairs. The serialized JSON must not exceed 3000 characters
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customHttpHeaders = Undefined::Value,
        /**
         * Success HTTP response codes. Can contain specific codes or ranges like 2xx. Default is [2xx, 3xx]
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $successHttpResponseCodes = Undefined::Value,
        /** Whether to check for SSL and domain expiration errors */
        public bool|Undefined $checkSslErrors = Undefined::Value,
        /** Whether to send a notification when the SSL certificate is about to expire */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** Whether to send a notification when the domain is about to expire */
        public bool|Undefined $domainExpirationReminder = Undefined::Value,
        /** Whether to follow redirections */
        public bool|Undefined $followRedirections = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = ['type' => self::TYPE];
        $data['friendlyName'] = $this->friendlyName;
        $data['interval'] = $this->interval;
        $data['url'] = $this->url;
        $data['timeout'] = $this->timeout;
        $data['config'] = Json::map($this->config->toArray());

        if (!$this->assignedAlertContacts instanceof Undefined) {
            $data['assignedAlertContacts'] = array_map(static fn(AssignedAlertContact $item): array|stdClass => Json::map($item->toArray()), $this->assignedAlertContacts);
        }

        if (!$this->tagNames instanceof Undefined) {
            $data['tagNames'] = $this->tagNames;
        }

        if (!$this->maintenanceWindowsIds instanceof Undefined) {
            $data['maintenanceWindowsIds'] = $this->maintenanceWindowsIds;
        }

        if (!$this->regionData instanceof Undefined) {
            $data['regionData'] = Json::map($this->regionData->toArray());
        }

        if (!$this->responseTimeThreshold instanceof Undefined) {
            $data['responseTimeThreshold'] = $this->responseTimeThreshold;
        }

        if (!$this->groupId instanceof Undefined) {
            $data['groupId'] = $this->groupId;
        }

        if (!$this->customFields instanceof Undefined) {
            $data['customFields'] = Json::map($this->customFields);
        }

        if (!$this->httpMethodType instanceof Undefined) {
            $data['httpMethodType'] = $this->httpMethodType->value;
        }

        if (!$this->authType instanceof Undefined) {
            $data['authType'] = $this->authType->value;
        }

        if (!$this->httpUsername instanceof Undefined) {
            $data['httpUsername'] = $this->httpUsername;
        }

        if (!$this->httpPassword instanceof Undefined) {
            $data['httpPassword'] = $this->httpPassword;
        }

        if (!$this->postValueData instanceof Undefined) {
            $data['postValueData'] = $this->postValueData;
        }

        if (!$this->postValueType instanceof Undefined) {
            $data['postValueType'] = $this->postValueType->value;
        }

        if (!$this->customHttpHeaders instanceof Undefined) {
            $data['customHttpHeaders'] = Json::map($this->customHttpHeaders);
        }

        if (!$this->successHttpResponseCodes instanceof Undefined) {
            $data['successHttpResponseCodes'] = $this->successHttpResponseCodes;
        }

        if (!$this->checkSslErrors instanceof Undefined) {
            $data['checkSSLErrors'] = $this->checkSslErrors;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->domainExpirationReminder instanceof Undefined) {
            $data['domainExpirationReminder'] = $this->domainExpirationReminder;
        }

        if (!$this->followRedirections instanceof Undefined) {
            $data['followRedirections'] = $this->followRedirections;
        }

        return $data;
    }
}
