<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\AssertionLogic;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics */
final readonly class AssertionDiagnostics implements ResponseModel
{
    public function __construct(
        public int $version = 0,
        public ?AssertionLogic $logic = null,
        public AssertionDiagnosticsSummary $summary = new AssertionDiagnosticsSummary(),
        /** @var list<AssertionResult> */
        public array $results = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            version: Cast::int($data['version'] ?? null) ?? 0,
            logic: Cast::stringEnum(AssertionLogic::class, $data['logic'] ?? null),
            summary: Cast::model(AssertionDiagnosticsSummary::class, $data['summary'] ?? null) ?? new AssertionDiagnosticsSummary(),
            results: Cast::modelList(AssertionResult::class, $data['results'] ?? null),
        );
    }
}
