<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics.results[].failingSamples[] */
final readonly class AssertionFailingSample implements ResponseModel
{
    public function __construct(
        public string $path = '',
        public string $actualSummary = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            path: Cast::string($data['path'] ?? null) ?? '',
            actualSummary: Cast::string($data['actualSummary'] ?? null) ?? '',
        );
    }
}
