<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics.summary */
final readonly class AssertionDiagnosticsSummary implements ResponseModel
{
    public function __construct(
        public bool $passed = false,
        public int $total = 0,
        public int $passedCount = 0,
        public int $failedCount = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            passed: Cast::bool($data['passed'] ?? null) ?? false,
            total: Cast::int($data['total'] ?? null) ?? 0,
            passedCount: Cast::int($data['passedCount'] ?? null) ?? 0,
            failedCount: Cast::int($data['failedCount'] ?? null) ?? 0,
        );
    }
}
