<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\AssertionComparison;
use GoSuccess\UptimeRobot\Enum\AssertionFailureReason;
use GoSuccess\UptimeRobot\Enum\AssertionSource;
use GoSuccess\UptimeRobot\Enum\AssertionValueType;

/** Schema: IncidentDetailDto.rootCause.assertionDiagnostics.results[] */
final readonly class AssertionResult implements ResponseModel
{
    public function __construct(
        public int $index = 0,
        public string $property = '',
        public ?AssertionSource $source = null,
        public string $selector = '',
        public ?AssertionComparison $comparison = null,
        public bool $passed = false,
        /** @var list<AssertionValueType> */
        public array $actualTypes = [],
        public string $actualSummary = '',
        public ?AssertionValueType $targetType = null,
        public string $targetSummary = '',
        public int $selectedCount = 0,
        public int $failedCount = 0,
        /** @var list<AssertionFailingSample> */
        public array $failingSamples = [],
        public ?AssertionFailureReason $failureReason = null,
        public bool $truncated = false,
        public bool $redacted = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            index: Cast::int($data['index'] ?? null) ?? 0,
            property: Cast::string($data['property'] ?? null) ?? '',
            source: Cast::stringEnum(AssertionSource::class, $data['source'] ?? null),
            selector: Cast::string($data['selector'] ?? null) ?? '',
            comparison: Cast::stringEnum(AssertionComparison::class, $data['comparison'] ?? null),
            passed: Cast::bool($data['passed'] ?? null) ?? false,
            actualTypes: Cast::listOf($data['actualTypes'] ?? null, static fn(mixed $value): ?AssertionValueType => Cast::stringEnum(AssertionValueType::class, $value)),
            actualSummary: Cast::string($data['actualSummary'] ?? null) ?? '',
            targetType: Cast::stringEnum(AssertionValueType::class, $data['targetType'] ?? null),
            targetSummary: Cast::string($data['targetSummary'] ?? null) ?? '',
            selectedCount: Cast::int($data['selectedCount'] ?? null) ?? 0,
            failedCount: Cast::int($data['failedCount'] ?? null) ?? 0,
            failingSamples: Cast::modelList(AssertionFailingSample::class, $data['failingSamples'] ?? null),
            failureReason: Cast::stringEnum(AssertionFailureReason::class, $data['failureReason'] ?? null),
            truncated: Cast::bool($data['truncated'] ?? null) ?? false,
            redacted: Cast::bool($data['redacted'] ?? null) ?? false,
        );
    }
}
