<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: AlertContactSettings */
final readonly class AssignedAlertContact implements RequestModel, ResponseModel
{
    /** ID of the alert contact to notify */
    public int $alertContactId;

    /** Delay of notification in minutes, after the monitor is down */
    public int $threshold;

    /** Repeat notifications every X minutes */
    public int $recurrence;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        int|Undefined $alertContactId = Undefined::Value,
        int|Undefined $threshold = Undefined::Value,
        int|Undefined $recurrence = Undefined::Value,
    ) {
        $this->alertContactId = $alertContactId instanceof Undefined ? 0 : $alertContactId;
        $this->threshold = $threshold instanceof Undefined ? 0 : $threshold;
        $this->recurrence = $recurrence instanceof Undefined ? 0 : $recurrence;
        $this->provided = array_filter([
            'alertContactId' => !$alertContactId instanceof Undefined,
            'threshold' => !$threshold instanceof Undefined,
            'recurrence' => !$recurrence instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            alertContactId: Cast::int($data['alertContactId'] ?? null) ?? Undefined::Value,
            threshold: Cast::int($data['threshold'] ?? null) ?? Undefined::Value,
            recurrence: Cast::int($data['recurrence'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['alertContactId'])) {
            $data['alertContactId'] = $this->alertContactId;
        }

        if (isset($this->provided['threshold'])) {
            $data['threshold'] = $this->threshold;
        }

        if (isset($this->provided['recurrence'])) {
            $data['recurrence'] = $this->recurrence;
        }

        return $data;
    }
}
