<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PublicBulkUpdateDto */
final readonly class BulkMonitorUpdate implements RequestModel
{
    public function __construct(
        /** Monitoring interval in seconds */
        public int|Undefined $interval = Undefined::Value,
        /** Timeout in seconds */
        public int|Undefined $timeout = Undefined::Value,
        /** Grace period in seconds */
        public int|Undefined $gracePeriod = Undefined::Value,
        /** Whether to check for SSL errors */
        public bool|Undefined $checkSslErrors = Undefined::Value,
        /** Whether to enable domain expiration reminder */
        public bool|Undefined $domainExpirationReminder = Undefined::Value,
        /** Whether to enable SSL expiration reminder */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** Response time threshold in milliseconds */
        public int|Undefined $responseTimeThreshold = Undefined::Value,
        /** Regional data configuration */
        public RegionalData|Undefined $regionalData = Undefined::Value,
        /**
         * Custom key-value metadata to set on the selected monitors; a single monitor's update replaces all its fields (verified live), the bulk update presumably too (not verified). Max 20 keys. Keys: alphanumeric + underscore + hyphen, max 64 chars. Values: max 255 chars. Paid plans only.
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customFields = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->interval instanceof Undefined) {
            $data['interval'] = $this->interval;
        }

        if (!$this->timeout instanceof Undefined) {
            $data['timeout'] = $this->timeout;
        }

        if (!$this->gracePeriod instanceof Undefined) {
            $data['gracePeriod'] = $this->gracePeriod;
        }

        if (!$this->checkSslErrors instanceof Undefined) {
            $data['checkSSLErrors'] = $this->checkSslErrors;
        }

        if (!$this->domainExpirationReminder instanceof Undefined) {
            $data['domainExpirationReminder'] = $this->domainExpirationReminder;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->responseTimeThreshold instanceof Undefined) {
            $data['responseTimeThreshold'] = $this->responseTimeThreshold;
        }

        if (!$this->regionalData instanceof Undefined) {
            $data['regionalData'] = Json::map($this->regionalData->toArray());
        }

        if (!$this->customFields instanceof Undefined) {
            $data['customFields'] = Json::map($this->customFields);
        }

        return $data;
    }
}
