<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\BulkOperationStatus;

/** Schema: BulkOperationResponseDto.results[] */
final readonly class BulkOperationItem implements ResponseModel
{
    public function __construct(
        public int $monitorId = 0,
        public string $monitorName = '',
        public ?BulkOperationStatus $status = null,
        public ?string $error = null,
        public ?string $code = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            monitorId: Cast::int($data['monitorId'] ?? null) ?? 0,
            monitorName: Cast::string($data['monitorName'] ?? null) ?? '',
            status: Cast::stringEnum(BulkOperationStatus::class, $data['status'] ?? null),
            error: Cast::string($data['error'] ?? null),
            code: Cast::string($data['code'] ?? null),
        );
    }
}
