<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: BulkOperationResponseDto */
final readonly class BulkOperationResult implements ResponseModel
{
    public function __construct(
        /** @var list<BulkOperationItem> */
        public array $results = [],
        public int $totalSuccess = 0,
        public int $totalError = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            results: Cast::modelList(BulkOperationItem::class, $data['results'] ?? null),
            totalSuccess: Cast::int($data['totalSuccess'] ?? null) ?? 0,
            totalError: Cast::int($data['totalError'] ?? null) ?? 0,
        );
    }
}
