<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\Region;

/** Schema: ActivityLogResponseDto.data[]<COMMENT> */
final readonly class CommentActivity implements ActivityLogEntry
{
    /** The "type" of this variant of {@see ActivityLogEntry}. */
    public const string TYPE = 'COMMENT';

    public function __construct(
        public ?DateTimeImmutable $date = null,
        public ?Region $region = null,
        public int $commentId = 0,
        public string $commentFullName = '',
        public string $commentEmail = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            date: Cast::dateTime($data['date'] ?? null),
            region: Cast::stringEnum(Region::class, $data['region'] ?? null),
            commentId: Cast::int($data['commentId'] ?? null) ?? 0,
            commentFullName: Cast::string($data['commentFullName'] ?? null) ?? '',
            commentEmail: Cast::string($data['commentEmail'] ?? null) ?? '',
        );
    }
}
