<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: DnsMonitorConfigDto */
final readonly class DnsMonitorConfig implements RequestModel
{
    public function __construct(
        /** DNS records configuration */
        public DnsRecords|Undefined $dnsRecords = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->dnsRecords instanceof Undefined) {
            $data['dnsRecords'] = Json::map($this->dnsRecords->toArray());
        }

        return $data;
    }
}
