<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use stdClass;

/** Schema: CreateDnsMonitorDto */
final readonly class DnsMonitorCreate implements MonitorCreate
{
    /** The "type" of this variant of {@see MonitorCreate}. */
    public const string TYPE = 'DNS';

    public function __construct(
        /** Friendly name of the monitor */
        public string $friendlyName,
        /** Interval of check in seconds */
        public int $interval,
        /** DNS server IP or hostname. A protocol prefix is stripped if provided */
        public string $url,
        /** DNS monitor configuration — the records to resolve and match */
        public DnsMonitorConfig $config,
        /**
         * Alert contacts to be assigned to the monitor. Threshold and recurrence are only available in the paid plans, they are always 0 in the Free Plan
         *
         * @var list<AssignedAlertContact>|Undefined
         */
        public array|Undefined $assignedAlertContacts = Undefined::Value,
        /**
         * Tags to be assigned to the monitor
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $tagNames = Undefined::Value,
        /**
         * Maintenance windows to be assigned to the monitor
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $maintenanceWindowsIds = Undefined::Value,
        /** Regional data for monitoring */
        public RegionalData|Undefined $regionData = Undefined::Value,
        /**
         * Response time threshold in milliseconds. When provided, the value is applied to all active regions as regionData.THRESHOLD. Always returns 0 — use regionData.THRESHOLD for per-region control.
         */
        public int|Undefined $responseTimeThreshold = Undefined::Value,
        /** Monitor group ID to assign the monitor to. Default is 0 (no group). */
        public int|Undefined $groupId = Undefined::Value,
        /**
         * Custom key-value metadata for the monitor. Max 20 keys. Keys: alphanumeric + underscore + hyphen, max 64 chars. Values: max 255 chars. Paid plans only.
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customFields = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = ['type' => self::TYPE];
        $data['friendlyName'] = $this->friendlyName;
        $data['interval'] = $this->interval;
        $data['url'] = $this->url;
        $data['config'] = Json::map($this->config->toArray());

        if (!$this->assignedAlertContacts instanceof Undefined) {
            $data['assignedAlertContacts'] = array_map(static fn(AssignedAlertContact $item): array|stdClass => Json::map($item->toArray()), $this->assignedAlertContacts);
        }

        if (!$this->tagNames instanceof Undefined) {
            $data['tagNames'] = $this->tagNames;
        }

        if (!$this->maintenanceWindowsIds instanceof Undefined) {
            $data['maintenanceWindowsIds'] = $this->maintenanceWindowsIds;
        }

        if (!$this->regionData instanceof Undefined) {
            $data['regionData'] = Json::map($this->regionData->toArray());
        }

        if (!$this->responseTimeThreshold instanceof Undefined) {
            $data['responseTimeThreshold'] = $this->responseTimeThreshold;
        }

        if (!$this->groupId instanceof Undefined) {
            $data['groupId'] = $this->groupId;
        }

        if (!$this->customFields instanceof Undefined) {
            $data['customFields'] = Json::map($this->customFields);
        }

        return $data;
    }
}
