<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: DnsRecordsDto */
final readonly class DnsRecords implements RequestModel, ResponseModel
{
    /**
     * CNAME DNS records
     *
     * @var list<string>
     */
    public array $cname;

    /**
     * MX DNS records
     *
     * @var list<string>
     */
    public array $mx;

    /**
     * NS DNS records
     *
     * @var list<string>
     */
    public array $ns;

    /**
     * A DNS records
     *
     * @var list<string>
     */
    public array $a;

    /**
     * AAAA DNS records
     *
     * @var list<string>
     */
    public array $aaaa;

    /**
     * TXT DNS records
     *
     * @var list<string>
     */
    public array $txt;

    /**
     * SRV DNS records
     *
     * @var list<string>
     */
    public array $srv;

    /**
     * PTR DNS records
     *
     * @var list<string>
     */
    public array $ptr;

    /**
     * SOA DNS records
     *
     * @var list<string>
     */
    public array $soa;

    /**
     * SPF DNS records
     *
     * @var list<string>
     */
    public array $spf;

    /**
     * DNSKEY DNS records
     *
     * @var list<string>
     */
    public array $dnskey;

    /**
     * DS DNS records
     *
     * @var list<string>
     */
    public array $ds;

    /**
     * NSEC DNS records
     *
     * @var list<string>
     */
    public array $nsec;

    /**
     * NSEC3 DNS records
     *
     * @var list<string>
     */
    public array $nsec3;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param list<string>|Undefined $cname
     * @param list<string>|Undefined $mx
     * @param list<string>|Undefined $ns
     * @param list<string>|Undefined $a
     * @param list<string>|Undefined $aaaa
     * @param list<string>|Undefined $txt
     * @param list<string>|Undefined $srv
     * @param list<string>|Undefined $ptr
     * @param list<string>|Undefined $soa
     * @param list<string>|Undefined $spf
     * @param list<string>|Undefined $dnskey
     * @param list<string>|Undefined $ds
     * @param list<string>|Undefined $nsec
     * @param list<string>|Undefined $nsec3
     */
    public function __construct(
        array|Undefined $cname = Undefined::Value,
        array|Undefined $mx = Undefined::Value,
        array|Undefined $ns = Undefined::Value,
        array|Undefined $a = Undefined::Value,
        array|Undefined $aaaa = Undefined::Value,
        array|Undefined $txt = Undefined::Value,
        array|Undefined $srv = Undefined::Value,
        array|Undefined $ptr = Undefined::Value,
        array|Undefined $soa = Undefined::Value,
        array|Undefined $spf = Undefined::Value,
        array|Undefined $dnskey = Undefined::Value,
        array|Undefined $ds = Undefined::Value,
        array|Undefined $nsec = Undefined::Value,
        array|Undefined $nsec3 = Undefined::Value,
    ) {
        $this->cname = $cname instanceof Undefined ? [] : $cname;
        $this->mx = $mx instanceof Undefined ? [] : $mx;
        $this->ns = $ns instanceof Undefined ? [] : $ns;
        $this->a = $a instanceof Undefined ? [] : $a;
        $this->aaaa = $aaaa instanceof Undefined ? [] : $aaaa;
        $this->txt = $txt instanceof Undefined ? [] : $txt;
        $this->srv = $srv instanceof Undefined ? [] : $srv;
        $this->ptr = $ptr instanceof Undefined ? [] : $ptr;
        $this->soa = $soa instanceof Undefined ? [] : $soa;
        $this->spf = $spf instanceof Undefined ? [] : $spf;
        $this->dnskey = $dnskey instanceof Undefined ? [] : $dnskey;
        $this->ds = $ds instanceof Undefined ? [] : $ds;
        $this->nsec = $nsec instanceof Undefined ? [] : $nsec;
        $this->nsec3 = $nsec3 instanceof Undefined ? [] : $nsec3;
        $this->provided = array_filter([
            'CNAME' => !$cname instanceof Undefined,
            'MX' => !$mx instanceof Undefined,
            'NS' => !$ns instanceof Undefined,
            'A' => !$a instanceof Undefined,
            'AAAA' => !$aaaa instanceof Undefined,
            'TXT' => !$txt instanceof Undefined,
            'SRV' => !$srv instanceof Undefined,
            'PTR' => !$ptr instanceof Undefined,
            'SOA' => !$soa instanceof Undefined,
            'SPF' => !$spf instanceof Undefined,
            'DNSKEY' => !$dnskey instanceof Undefined,
            'DS' => !$ds instanceof Undefined,
            'NSEC' => !$nsec instanceof Undefined,
            'NSEC3' => !$nsec3 instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            cname: Cast::listOf($data['CNAME'] ?? null, Cast::string(...)) ?: Undefined::Value,
            mx: Cast::listOf($data['MX'] ?? null, Cast::string(...)) ?: Undefined::Value,
            ns: Cast::listOf($data['NS'] ?? null, Cast::string(...)) ?: Undefined::Value,
            a: Cast::listOf($data['A'] ?? null, Cast::string(...)) ?: Undefined::Value,
            aaaa: Cast::listOf($data['AAAA'] ?? null, Cast::string(...)) ?: Undefined::Value,
            txt: Cast::listOf($data['TXT'] ?? null, Cast::string(...)) ?: Undefined::Value,
            srv: Cast::listOf($data['SRV'] ?? null, Cast::string(...)) ?: Undefined::Value,
            ptr: Cast::listOf($data['PTR'] ?? null, Cast::string(...)) ?: Undefined::Value,
            soa: Cast::listOf($data['SOA'] ?? null, Cast::string(...)) ?: Undefined::Value,
            spf: Cast::listOf($data['SPF'] ?? null, Cast::string(...)) ?: Undefined::Value,
            dnskey: Cast::listOf($data['DNSKEY'] ?? null, Cast::string(...)) ?: Undefined::Value,
            ds: Cast::listOf($data['DS'] ?? null, Cast::string(...)) ?: Undefined::Value,
            nsec: Cast::listOf($data['NSEC'] ?? null, Cast::string(...)) ?: Undefined::Value,
            nsec3: Cast::listOf($data['NSEC3'] ?? null, Cast::string(...)) ?: Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['CNAME'])) {
            $data['CNAME'] = $this->cname;
        }

        if (isset($this->provided['MX'])) {
            $data['MX'] = $this->mx;
        }

        if (isset($this->provided['NS'])) {
            $data['NS'] = $this->ns;
        }

        if (isset($this->provided['A'])) {
            $data['A'] = $this->a;
        }

        if (isset($this->provided['AAAA'])) {
            $data['AAAA'] = $this->aaaa;
        }

        if (isset($this->provided['TXT'])) {
            $data['TXT'] = $this->txt;
        }

        if (isset($this->provided['SRV'])) {
            $data['SRV'] = $this->srv;
        }

        if (isset($this->provided['PTR'])) {
            $data['PTR'] = $this->ptr;
        }

        if (isset($this->provided['SOA'])) {
            $data['SOA'] = $this->soa;
        }

        if (isset($this->provided['SPF'])) {
            $data['SPF'] = $this->spf;
        }

        if (isset($this->provided['DNSKEY'])) {
            $data['DNSKEY'] = $this->dnskey;
        }

        if (isset($this->provided['DS'])) {
            $data['DS'] = $this->ds;
        }

        if (isset($this->provided['NSEC'])) {
            $data['NSEC'] = $this->nsec;
        }

        if (isset($this->provided['NSEC3'])) {
            $data['NSEC3'] = $this->nsec3;
        }

        return $data;
    }
}
