<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: IncidentCommentDto */
final readonly class IncidentComment implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        /** The text of the comment, which create() and update() send as content. */
        public string $comment = '',
        public bool $publishOnStatusPage = false,
        /** When the comment was written. */
        public ?DateTimeImmutable $created = null,
        public IncidentCommentUser $user = new IncidentCommentUser(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            comment: Cast::string($data['comment'] ?? null) ?? '',
            publishOnStatusPage: Cast::bool($data['publishOnStatusPage'] ?? null) ?? false,
            created: Cast::dateTime($data['created'] ?? null),
            user: Cast::model(IncidentCommentUser::class, $data['user'] ?? null) ?? new IncidentCommentUser(),
        );
    }
}
