<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: IncidentDetailDto.rootCause */
final readonly class IncidentRootCause implements ResponseModel
{
    public function __construct(
        /**
         * The HTTP method and the URL of the failed check, e.g. "GET https://example.com/"; empty for a slow response (verified live).
         */
        public ?string $url = null,
        /**
         * The headers the check sent, by name; empty for a slow response (verified live).
         *
         * @var array<array-key, string>
         */
        public array $requestHeaders = [],
        /**
         * The headers of the response, each name with the list of its values; empty if no response came and for a slow response (verified live).
         *
         * @var array<array-key, list<string>>
         */
        public array $responseHeaders = [],
        /**
         * The HTTP status code of the response; null if no response came or for a slow response (verified live).
         */
        public ?int $httpResponseCode = null,
        /**
         * Where to download the response body; empty or null if there is none (verified live; never set on the incidents read).
         */
        public ?string $responseDownloadUrl = null,
        public ?AssertionDiagnostics $assertionDiagnostics = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            url: Cast::string($data['url'] ?? null),
            requestHeaders: Cast::mapOf($data['requestHeaders'] ?? null, Cast::string(...)),
            responseHeaders: Cast::mapOf($data['responseHeaders'] ?? null, static fn(mixed $value): array => Cast::listOf($value, Cast::string(...))),
            httpResponseCode: Cast::int($data['httpResponseCode'] ?? null),
            responseDownloadUrl: Cast::string($data['responseDownloadUrl'] ?? null),
            assertionDiagnostics: Cast::model(AssertionDiagnostics::class, $data['assertionDiagnostics'] ?? null),
        );
    }
}
