<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: CreateIncidentCommentRequestDto */
final readonly class IncidentCommentCreate implements RequestModel
{
    public function __construct(
        /** The text of the comment, at most 10000 characters; responses name it comment. */
        public string $content,
        /** Whether the comment is published on the status page; false by default. */
        public bool|Undefined $publishOnStatusPage = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['content'] = $this->content;

        if (!$this->publishOnStatusPage instanceof Undefined) {
            $data['publishOnStatusPage'] = $this->publishOnStatusPage;
        }

        return $data;
    }
}
