<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UpdateIncidentCommentRequestDto */
final readonly class IncidentCommentUpdate implements RequestModel
{
    public function __construct(
        /**
         * The new text of the comment, at most 10000 characters. Required: an update always replaces the text.
         */
        public string $content,
        /**
         * Whether the comment is published on the status page. The specification gives false as its default, so leaving it out may unpublish the comment.
         */
        public bool|Undefined $publishOnStatusPage = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['content'] = $this->content;

        if (!$this->publishOnStatusPage instanceof Undefined) {
            $data['publishOnStatusPage'] = $this->publishOnStatusPage;
        }

        return $data;
    }
}
