<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: IncidentCommentDto.user */
final readonly class IncidentCommentUser implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $fullName = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            fullName: Cast::string($data['fullName'] ?? null) ?? '',
        );
    }
}
