<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: IncidentSummaryPaginationDto.data[] */
final readonly class IncidentSummary implements ResponseModel
{
    public function __construct(
        /**
         * The ID, a string of digits: incident IDs exceed the integers a JSON number holds exactly (verified live: "358532761126055015").
         */
        public string $id = '',
        /** The status of the incident; the specification documents no values (verified live: Resolved). */
        public string $status = '',
        /**
         * The kind of incident; the specification documents no values (verified live: Downtime and SlowResponse).
         */
        public string $type = '',
        /**
         * The cause code, which reason spells out. Verified live: the HTTP status code of an HTTP error (403 "403 Forbidden"), 333333 ("Connection Timeout"), 444444 ("No Response") and 0 for a slow response ("Response time"). The specification documents none of them.
         */
        public ?int $cause = null,
        public string $reason = '',
        public IncidentMonitor $monitor = new IncidentMonitor(),
        public int $commentsCount = 0,
        public ?DateTimeImmutable $startedAt = null,
        /**
         * When the incident ended; null according to the specification, presumably while it lasts (every incident read live was resolved).
         */
        public ?DateTimeImmutable $resolvedAt = null,
        /** Seconds from startedAt to resolvedAt (verified live). */
        public ?int $duration = null,
        /**
         * Whether the incident counts in the uptime reports (verified live: false for slow responses, true for downtimes).
         */
        public bool $includeInReports = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            type: Cast::string($data['type'] ?? null) ?? '',
            cause: Cast::int($data['cause'] ?? null),
            reason: Cast::string($data['reason'] ?? null) ?? '',
            monitor: Cast::model(IncidentMonitor::class, $data['monitor'] ?? null) ?? new IncidentMonitor(),
            commentsCount: Cast::int($data['commentsCount'] ?? null) ?? 0,
            startedAt: Cast::dateTime($data['startedAt'] ?? null),
            resolvedAt: Cast::dateTime($data['resolvedAt'] ?? null),
            duration: Cast::int($data['duration'] ?? null),
            includeInReports: Cast::bool($data['includeInReports'] ?? null) ?? false,
        );
    }
}
