<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: IncidentDetailDto */
final readonly class Incident implements ResponseModel
{
    public function __construct(
        /**
         * The ID, a string of digits: incident IDs exceed the integers a JSON number holds exactly (verified live: "358532761126055015").
         */
        public string $id = '',
        /** The status of the incident; the specification documents no values (verified live: Resolved). */
        public string $status = '',
        /**
         * The cause code, which reason spells out. Verified live: the HTTP status code of an HTTP error (403 "403 Forbidden"), 333333 ("Connection Timeout"), 444444 ("No Response") and 0 for a slow response ("Response time"). The specification documents none of them.
         */
        public int $cause = 0,
        public string $reason = '',
        /** Seconds from startedAt to resolvedAt (verified live). */
        public ?int $duration = null,
        public ?DateTimeImmutable $startedAt = null,
        /** When the incident ended; null according to the specification, presumably while it lasts. */
        public ?DateTimeImmutable $resolvedAt = null,
        public ?IncidentRootCause $rootCause = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            cause: Cast::int($data['cause'] ?? null) ?? 0,
            reason: Cast::string($data['reason'] ?? null) ?? '',
            duration: Cast::int($data['duration'] ?? null),
            startedAt: Cast::dateTime($data['startedAt'] ?? null),
            resolvedAt: Cast::dateTime($data['resolvedAt'] ?? null),
            rootCause: Cast::model(IncidentRootCause::class, $data['rootCause'] ?? null),
        );
    }
}
