<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * An integration to create: one model per integration type, each with the settings that type requires.
 *
 * Implemented by one model per "type": {@see SlackIntegrationCreate}, {@see
 * TelegramIntegrationCreate}, {@see MsTeamsIntegrationCreate}, {@see WebhookIntegrationCreate}, {@see
 * ZapierIntegrationCreate}, {@see PagerDutyIntegrationCreate}, {@see GoogleChatIntegrationCreate},
 * {@see DiscordIntegrationCreate}, {@see SplunkIntegrationCreate}, {@see PushbulletIntegrationCreate},
 * {@see PushoverIntegrationCreate}, {@see MattermostIntegrationCreate}.
 *
 * Schema: IntegrationsController_create.body
 */
interface IntegrationCreate extends RequestModel {}
