<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: IntegrationDto */
final readonly class Integration implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $friendlyName = null,
        /** Which status changes of its monitors the integration is alerted of. */
        public ?NotificationEvent $enableNotificationsFor = null,
        /**
         * The kind of integration, e.g. Slack, MSTeams or Webhook, in a spelling that may differ from the requests' (UptimeRobot's clients read PagerDuty for Pagerduty); with includeOrgMembers also the types of personal contacts (verified live: Email, ProSms, Voice and MobileApp). A string, as the specification documents no values.
         */
        public string $type = '',
        /**
         * Active, Paused, NotActivated or ToMigrate, the values UptimeRobot's guide for its MCP server (uptimerobot/ai, skills/list-integrations) and its Terraform provider name; only Active contacts deliver alerts. Verified live: Active, Paused and ToMigrate. A string, as the specification documents no values.
         */
        public string $status = '',
        public ?bool $sslExpirationReminder = null,
        /**
         * The destination: the URL of Slack, Microsoft Teams, Google Chat, Discord, Mattermost, Zapier, Splunk and webhook integrations, according to the official Terraform provider, which expects none for Telegram, Pushbullet, PagerDuty and Pushover; for a personal contact, its address (verified live).
         */
        public ?string $value = null,
        /**
         * Settings of the type, according to the official Terraform provider: the text of Slack, Discord and Mattermost, the settings of a webhook as a JSON string (postValue, sendJSON, sendQuery and sendPost), and autoResolve of PagerDuty as "1" or "true", "0" or "false". For a personal contact, its customValue, with an empty string for null (verified live).
         */
        public ?string $customValue = null,
        /**
         * The location of PagerDuty (us or eu), according to the official Terraform provider; empty for the personal contacts (verified live).
         */
        public ?string $customValue2 = null,
        /** For a mobile app contact, an ID of the device (verified live: a UUID); empty otherwise. */
        public ?string $customValue3 = null,
        /** For a mobile app contact, a label of the device (verified live); empty otherwise. */
        public ?string $customValue4 = null,
        /**
         * The headers a webhook integration sends, by name; empty if none (verified live for the personal contacts: null).
         *
         * @var array<array-key, string>
         */
        public array $customHeaders = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            friendlyName: Cast::string($data['friendlyName'] ?? null),
            enableNotificationsFor: Cast::stringEnum(NotificationEvent::class, $data['enableNotificationsFor'] ?? null),
            type: Cast::string($data['type'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            sslExpirationReminder: Cast::bool($data['sslExpirationReminder'] ?? null),
            value: Cast::string($data['value'] ?? null),
            customValue: Cast::string($data['customValue'] ?? null),
            customValue2: Cast::string($data['customValue2'] ?? null),
            customValue3: Cast::string($data['customValue3'] ?? null),
            customValue4: Cast::string($data['customValue4'] ?? null),
            customHeaders: Cast::mapOf($data['customHeaders'] ?? null, Cast::string(...)),
        );
    }
}
