<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * Changes to an integration: one model per integration type, which must be the type of the integration.
 *
 * Implemented by one model per "type": {@see SlackIntegrationUpdate}, {@see
 * TelegramIntegrationUpdate}, {@see MsTeamsIntegrationUpdate}, {@see WebhookIntegrationUpdate}, {@see
 * ZapierIntegrationUpdate}, {@see PagerDutyIntegrationUpdate}, {@see GoogleChatIntegrationUpdate},
 * {@see DiscordIntegrationUpdate}, {@see SplunkIntegrationUpdate}, {@see PushbulletIntegrationUpdate},
 * {@see PushoverIntegrationUpdate}, {@see MattermostIntegrationUpdate}.
 *
 * Schema: IntegrationsController_update.body
 */
interface IntegrationUpdate extends RequestModel {}
