<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\IpVersion;

/** Schema: IpVersionMonitorConfigDto */
final readonly class IpVersionMonitorConfig implements RequestModel
{
    public function __construct(
        /** IP version preference. Omit for default behavior (IPv4 priority, falls back to IPv6) */
        public IpVersion|Undefined $ipVersion = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->ipVersion instanceof Undefined) {
            $data['ipVersion'] = $this->ipVersion->value;
        }

        return $data;
    }
}
