<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorDto.lastIncident */
final readonly class LastIncident implements ResponseModel
{
    public function __construct(
        public string $id = '',
        public string $status = '',
        public int $cause = 0,
        public string $reason = '',
        public ?DateTimeImmutable $startedAt = null,
        public ?int $duration = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            status: Cast::string($data['status'] ?? null) ?? '',
            cause: Cast::int($data['cause'] ?? null) ?? 0,
            reason: Cast::string($data['reason'] ?? null) ?? '',
            startedAt: Cast::dateTime($data['startedAt'] ?? null),
            duration: Cast::int($data['duration'] ?? null),
        );
    }
}
