<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\MaintenanceWindowInterval;
use GoSuccess\UptimeRobot\Enum\MaintenanceWindowStatus;

/** Schema: MaintenanceWindowDto */
final readonly class MaintenanceWindow implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public int $userId = 0,
        public string $name = '',
        public ?MaintenanceWindowInterval $interval = null,
        public ?string $date = null,
        public string $time = '',
        public int $duration = 0,
        public bool $autoAddMonitors = false,
        /** @var list<int> */
        public array $monitorIds = [],
        /** @var list<int> */
        public array $days = [],
        public ?MaintenanceWindowStatus $status = null,
        public ?DateTimeImmutable $created = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            userId: Cast::int($data['userId'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            interval: Cast::stringEnum(MaintenanceWindowInterval::class, $data['interval'] ?? null),
            date: Cast::string($data['date'] ?? null),
            time: Cast::string($data['time'] ?? null) ?? '',
            duration: Cast::int($data['duration'] ?? null) ?? 0,
            autoAddMonitors: Cast::bool($data['autoAddMonitors'] ?? null) ?? false,
            monitorIds: Cast::listOf($data['monitorIds'] ?? null, Cast::int(...)),
            days: Cast::listOf($data['days'] ?? null, Cast::int(...)),
            status: Cast::stringEnum(MaintenanceWindowStatus::class, $data['status'] ?? null),
            created: Cast::dateTime($data['created'] ?? null),
        );
    }
}
