<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\MaintenanceWindowInterval;
use GoSuccess\UptimeRobot\Enum\MaintenanceWindowStatus;

/** Schema: MaintenanceWindowDto */
final readonly class MaintenanceWindow implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public int $userId = 0,
        public string $name = '',
        public ?MaintenanceWindowInterval $interval = null,
        /** The start date as YYYY-MM-DD, e.g. "2024-06-20", or null. The specification names no time zone. */
        public ?string $date = null,
        /** The start time as HH:mm:ss, e.g. "14:30:00". The specification names no time zone. */
        public string $time = '',
        /** Minutes the window lasts. */
        public int $duration = 0,
        /** Whether all monitors are added to the window automatically. */
        public bool $autoAddMonitors = false,
        /**
         * The monitors in the window. The official Terraform provider treats [0] as all monitors, together with autoAddMonitors (not verified live).
         *
         * @var list<int>
         */
        public array $monitorIds = [],
        /**
         * The days a weekly or monthly window recurs on. Weekly: 1 = Monday to 7 = Sunday according to the official Terraform provider, whose acceptance tests store 7; the specification only gives [2, 4, 5] for Tuesday, Thursday and Friday, which 0 = Sunday would fit as well. Monthly: 1 to 31, or -1 for the last day of the month. The API's validator accepts any number (verified live: 0, 8, 32 and -2); according to the provider, the API ignores invalid days.
         *
         * @var list<int>
         */
        public array $days = [],
        /** active: the window suppresses the alerts of its monitors during its periods; paused: it does not. */
        public ?MaintenanceWindowStatus $status = null,
        public ?DateTimeImmutable $created = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            userId: Cast::int($data['userId'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            interval: Cast::stringEnum(MaintenanceWindowInterval::class, $data['interval'] ?? null),
            date: Cast::string($data['date'] ?? null),
            time: Cast::string($data['time'] ?? null) ?? '',
            duration: Cast::int($data['duration'] ?? null) ?? 0,
            autoAddMonitors: Cast::bool($data['autoAddMonitors'] ?? null) ?? false,
            monitorIds: Cast::listOf($data['monitorIds'] ?? null, Cast::int(...)),
            days: Cast::listOf($data['days'] ?? null, Cast::int(...)),
            status: Cast::stringEnum(MaintenanceWindowStatus::class, $data['status'] ?? null),
            created: Cast::dateTime($data['created'] ?? null),
        );
    }
}
