<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\MaintenanceWindowInterval;
use GoSuccess\UptimeRobot\Enum\MaintenanceWindowStatus;

/** Schema: UpdateMaintenanceWindowDto */
final readonly class MaintenanceWindowUpdate implements RequestModel
{
    public function __construct(
        /** Name of the maintenance window */
        public string|Undefined $name = Undefined::Value,
        public MaintenanceWindowInterval|Undefined $interval = Undefined::Value,
        /**
         * The start date as YYYY-MM-DD (years 19xx and 20xx), e.g. "2024-06-20". The specification names no time zone.
         */
        public string|Undefined $date = Undefined::Value,
        /** The start time as HH:mm:ss, e.g. "14:30:00". The specification names no time zone. */
        public string|Undefined $time = Undefined::Value,
        /** Minutes the window lasts, at least 1. */
        public int|Undefined $duration = Undefined::Value,
        /**
         * The days a weekly or monthly window recurs on. Weekly: 1 = Monday to 7 = Sunday according to the official Terraform provider, whose acceptance tests store 7; the specification only gives [2, 4, 5] for Tuesday, Thursday and Friday, which 0 = Sunday would fit as well. Monthly: 1 to 31, or -1 for the last day of the month. The API's validator accepts any number (verified live: 0, 8, 32 and -2); according to the provider, the API ignores invalid days.
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $days = Undefined::Value,
        /**
         * The monitors in the window, presumably replacing the current ones: the official Terraform provider sends the whole list and expects the window to report exactly it (not verified live).
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $monitorIds = Undefined::Value,
        /**
         * Pause or resume the maintenance window. `paused` stops it from suppressing alerts; `active` re-enables it. Omit to leave the current status unchanged.
         */
        public MaintenanceWindowStatus|Undefined $status = Undefined::Value,
        /**
         * Whether all monitors are added to the window automatically. Missing from the specification's update request; the official Terraform provider changes it this way (not verified live).
         */
        public bool|Undefined $autoAddMonitors = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->name instanceof Undefined) {
            $data['name'] = $this->name;
        }

        if (!$this->interval instanceof Undefined) {
            $data['interval'] = $this->interval->value;
        }

        if (!$this->date instanceof Undefined) {
            $data['date'] = $this->date;
        }

        if (!$this->time instanceof Undefined) {
            $data['time'] = $this->time;
        }

        if (!$this->duration instanceof Undefined) {
            $data['duration'] = $this->duration;
        }

        if (!$this->days instanceof Undefined) {
            $data['days'] = $this->days;
        }

        if (!$this->monitorIds instanceof Undefined) {
            $data['monitorIds'] = $this->monitorIds;
        }

        if (!$this->status instanceof Undefined) {
            $data['status'] = $this->status->value;
        }

        if (!$this->autoAddMonitors instanceof Undefined) {
            $data['autoAddMonitors'] = $this->autoAddMonitors;
        }

        return $data;
    }
}
