<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: CreateMattermostIntegrationDto ("data": MattermostBaseIntegrationDto) */
final readonly class MattermostIntegrationCreate implements IntegrationCreate
{
    /** The "type" of this variant of {@see IntegrationCreate}. */
    public const string TYPE = 'Mattermost';

    public function __construct(
        /** The Mattermost Webhook URL */
        public string $webhookUrl,
        /**
         * Text added to every notification. The specification requires it on create, although its description calls it optional; an empty string sends no text. The official Terraform provider clears it with an empty string, and its acceptance test reads an empty Mattermost text back (not verified live).
         */
        public string $customValue,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        public string|Undefined $friendlyName = Undefined::Value,
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['webhookURL'] = $this->webhookUrl;
        $data['customValue'] = $this->customValue;

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
