<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\HttpAuthType;
use GoSuccess\UptimeRobot\Enum\HttpMethod;
use GoSuccess\UptimeRobot\Enum\KeywordCaseType;
use GoSuccess\UptimeRobot\Enum\KeywordType;
use GoSuccess\UptimeRobot\Enum\MonitorType;
use GoSuccess\UptimeRobot\Enum\PostValueType;
use stdClass;

/** Schema: UpdateMonitorDto */
final readonly class MonitorUpdate implements RequestModel
{
    public function __construct(
        /** Friendly name of the monitor */
        public string|Undefined $friendlyName = Undefined::Value,
        /** URL of the monitor. For DNS monitors: DNS server IP or hostname. Not required for Heartbeat monitor */
        public string|Undefined $url = Undefined::Value,
        public MonitorType|Undefined $type = Undefined::Value,
        /** Required for Port and UDP monitors */
        public int|Undefined $port = Undefined::Value,
        /** Required for Keyword monitor */
        public KeywordType|Undefined $keywordType = Undefined::Value,
        /** Required for Keyword monitor */
        public KeywordCaseType|Undefined $keywordCaseType = Undefined::Value,
        /** The keyword to look for (keyword monitors); null is rejected. */
        public string|Undefined $keywordValue = Undefined::Value,
        /** Interval of check in seconds. Heartbeat monitors support at most 2678400 seconds (31 days). */
        public int|Undefined $interval = Undefined::Value,
        /** Timeout of check in seconds. Only for Http, Keyword and Port monitors */
        public int|Undefined $timeout = Undefined::Value,
        /** Grace period of check in seconds. Only for Heartbeat monitor */
        public int|Undefined $gracePeriod = Undefined::Value,
        /** Username for HTTP Basic authentication */
        public string|Undefined $httpUsername = Undefined::Value,
        /** Password for HTTP Basic authentication */
        public string|Undefined $httpPassword = Undefined::Value,
        /**
         * HTTP method to use for the request. For HTTP and Keyword monitors it defaults to HEAD if omitted; API monitors default to GET and do not allow HEAD
         */
        public HttpMethod|Undefined|null $httpMethodType = Undefined::Value,
        /** Authentication method to use for the request. Only applicable for HTTP and Keyword monitors */
        public HttpAuthType|Undefined $authType = Undefined::Value,
        /**
         * The body the check sends: an array, sent as a JSON object, or a JSON string; the API stores either as an object (verified live). Not applicable for the HTTP method HEAD.
         */
        public mixed $postValueData = Undefined::Value,
        /**
         * Type of data payload to be sent in the request. Affects what data is accepted by "postValueData" field
         */
        public PostValueType|Undefined $postValueType = Undefined::Value,
        /**
         * Alert contacts to be assigned to the monitor. Threshold and recurrence are only available in the paid plans, they are always 0 in the Free Plan
         *
         * @var list<AssignedAlertContact>|Undefined
         */
        public array|Undefined $assignedAlertContacts = Undefined::Value,
        /**
         * The headers the check sends. Replaces all current headers; an empty array removes them (verified live). The serialized JSON must not exceed 3000 characters.
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customHttpHeaders = Undefined::Value,
        /**
         * The HTTP status codes or ranges such as "2xx" that count as up. Replaces the current ones; an empty list resets them to ["2xx", "3xx"] (verified live).
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $successHttpResponseCodes = Undefined::Value,
        /** Whether to check for SSL and domain expiration errors */
        public bool|Undefined $checkSslErrors = Undefined::Value,
        /**
         * Tags to be assigned to the monitor
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $tagNames = Undefined::Value,
        /**
         * Maintenance windows to be assigned to the monitor
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $maintenanceWindowsIds = Undefined::Value,
        /** Whether to send a notification when the domain is about to expire */
        public bool|Undefined $domainExpirationReminder = Undefined::Value,
        /** Whether to send a notification when the SSL certificate is about to expire */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** Whether to follow redirections */
        public bool|Undefined $followRedirections = Undefined::Value,
        /**
         * Response time threshold in milliseconds, stored in regionalData THRESHOLD; the property itself keeps reading 0 (verified live).
         */
        public int|Undefined $responseTimeThreshold = Undefined::Value,
        /** Regional data for monitoring */
        public RegionalData|Undefined $regionData = Undefined::Value,
        /** Monitor group ID to assign the monitor to. Use 0 for the default group. */
        public int|Undefined $groupId = Undefined::Value,
        /**
         * Custom key-value metadata. Replaces all current fields (verified live). Max 20 keys. Keys: alphanumeric + underscore + hyphen, max 64 chars. Values: max 255 chars. Paid plans only.
         *
         * @var array<array-key, string>|Undefined
         */
        public array|Undefined $customFields = Undefined::Value,
        /**
         * Monitor configuration patch. Top-level shallow merge with existing config: omit keys to leave unchanged, set a key to null to remove it, or send `config: null` to clear all config.
         */
        public MonitorConfigUpdate|Undefined|null $config = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->url instanceof Undefined) {
            $data['url'] = $this->url;
        }

        if (!$this->type instanceof Undefined) {
            $data['type'] = $this->type->value;
        }

        if (!$this->port instanceof Undefined) {
            $data['port'] = $this->port;
        }

        if (!$this->keywordType instanceof Undefined) {
            $data['keywordType'] = $this->keywordType->value;
        }

        if (!$this->keywordCaseType instanceof Undefined) {
            $data['keywordCaseType'] = $this->keywordCaseType->value;
        }

        if (!$this->keywordValue instanceof Undefined) {
            $data['keywordValue'] = $this->keywordValue;
        }

        if (!$this->interval instanceof Undefined) {
            $data['interval'] = $this->interval;
        }

        if (!$this->timeout instanceof Undefined) {
            $data['timeout'] = $this->timeout;
        }

        if (!$this->gracePeriod instanceof Undefined) {
            $data['gracePeriod'] = $this->gracePeriod;
        }

        if (!$this->httpUsername instanceof Undefined) {
            $data['httpUsername'] = $this->httpUsername;
        }

        if (!$this->httpPassword instanceof Undefined) {
            $data['httpPassword'] = $this->httpPassword;
        }

        if (!$this->httpMethodType instanceof Undefined) {
            $data['httpMethodType'] = $this->httpMethodType?->value;
        }

        if (!$this->authType instanceof Undefined) {
            $data['authType'] = $this->authType->value;
        }

        if (!$this->postValueData instanceof Undefined) {
            $data['postValueData'] = $this->postValueData;
        }

        if (!$this->postValueType instanceof Undefined) {
            $data['postValueType'] = $this->postValueType->value;
        }

        if (!$this->assignedAlertContacts instanceof Undefined) {
            $data['assignedAlertContacts'] = array_map(static fn(AssignedAlertContact $item): array|stdClass => Json::map($item->toArray()), $this->assignedAlertContacts);
        }

        if (!$this->customHttpHeaders instanceof Undefined) {
            $data['customHttpHeaders'] = Json::map($this->customHttpHeaders);
        }

        if (!$this->successHttpResponseCodes instanceof Undefined) {
            $data['successHttpResponseCodes'] = $this->successHttpResponseCodes;
        }

        if (!$this->checkSslErrors instanceof Undefined) {
            $data['checkSSLErrors'] = $this->checkSslErrors;
        }

        if (!$this->tagNames instanceof Undefined) {
            $data['tagNames'] = $this->tagNames;
        }

        if (!$this->maintenanceWindowsIds instanceof Undefined) {
            $data['maintenanceWindowsIds'] = $this->maintenanceWindowsIds;
        }

        if (!$this->domainExpirationReminder instanceof Undefined) {
            $data['domainExpirationReminder'] = $this->domainExpirationReminder;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->followRedirections instanceof Undefined) {
            $data['followRedirections'] = $this->followRedirections;
        }

        if (!$this->responseTimeThreshold instanceof Undefined) {
            $data['responseTimeThreshold'] = $this->responseTimeThreshold;
        }

        if (!$this->regionData instanceof Undefined) {
            $data['regionData'] = Json::map($this->regionData->toArray());
        }

        if (!$this->groupId instanceof Undefined) {
            $data['groupId'] = $this->groupId;
        }

        if (!$this->customFields instanceof Undefined) {
            $data['customFields'] = Json::map($this->customFields);
        }

        if (!$this->config instanceof Undefined) {
            $data['config'] = $this->config === null ? null : Json::map($this->config->toArray());
        }

        return $data;
    }
}
