<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * A monitor to create: one model per monitor type, each with the fields that type requires.
 *
 * Implemented by one model per "type": {@see HttpMonitorCreate}, {@see KeywordMonitorCreate}, {@see
 * PingMonitorCreate}, {@see PortMonitorCreate}, {@see HeartbeatMonitorCreate}, {@see
 * DnsMonitorCreate}, {@see ApiMonitorCreate}, {@see UdpMonitorCreate}, {@see
 * VisualComparisonMonitorCreate}.
 *
 * Schema: MonitorsController_create.body
 */
interface MonitorCreate extends RequestModel {}
