<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: CreateMonitorGroupDto */
final readonly class MonitorGroupCreate implements RequestModel
{
    public function __construct(
        /** Name of the monitor group */
        public string $name,
        /**
         * The monitors to put into the group. A monitor is in one group at most (its groupId), so they leave the group they are in.
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $monitorIds = Undefined::Value,
        /**
         * Groups whose monitors are moved into the new group; 0 stands for the monitors in no group, which the specification calls the default group.
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $groupIds = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['name'] = $this->name;

        if (!$this->monitorIds instanceof Undefined) {
            $data['monitorIds'] = $this->monitorIds;
        }

        if (!$this->groupIds instanceof Undefined) {
            $data['groupIds'] = $this->groupIds;
        }

        return $data;
    }
}
