<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: MonitorDto.tags[] */
final readonly class MonitorTag implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $name = '',
        public string $color = '',
        /** @var list<TaggedMonitor> */
        public array $monitors = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            color: Cast::string($data['color'] ?? null) ?? '',
            monitors: Cast::modelList(TaggedMonitor::class, $data['monitors'] ?? null),
        );
    }
}
