<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorUptimeStatsDto */
final readonly class MonitorUptimeStats implements ResponseModel
{
    public function __construct(
        /**
         * The uptime as a percentage from 0 to 100, e.g. 99.95, unlike the fraction of MonitorResource::uptimeStats() (verified live).
         */
        public float $uptime = 0.0,
        /** Total downtime duration in seconds */
        public int $totalDowntimeSeconds = 0,
        /** Number of incidents in the period */
        public int $incidentCount = 0,
        /** Mean Time Between Failures in seconds, or null if no incidents occurred */
        public ?int $mtbf = null,
        /** Start of the date range (ISO 8601) */
        public ?DateTimeImmutable $from = null,
        /** End of the date range (ISO 8601) */
        public ?DateTimeImmutable $to = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            uptime: Cast::float($data['uptime'] ?? null) ?? 0.0,
            totalDowntimeSeconds: Cast::int($data['total_downtime_seconds'] ?? null) ?? 0,
            incidentCount: Cast::int($data['incident_count'] ?? null) ?? 0,
            mtbf: Cast::int($data['mtbf'] ?? null),
            from: Cast::dateTime($data['from'] ?? null),
            to: Cast::dateTime($data['to'] ?? null),
        );
    }
}
