<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UpdateMonitorGroupDto */
final readonly class MonitorGroupUpdate implements RequestModel
{
    public function __construct(
        /** Name of the monitor group */
        public string|Undefined $name = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->name instanceof Undefined) {
            $data['name'] = $this->name;
        }

        return $data;
    }
}
