<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\HttpAuthType;
use GoSuccess\UptimeRobot\Enum\HttpMethod;
use GoSuccess\UptimeRobot\Enum\KeywordCaseType;
use GoSuccess\UptimeRobot\Enum\KeywordType;
use GoSuccess\UptimeRobot\Enum\MonitorStatus;
use GoSuccess\UptimeRobot\Enum\MonitorType;
use GoSuccess\UptimeRobot\Enum\PostValueType;

/** Schema: MonitorDto */
final readonly class Monitor implements ResponseModel
{
    public function __construct(
        public ?MonitorType $type = null,
        /** Seconds between two checks. */
        public int $interval = 0,
        public ?string $sslBrand = null,
        public ?DateTimeImmutable $sslExpiryDateTime = null,
        public ?DateTimeImmutable $domainExpireDate = null,
        public bool $checkSslErrors = false,
        public ?bool $sslExpirationReminder = null,
        public ?bool $domainExpirationReminder = null,
        public bool $followRedirections = false,
        /**
         * The authentication of the check. Monitors created without one report HTTP_BASIC with empty credentials, whatever their type (verified live).
         */
        public ?HttpAuthType $authType = null,
        /** The user name of the authentication; empty if none is set (verified live). */
        public string $httpUsername = '',
        /**
         * The password of the authentication, in plain text (verified live); empty if none is set. Treat monitor data as secret.
         */
        public string $httpPassword = '',
        /**
         * The headers the check sends; numbers are read as strings.
         *
         * @var array<array-key, string>
         */
        public array $customHttpHeaders = [],
        /**
         * The HTTP method of the check; null for HTTP and keyword monitors created without one, which use HEAD then (the documented default).
         */
        public ?HttpMethod $httpMethodType = null,
        /** @var list<string> */
        public array $successHttpResponseCodes = [],
        public ?int $timeout = null,
        /**
         * The body the check sends, as the decoded JSON object, or null.
         *
         * @var array<array-key, mixed>|null
         */
        public ?array $postValueData = null,
        public ?PostValueType $postValueType = null,
        public ?int $port = null,
        public ?int $gracePeriod = null,
        /** The keyword to look for; empty on monitors of other types (verified live). */
        public ?string $keywordValue = null,
        /**
         * Whether the keyword match is case sensitive; CaseSensitive on monitors of other types (verified live).
         */
        public ?KeywordCaseType $keywordCaseType = null,
        /**
         * Whether to alert when the keyword exists or when it does not; null on monitors of other types (verified live).
         */
        public ?KeywordType $keywordType = null,
        /** Always 0; the thresholds are in regionalData (verified live). */
        public int $responseTimeThreshold = 0,
        public ?MonitorConfig $config = null,
        /** The regions the checks run from. */
        public RegionalData $regionalData = new RegionalData(),
        /** @var list<MaintenanceWindow> */
        public array $maintenanceWindows = [],
        /** @var list<StatusPage> */
        public array $psps = [],
        public int $id = 0,
        public string $friendlyName = '',
        /**
         * The status of the monitor: UP, DOWN, LOOKS_DOWN, PAUSED, or STARTED, which a new or restarted monitor reports until its first check (verified live).
         */
        public ?MonitorStatus $status = null,
        /**
         * The URL, host name or IP address that is checked; for heartbeat monitors, the token of the URL the heartbeats are sent to (verified live).
         */
        public string $url = '',
        /** Seconds since the status last changed; 0 for a new monitor. */
        public int $currentStateDuration = 0,
        /**
         * The ID of the latest incident, as a string: incident IDs exceed the integers JSON numbers hold exactly (verified live: "352577094135060139").
         */
        public ?string $lastIncidentId = null,
        public int $userId = 0,
        /** @var list<MonitorTag> */
        public array $tags = [],
        /** @var list<AssignedAlertContact> */
        public array $assignedAlertContacts = [],
        public ?LastIncident $lastIncident = null,
        public UptimeHistogram $lastDayUptimes = new UptimeHistogram(),
        public ?DateTimeImmutable $createDateTime = null,
        public ?string $apiKey = null,
        /** The monitor group; 0 if the monitor is in none (verified live). */
        public ?int $groupId = null,
        /** @var array<array-key, string> */
        public array $customFields = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            type: Cast::stringEnum(MonitorType::class, $data['type'] ?? null),
            interval: Cast::int($data['interval'] ?? null) ?? 0,
            sslBrand: Cast::string($data['sslBrand'] ?? null),
            sslExpiryDateTime: Cast::dateTime($data['sslExpiryDateTime'] ?? null),
            domainExpireDate: Cast::dateTime($data['domainExpireDate'] ?? null),
            checkSslErrors: Cast::bool($data['checkSSLErrors'] ?? null) ?? false,
            sslExpirationReminder: Cast::bool($data['sslExpirationReminder'] ?? null),
            domainExpirationReminder: Cast::bool($data['domainExpirationReminder'] ?? null),
            followRedirections: Cast::bool($data['followRedirections'] ?? null) ?? false,
            authType: Cast::stringEnum(HttpAuthType::class, $data['authType'] ?? null),
            httpUsername: Cast::string($data['httpUsername'] ?? null) ?? '',
            httpPassword: Cast::string($data['httpPassword'] ?? null) ?? '',
            customHttpHeaders: Cast::mapOf($data['customHttpHeaders'] ?? null, Cast::string(...)),
            httpMethodType: Cast::stringEnum(HttpMethod::class, $data['httpMethodType'] ?? null),
            successHttpResponseCodes: Cast::listOf($data['successHttpResponseCodes'] ?? null, Cast::string(...)),
            timeout: Cast::int($data['timeout'] ?? null),
            postValueData: Cast::object($data['postValueData'] ?? null),
            postValueType: Cast::stringEnum(PostValueType::class, $data['postValueType'] ?? null),
            port: Cast::int($data['port'] ?? null),
            gracePeriod: Cast::int($data['gracePeriod'] ?? null),
            keywordValue: Cast::string($data['keywordValue'] ?? null),
            keywordCaseType: Cast::intEnum(KeywordCaseType::class, $data['keywordCaseType'] ?? null),
            keywordType: Cast::stringEnum(KeywordType::class, $data['keywordType'] ?? null),
            responseTimeThreshold: Cast::int($data['responseTimeThreshold'] ?? null) ?? 0,
            config: Cast::model(MonitorConfig::class, $data['config'] ?? null),
            regionalData: Cast::model(RegionalData::class, $data['regionalData'] ?? null) ?? new RegionalData(),
            maintenanceWindows: Cast::modelList(MaintenanceWindow::class, $data['maintenanceWindows'] ?? null),
            psps: Cast::modelList(StatusPage::class, $data['psps'] ?? null),
            id: Cast::int($data['id'] ?? null) ?? 0,
            friendlyName: Cast::string($data['friendlyName'] ?? null) ?? '',
            status: Cast::stringEnum(MonitorStatus::class, $data['status'] ?? null),
            url: Cast::string($data['url'] ?? null) ?? '',
            currentStateDuration: Cast::int($data['currentStateDuration'] ?? null) ?? 0,
            lastIncidentId: Cast::string($data['lastIncidentId'] ?? null),
            userId: Cast::int($data['userId'] ?? null) ?? 0,
            tags: Cast::modelList(MonitorTag::class, $data['tags'] ?? null),
            assignedAlertContacts: Cast::modelList(AssignedAlertContact::class, $data['assignedAlertContacts'] ?? null),
            lastIncident: Cast::model(LastIncident::class, $data['lastIncident'] ?? null),
            lastDayUptimes: Cast::model(UptimeHistogram::class, $data['lastDayUptimes'] ?? null) ?? new UptimeHistogram(),
            createDateTime: Cast::dateTime($data['createDateTime'] ?? null),
            apiKey: Cast::string($data['apiKey'] ?? null),
            groupId: Cast::int($data['groupId'] ?? null),
            customFields: Cast::mapOf($data['customFields'] ?? null, Cast::string(...)),
        );
    }
}
