<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\IpVersion;

/**
 * Changes to the settings of a monitor type, merged into the current ones key by key: a key left out is kept, a key set to null is removed (verified live).
 *
 * Schema: UpdateMonitorConfigDto
 */
final readonly class MonitorConfigUpdate implements RequestModel
{
    public function __construct(
        /**
         * Days before the SSL certificate expires on which to send a reminder (0-365, at most 10 items). HTTP, keyword and API monitors.
         *
         * @var list<int>|Undefined|null
         */
        public array|Undefined|null $sslExpirationPeriodDays = Undefined::Value,
        /** IP version preference; null restores the default behavior (IPv4 priority, falls back to IPv6). */
        public IpVersion|Undefined|null $ipVersion = Undefined::Value,
        /** Number of retries on application errors (HTTP 4xx/5xx), 0-3. HTTP, keyword and API monitors. */
        public int|Undefined|null $applicationErrorRetries = Undefined::Value,
        /** The expected DNS records of a DNS monitor. */
        public DnsRecords|Undefined|null $dnsRecords = Undefined::Value,
        /** The assertions of an API monitor; replaces the current ones as a whole (verified live). */
        public ApiAssertions|Undefined|null $apiAssertions = Undefined::Value,
        /** The settings of a UDP monitor. */
        public UdpSettings|Undefined|null $udp = Undefined::Value,
        /** The settings of a visual comparison monitor. */
        public VisualComparisonSettings|Undefined|null $visualComparison = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->sslExpirationPeriodDays instanceof Undefined) {
            $data['sslExpirationPeriodDays'] = $this->sslExpirationPeriodDays;
        }

        if (!$this->ipVersion instanceof Undefined) {
            $data['ipVersion'] = $this->ipVersion?->value;
        }

        if (!$this->applicationErrorRetries instanceof Undefined) {
            $data['applicationErrorRetries'] = $this->applicationErrorRetries;
        }

        if (!$this->dnsRecords instanceof Undefined) {
            $data['dnsRecords'] = $this->dnsRecords === null ? null : Json::map($this->dnsRecords->toArray());
        }

        if (!$this->apiAssertions instanceof Undefined) {
            $data['apiAssertions'] = $this->apiAssertions === null ? null : Json::map($this->apiAssertions->toArray());
        }

        if (!$this->udp instanceof Undefined) {
            $data['udp'] = $this->udp === null ? null : Json::map($this->udp->toArray());
        }

        if (!$this->visualComparison instanceof Undefined) {
            $data['visualComparison'] = $this->visualComparison === null ? null : Json::map($this->visualComparison->toArray());
        }

        return $data;
    }
}
