<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\IpVersion;

/** Schema: MonitorDto.config */
final readonly class MonitorConfig implements ResponseModel
{
    public function __construct(
        public ?DnsRecords $dnsRecords = null,
        public ?ApiAssertions $apiAssertions = null,
        /** @var list<int> */
        public array $sslExpirationPeriodDays = [],
        public ?UdpSettings $udp = null,
        public ?IpVersion $ipVersion = null,
        public ?int $applicationErrorRetries = null,
        public ?MonitorVisualComparison $visualComparison = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            dnsRecords: Cast::model(DnsRecords::class, $data['dnsRecords'] ?? null),
            apiAssertions: Cast::model(ApiAssertions::class, $data['apiAssertions'] ?? null),
            sslExpirationPeriodDays: Cast::listOf($data['sslExpirationPeriodDays'] ?? null, Cast::int(...)),
            udp: Cast::model(UdpSettings::class, $data['udp'] ?? null),
            ipVersion: Cast::stringEnum(IpVersion::class, $data['ipVersion'] ?? null),
            applicationErrorRetries: Cast::int($data['applicationErrorRetries'] ?? null),
            visualComparison: Cast::model(MonitorVisualComparison::class, $data['visualComparison'] ?? null),
        );
    }
}
