<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\VisualComparisonViewport;

/** Schema: MonitorDto.config.visualComparison */
final readonly class MonitorVisualComparison implements ResponseModel
{
    public function __construct(
        public int $sensitivityThreshold = 0,
        public ?VisualComparisonViewport $viewport = null,
        public ?VisualComparisonArea $areaCoordinates = null,
        public bool $refreshBaseline = false,
        public string $userBaselinePath = '',
        public string $lastCheckBaselinePath = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            sensitivityThreshold: Cast::int($data['sensitivityThreshold'] ?? null) ?? 0,
            viewport: Cast::stringEnum(VisualComparisonViewport::class, $data['viewport'] ?? null),
            areaCoordinates: Cast::model(VisualComparisonArea::class, $data['areaCoordinates'] ?? null),
            refreshBaseline: Cast::bool($data['refreshBaseline'] ?? null) ?? false,
            userBaselinePath: Cast::string($data['userBaselinePath'] ?? null) ?? '',
            lastCheckBaselinePath: Cast::string($data['lastCheckBaselinePath'] ?? null) ?? '',
        );
    }
}
