<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorGroupDto */
final readonly class MonitorGroup implements ResponseModel
{
    public function __construct(
        /**
         * The ID, which the monitors in the group report as groupId; the monitors in no group report 0, for which there is no group to read (verified live).
         */
        public int $id = 0,
        public string $name = '',
        public ?DateTimeImmutable $createdAt = null,
        public ?DateTimeImmutable $updatedAt = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
            createdAt: Cast::dateTime($data['createdAt'] ?? null),
            updatedAt: Cast::dateTime($data['updatedAt'] ?? null),
        );
    }
}
