<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: CreateMsTeamsIntegrationDto ("data": MsTeamsBaseIntegrationDto) */
final readonly class MsTeamsIntegrationCreate implements IntegrationCreate
{
    /** The "type" of this variant of {@see IntegrationCreate}. */
    public const string TYPE = 'MSTeams';

    public function __construct(
        /** The Microsoft Teams Webhook URL */
        public string $webhookUrl,
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['webhookURL'] = $this->webhookUrl;

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
