<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\AlertDeliveryStatus;
use GoSuccess\UptimeRobot\Enum\Region;

/** Schema: ActivityLogResponseDto.data[]<NOTIFICATION> */
final readonly class NotificationActivity implements ActivityLogEntry
{
    /** The "type" of this variant of {@see ActivityLogEntry}. */
    public const string TYPE = 'NOTIFICATION';

    public function __construct(
        public ?DateTimeImmutable $date = null,
        public ?Region $region = null,
        public string $sentToFullName = '',
        /**
         * The address the alert went to: an e-mail address, a phone number or, for the mobile app, the device token (verified live: a device token).
         */
        public string $sentToValue = '',
        /**
         * The channel of the alert contact, e.g. MobileApp (verified live); the specification documents no values.
         */
        public string $notificationType = '',
        public ?AlertDeliveryStatus $notificationStatus = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            date: Cast::dateTime($data['date'] ?? null),
            region: Cast::stringEnum(Region::class, $data['region'] ?? null),
            sentToFullName: Cast::string($data['sentToFullName'] ?? null) ?? '',
            sentToValue: Cast::string($data['sentToValue'] ?? null) ?? '',
            notificationType: Cast::string($data['notificationType'] ?? null) ?? '',
            notificationStatus: Cast::stringEnum(AlertDeliveryStatus::class, $data['notificationStatus'] ?? null),
        );
    }
}
