<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;
use GoSuccess\UptimeRobot\Enum\PagerDutyLocation;

/** Schema: CreatePagerdutyIntegrationDto ("data": CreatePagerdutyBaseIntegrationDto) */
final readonly class PagerDutyIntegrationCreate implements IntegrationCreate
{
    /** The "type" of this variant of {@see IntegrationCreate}. */
    public const string TYPE = 'Pagerduty';

    public function __construct(
        /** The PagerDuty Integration Key */
        public string $integrationKey,
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** The PagerDuty Service region */
        public PagerDutyLocation|Undefined $location = Undefined::Value,
        /** Auto-resolve incidents after up event */
        public bool|Undefined $autoResolve = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['integrationKey'] = $this->integrationKey;

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->location instanceof Undefined) {
            $data['location'] = $this->location->value;
        }

        if (!$this->autoResolve instanceof Undefined) {
            $data['autoResolve'] = $this->autoResolve;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
