<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;
use GoSuccess\UptimeRobot\Enum\PushoverPriority;

/** Schema: CreatePushoverIntegrationDto ("data": CreatePushoverBaseIntegrationDto) */
final readonly class PushoverIntegrationCreate implements IntegrationCreate
{
    /** The "type" of this variant of {@see IntegrationCreate}. */
    public const string TYPE = 'Pushover';

    public function __construct(
        /** The Pushover User Key */
        public string $userKey,
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** The Pushover priority of the notifications. */
        public PushoverPriority|Undefined $priority = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['userKey'] = $this->userKey;

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->priority instanceof Undefined) {
            $data['priority'] = $this->priority->value;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
