<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorResponseTimeStatsByRegionDto */
final readonly class RegionalResponseTimeStats implements ResponseModel
{
    public function __construct(
        /** Response time statistics for North America region */
        public ?ResponseTimeStats $na = null,
        /** Response time statistics for Europe region */
        public ?ResponseTimeStats $eu = null,
        /** Response time statistics for Asia region */
        public ?ResponseTimeStats $as = null,
        /** Response time statistics for Oceania region */
        public ?ResponseTimeStats $oc = null,
        /** Response time statistics averaged across all regions, combined with legacy data when available */
        public ?ResponseTimeStats $all = null,
        /** Start of the date range (ISO 8601) */
        public ?DateTimeImmutable $from = null,
        /** End of the date range (ISO 8601) */
        public ?DateTimeImmutable $to = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            na: Cast::model(ResponseTimeStats::class, $data['na'] ?? null),
            eu: Cast::model(ResponseTimeStats::class, $data['eu'] ?? null),
            as: Cast::model(ResponseTimeStats::class, $data['as'] ?? null),
            oc: Cast::model(ResponseTimeStats::class, $data['oc'] ?? null),
            all: Cast::model(ResponseTimeStats::class, $data['all'] ?? null),
            from: Cast::dateTime($data['from'] ?? null),
            to: Cast::dateTime($data['to'] ?? null),
        );
    }
}
