<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\Region;
use GoSuccess\UptimeRobot\Enum\RegionInfrastructure;

/** Schema: RegionalDataDto */
final readonly class RegionalData implements RequestModel, ResponseModel
{
    /**
     * The regions the checks run from; at least one.
     *
     * @var list<Region>
     */
    public array $region;

    /**
     * Response time thresholds in milliseconds by region code (na, eu, as, oc).
     *
     * @var array<array-key, int>
     */
    public array $threshold;

    /** Whether the regions were chosen rather than assigned by default. */
    public bool $manualSelected;

    /** The checking infrastructure, set by the API (verified live: New). */
    public ?RegionInfrastructure $infrastructure;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param list<Region>|Undefined $region
     * @param array<array-key, int>|Undefined $threshold
     */
    public function __construct(
        array|Undefined $region = Undefined::Value,
        array|Undefined $threshold = Undefined::Value,
        bool|Undefined $manualSelected = Undefined::Value,
        RegionInfrastructure|Undefined $infrastructure = Undefined::Value,
    ) {
        $this->region = $region instanceof Undefined ? [] : $region;
        $this->threshold = $threshold instanceof Undefined ? [] : $threshold;
        $this->manualSelected = $manualSelected instanceof Undefined ? false : $manualSelected;
        $this->infrastructure = $infrastructure instanceof Undefined ? null : $infrastructure;
        $this->provided = array_filter([
            'REGION' => !$region instanceof Undefined,
            'THRESHOLD' => !$threshold instanceof Undefined,
            'MANUAL_SELECTED' => !$manualSelected instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            region: Cast::listOf($data['REGION'] ?? null, static fn(mixed $value): ?Region => Cast::stringEnum(Region::class, $value)) ?: Undefined::Value,
            threshold: Cast::mapOf($data['THRESHOLD'] ?? null, Cast::int(...)) ?: Undefined::Value,
            manualSelected: Cast::bool($data['MANUAL_SELECTED'] ?? null) ?? Undefined::Value,
            infrastructure: Cast::stringEnum(RegionInfrastructure::class, $data['INFRASTRUCTURE'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['REGION'])) {
            $data['REGION'] = array_map(static fn(Region $item): string => $item->value, $this->region);
        }

        if (isset($this->provided['THRESHOLD'])) {
            $data['THRESHOLD'] = Json::map($this->threshold);
        }

        if (isset($this->provided['MANUAL_SELECTED'])) {
            $data['MANUAL_SELECTED'] = $this->manualSelected;
        }

        return $data;
    }
}
