<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: ActivityLogResponseDto.data[]<STATUS_UPDATE>.remoteNode */
final readonly class RemoteNode implements ResponseModel
{
    public function __construct(
        /** The ID of the node; 0 on every node read live. */
        public int $id = 0,
        public bool $status = false,
        public string $ip = '',
        /**
         * The IPv6 address of the node; some nodes report a private IPv4 address here, e.g. 10.0.4.16 (verified live).
         */
        public ?string $ipv6 = null,
        public string $city = '',
        public string $country = '',
        public ?string $privateIp = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            status: Cast::bool($data['status'] ?? null) ?? false,
            ip: Cast::string($data['IP'] ?? null) ?? '',
            ipv6: Cast::string($data['IPv6'] ?? null),
            city: Cast::string($data['city'] ?? null) ?? '',
            country: Cast::string($data['country'] ?? null) ?? '',
            privateIp: Cast::string($data['privateIP'] ?? null),
        );
    }
}
