<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorResponseTimeStatsDto */
final readonly class ResponseTimeStats implements ResponseModel
{
    public function __construct(
        /** Summary statistics for the response time data */
        public ResponseTimeSummary $summary = new ResponseTimeSummary(),
        /** The number of time series points the statistics are based on, not of checks (verified live). */
        public int $dataPoints = 0,
        /** Start of the date range (ISO 8601) */
        public ?DateTimeImmutable $from = null,
        /** End of the date range (ISO 8601) */
        public ?DateTimeImmutable $to = null,
        /**
         * Optional time series data points
         *
         * @var list<ResponseTimeDataPoint>
         */
        public array $timeSeries = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            summary: Cast::model(ResponseTimeSummary::class, $data['summary'] ?? null) ?? new ResponseTimeSummary(),
            dataPoints: Cast::int($data['data_points'] ?? null) ?? 0,
            from: Cast::dateTime($data['from'] ?? null),
            to: Cast::dateTime($data['to'] ?? null),
            timeSeries: Cast::modelList(ResponseTimeDataPoint::class, $data['time_series'] ?? null),
        );
    }
}
