<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: MonitorResponseTimeStatsDto.time_series[] */
final readonly class ResponseTimeDataPoint implements ResponseModel
{
    public function __construct(
        /** The time of the data point. */
        public ?DateTimeImmutable $timestamp = null,
        /** Response time value in milliseconds */
        public int $value = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            timestamp: Cast::dateTime($data['timestamp'] ?? null),
            value: Cast::int($data['value'] ?? null) ?? 0,
        );
    }
}
