<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * Summary statistics for the response time data
 *
 * Schema: MonitorResponseTimeStatsDto.summary
 */
final readonly class ResponseTimeSummary implements ResponseModel
{
    public function __construct(
        /** Minimum response time in milliseconds */
        public ?int $min = null,
        /** Maximum response time in milliseconds */
        public ?int $max = null,
        /** Average response time in milliseconds */
        public ?int $avg = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            min: Cast::int($data['min'] ?? null),
            max: Cast::int($data['max'] ?? null),
            avg: Cast::int($data['avg'] ?? null),
        );
    }
}
