<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\AlertDeliveryStatus;

/** Schema: PublicSentAlertsResponseDto.data[] */
final readonly class SentAlert implements ResponseModel
{
    public function __construct(
        /** When the alert was sent. */
        public ?DateTimeImmutable $timestamp = null,
        public string $recipientName = '',
        /**
         * The address the alert went to: an e-mail address, a phone number or, for the mobile app, the device token (verified live: a device token).
         */
        public string $recipientValue = '',
        /**
         * The channel of the alert contact, e.g. MobileApp (verified live); the specification documents no values.
         */
        public string $channelType = '',
        public ?AlertDeliveryStatus $status = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            timestamp: Cast::dateTime($data['timestamp'] ?? null),
            recipientName: Cast::string($data['recipientName'] ?? null) ?? '',
            recipientValue: Cast::string($data['recipientValue'] ?? null) ?? '',
            channelType: Cast::string($data['channelType'] ?? null) ?? '',
            status: Cast::stringEnum(AlertDeliveryStatus::class, $data['status'] ?? null),
        );
    }
}
