<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: CreateSlackIntegrationDto ("data": SlackBaseIntegrationDto) */
final readonly class SlackIntegrationCreate implements IntegrationCreate
{
    /** The "type" of this variant of {@see IntegrationCreate}. */
    public const string TYPE = 'Slack';

    public function __construct(
        /** The Slack incoming webhook URL. */
        public string $webhookUrl,
        /**
         * The channel, e.g. #alerts, as the official Terraform provider documents it; the specification describes it not at all, but requires it on create. The provider leaves it out when it is not configured (not verified live); an empty string names no channel.
         */
        public string $customValue,
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['webhookURL'] = $this->webhookUrl;
        $data['customValue'] = $this->customValue;

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
