<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: UpdateSplunkIntegrationSchema ("data": UpdateSplunkIntegrationDataDto) */
final readonly class SplunkIntegrationUpdate implements IntegrationUpdate
{
    /** The "type" of this variant of {@see IntegrationUpdate}. */
    public const string TYPE = 'Splunk';

    public function __construct(
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** The Splunk URL the alerts are posted to. */
        public string|Undefined $urlToNotify = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->urlToNotify instanceof Undefined) {
            $data['urlToNotify'] = $this->urlToNotify;
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
