<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto.customSettings.colors */
final readonly class StatusPageCustomSettingsColors implements ResponseModel
{
    public function __construct(
        public ?string $main = null,
        public ?string $text = null,
        public ?string $link = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            main: Cast::string($data['main'] ?? null),
            text: Cast::string($data['text'] ?? null),
            link: Cast::string($data['link'] ?? null),
        );
    }
}
