<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto.customSettings.page */
final readonly class StatusPageCustomSettingsPage implements ResponseModel
{
    public function __construct(
        public string $layout = '',
        public string $theme = '',
        public string $density = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            layout: Cast::string($data['layout'] ?? null) ?? '',
            theme: Cast::string($data['theme'] ?? null) ?? '',
            density: Cast::string($data['density'] ?? null) ?? '',
        );
    }
}
