<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: FontCustomSettingsDto */
final readonly class StatusPageCustomSettingsFontInput implements RequestModel
{
    public function __construct(
        /** The font family to use for the PSP. Google fonts are supported. */
        public string|Undefined $family = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->family instanceof Undefined) {
            $data['family'] = $this->family;
        }

        return $data;
    }
}
