<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\Region;

/** Schema: ActivityLogResponseDto.data[]<STATUS_UPDATE> */
final readonly class StatusUpdateActivity implements ActivityLogEntry
{
    /** The "type" of this variant of {@see ActivityLogEntry}. */
    public const string TYPE = 'STATUS_UPDATE';

    public function __construct(
        public ?DateTimeImmutable $date = null,
        public ?Region $region = null,
        /** The status of the incident; null if absent, as on every entry read live. */
        public ?string $incidentStatus = null,
        /** What the check found; the specification documents no values (verified live: Down, Slow and Up). */
        public string $alertLogType = '',
        /**
         * The cause code, as of the incident; 0 on the Up entry that ends it ("Monitor is UP", verified live).
         */
        public int $cause = 0,
        public string $reason = '',
        public ?RemoteNode $remoteNode = null,
        /** The response time in milliseconds; only on Slow entries (verified live: 3503). */
        public ?int $responseTime = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            date: Cast::dateTime($data['date'] ?? null),
            region: Cast::stringEnum(Region::class, $data['region'] ?? null),
            incidentStatus: Cast::string($data['incidentStatus'] ?? null),
            alertLogType: Cast::string($data['alertLogType'] ?? null) ?? '',
            cause: Cast::int($data['cause'] ?? null) ?? 0,
            reason: Cast::string($data['reason'] ?? null) ?? '',
            remoteNode: Cast::model(RemoteNode::class, $data['remoteNode'] ?? null),
            responseTime: Cast::int($data['responseTime'] ?? null),
        );
    }
}
