<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto */
final readonly class StatusPage implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $friendlyName = '',
        public ?string $customDomain = null,
        /** Whether visitors need a password; the API never returns the password itself. */
        public bool $isPasswordSet = false,
        /**
         * The monitors on the page; [0] means every monitor of the account, the setting autoAddMonitors of the requests, according to the official Terraform provider (not verified live). Empty if null.
         *
         * @var list<int>
         */
        public array $monitorIds = [],
        /** @var list<int> */
        public array $tagIds = [],
        public ?int $monitorsCount = null,
        /**
         * ENABLED if the page is published, PAUSED if not, as the requests name the values; the specification documents none for the response (not verified live).
         */
        public string $status = '',
        public string $urlKey = '',
        public ?string $homepageLink = null,
        public ?string $gaCode = null,
        public bool $shareAnalyticsConsent = false,
        public bool $useSmallCookieConsentModal = false,
        /** The uploaded icon as the API reports it, presumably its URL; null without one (not verified live). */
        public ?string $icon = null,
        public bool $noIndex = false,
        /** The uploaded logo as the API reports it, presumably its URL; null without one (not verified live). */
        public ?string $logo = null,
        public bool $hideUrlLinks = false,
        public bool $subscription = false,
        public bool $showCookieBar = false,
        /** The announcement pinned to the page; null if none. */
        public ?int $pinnedAnnouncementId = null,
        public ?StatusPageCustomSettings $customSettings = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            friendlyName: Cast::string($data['friendlyName'] ?? null) ?? '',
            customDomain: Cast::string($data['customDomain'] ?? null),
            isPasswordSet: Cast::bool($data['isPasswordSet'] ?? null) ?? false,
            monitorIds: Cast::listOf($data['monitorIds'] ?? null, Cast::int(...)),
            tagIds: Cast::listOf($data['tagIds'] ?? null, Cast::int(...)),
            monitorsCount: Cast::int($data['monitorsCount'] ?? null),
            status: Cast::string($data['status'] ?? null) ?? '',
            urlKey: Cast::string($data['urlKey'] ?? null) ?? '',
            homepageLink: Cast::string($data['homepageLink'] ?? null),
            gaCode: Cast::string($data['gaCode'] ?? null),
            shareAnalyticsConsent: Cast::bool($data['shareAnalyticsConsent'] ?? null) ?? false,
            useSmallCookieConsentModal: Cast::bool($data['useSmallCookieConsentModal'] ?? null) ?? false,
            icon: Cast::string($data['icon'] ?? null),
            noIndex: Cast::bool($data['noIndex'] ?? null) ?? false,
            logo: Cast::string($data['logo'] ?? null),
            hideUrlLinks: Cast::bool($data['hideUrlLinks'] ?? null) ?? false,
            subscription: Cast::bool($data['subscription'] ?? null) ?? false,
            showCookieBar: Cast::bool($data['showCookieBar'] ?? null) ?? false,
            pinnedAnnouncementId: Cast::int($data['pinnedAnnouncementId'] ?? null),
            customSettings: Cast::model(StatusPageCustomSettings::class, $data['customSettings'] ?? null),
        );
    }
}
