<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\StatusPageDensity;
use GoSuccess\UptimeRobot\Enum\StatusPageLayout;
use GoSuccess\UptimeRobot\Enum\StatusPageTheme;

/** Schema: PageCustomSettingsDto */
final readonly class StatusPageCustomSettingsPageInput implements RequestModel
{
    public function __construct(
        /** The alignment of the logo on the page */
        public StatusPageLayout|Undefined $layout = Undefined::Value,
        /** The theme of the page */
        public StatusPageTheme|Undefined $theme = Undefined::Value,
        /** The density of the page */
        public StatusPageDensity|Undefined $density = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->layout instanceof Undefined) {
            $data['layout'] = $this->layout->value;
        }

        if (!$this->theme instanceof Undefined) {
            $data['theme'] = $this->theme->value;
        }

        if (!$this->density instanceof Undefined) {
            $data['density'] = $this->density->value;
        }

        return $data;
    }
}
