<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: ColorsCustomSettingsDto */
final readonly class StatusPageCustomSettingsColorsInput implements RequestModel
{
    public function __construct(
        /** The main color of the page in hex format */
        public string|Undefined $main = Undefined::Value,
        /** The text color of the page in hex format */
        public string|Undefined $text = Undefined::Value,
        /** The link color of the page in hex format */
        public string|Undefined $link = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->main instanceof Undefined) {
            $data['main'] = $this->main;
        }

        if (!$this->text instanceof Undefined) {
            $data['text'] = $this->text;
        }

        if (!$this->link instanceof Undefined) {
            $data['link'] = $this->link;
        }

        return $data;
    }
}
