<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: CustomSettingsDto */
final readonly class StatusPageCustomSettingsInput implements RequestModel
{
    public function __construct(
        public StatusPageCustomSettingsFontInput|Undefined|null $font = Undefined::Value,
        public StatusPageCustomSettingsPageInput|Undefined|null $page = Undefined::Value,
        /** The colors of the page */
        public StatusPageCustomSettingsColorsInput|Undefined|null $colors = Undefined::Value,
        public StatusPageCustomSettingsFeaturesInput|Undefined|null $features = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->font instanceof Undefined) {
            $data['font'] = $this->font === null ? null : Json::map($this->font->toArray());
        }

        if (!$this->page instanceof Undefined) {
            $data['page'] = $this->page === null ? null : Json::map($this->page->toArray());
        }

        if (!$this->colors instanceof Undefined) {
            $data['colors'] = $this->colors === null ? null : Json::map($this->colors->toArray());
        }

        if (!$this->features instanceof Undefined) {
            $data['features'] = $this->features === null ? null : Json::map($this->features->toArray());
        }

        return $data;
    }
}
