<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\StatusPageSort;
use GoSuccess\UptimeRobot\Enum\StatusPageStatus;

/** Schema: CreatePsPDto */
final readonly class StatusPageCreate implements RequestModel
{
    public function __construct(
        /** Friendly name of the Public Status Page */
        public string $friendlyName,
        /**
         * The monitors on the page; [0] alone stands for every monitor of the account, including those added later, and an empty list removes every monitor. Wins over autoAddMonitors when both are sent.
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $monitorIds = Undefined::Value,
        /**
         * The tags assigned to the page.
         *
         * @var list<int>|Undefined
         */
        public array|Undefined $tagIds = Undefined::Value,
        /**
         * Whether every monitor of the account, also those added later, is shown on the page. An explicit monitorIds wins over it, even an empty one. Responses do not report it; they list monitorIds [0] instead, according to the official Terraform provider (not verified live).
         */
        public bool|Undefined $autoAddMonitors = Undefined::Value,
        /** A password visitors must enter, at most 255 characters. Responses only report isPasswordSet. */
        public string|Undefined $password = Undefined::Value,
        /** Provide when you want to use custom domain for the Public Status Page */
        public string|Undefined $customDomain = Undefined::Value,
        /** This will hide "Powered by UptimeRobot" link in footer */
        public bool|Undefined $hideUrlLinks = Undefined::Value,
        /** Set HTML meta tag to allow or disallow search engines to index your status page */
        public bool|Undefined $noIndex = Undefined::Value,
        /**
         * The Google Analytics measurement ID, "G-" and 10 upper-case letters or digits; for a page with a custom domain only.
         */
        public string|Undefined $gaCode = Undefined::Value,
        /**
         * How the monitors are ordered on the page. A manual order can only be arranged in the dashboard. Responses do not report the order.
         */
        public StatusPageSort|Undefined $sort = Undefined::Value,
        /** ENABLED publishes the page, PAUSED takes it offline. */
        public StatusPageStatus|Undefined $status = Undefined::Value,
        /** Subscribers can subscribe to receive announcements via an e-mail. */
        public bool|Undefined $subscription = Undefined::Value,
        /** Help us improve the Status Pages by sharing the analytics data with us. */
        public bool|Undefined $shareAnalyticsConsent = Undefined::Value,
        /** The link target for the logo (or main title) on status page. Usually leads to your homepage. */
        public string|Undefined $homepageLink = Undefined::Value,
        /** Available only for a Custom domain status page */
        public bool|Undefined $showCookieBar = Undefined::Value,
        /** Allowing visitor to interact with the page - should not be used on public pages */
        public bool|Undefined $useSmallCookieConsentModal = Undefined::Value,
        /** The design of the page. */
        public StatusPageCustomSettingsInput|Undefined $customSettings = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['friendlyName'] = $this->friendlyName;

        if (!$this->monitorIds instanceof Undefined) {
            $data['monitorIds'] = $this->monitorIds;
        }

        if (!$this->tagIds instanceof Undefined) {
            $data['tagIds'] = $this->tagIds;
        }

        if (!$this->autoAddMonitors instanceof Undefined) {
            $data['autoAddMonitors'] = $this->autoAddMonitors;
        }

        if (!$this->password instanceof Undefined) {
            $data['password'] = $this->password;
        }

        if (!$this->customDomain instanceof Undefined) {
            $data['customDomain'] = $this->customDomain;
        }

        if (!$this->hideUrlLinks instanceof Undefined) {
            $data['hideUrlLinks'] = $this->hideUrlLinks;
        }

        if (!$this->noIndex instanceof Undefined) {
            $data['noIndex'] = $this->noIndex;
        }

        if (!$this->gaCode instanceof Undefined) {
            $data['gaCode'] = $this->gaCode;
        }

        if (!$this->sort instanceof Undefined) {
            $data['sort'] = $this->sort->value;
        }

        if (!$this->status instanceof Undefined) {
            $data['status'] = $this->status->value;
        }

        if (!$this->subscription instanceof Undefined) {
            $data['subscription'] = $this->subscription;
        }

        if (!$this->shareAnalyticsConsent instanceof Undefined) {
            $data['shareAnalyticsConsent'] = $this->shareAnalyticsConsent;
        }

        if (!$this->homepageLink instanceof Undefined) {
            $data['homepageLink'] = $this->homepageLink;
        }

        if (!$this->showCookieBar instanceof Undefined) {
            $data['showCookieBar'] = $this->showCookieBar;
        }

        if (!$this->useSmallCookieConsentModal instanceof Undefined) {
            $data['useSmallCookieConsentModal'] = $this->useSmallCookieConsentModal;
        }

        if (!$this->customSettings instanceof Undefined) {
            $data['customSettings'] = Json::map($this->customSettings->toArray());
        }

        return $data;
    }
}
