<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto.customSettings.font */
final readonly class StatusPageCustomSettingsFont implements ResponseModel
{
    public function __construct(
        public ?string $family = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            family: Cast::string($data['family'] ?? null),
        );
    }
}
