<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\StatusPageDensity;
use GoSuccess\UptimeRobot\Enum\StatusPageLayout;
use GoSuccess\UptimeRobot\Enum\StatusPageTheme;

/** Schema: PspDto.customSettings.page */
final readonly class StatusPageCustomSettingsPage implements ResponseModel
{
    public function __construct(
        /**
         * Where the logo sits. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
         */
        public ?StatusPageLayout $layout = null,
        /**
         * The color theme. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
         */
        public ?StatusPageTheme $theme = null,
        /**
         * The density of the page. The requests take the same lower-case values, not the title-case ones of the specification (verified live).
         */
        public ?StatusPageDensity $density = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            layout: Cast::stringEnum(StatusPageLayout::class, $data['layout'] ?? null),
            theme: Cast::stringEnum(StatusPageTheme::class, $data['theme'] ?? null),
            density: Cast::stringEnum(StatusPageDensity::class, $data['density'] ?? null),
        );
    }
}
