<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto.customSettings.features */
final readonly class StatusPageCustomSettingsFeatures implements ResponseModel
{
    public function __construct(
        public ?bool $showBars = null,
        public ?bool $showUptimePercentage = null,
        public ?bool $enableFloatingStatus = null,
        public ?bool $showOverallUptime = null,
        public ?bool $showOutageUpdates = null,
        public ?bool $showOutageDetails = null,
        public ?bool $enableDetailsPage = null,
        public ?bool $showMonitorUrl = null,
        public ?bool $hidePausedMonitors = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            showBars: Cast::bool($data['showBars'] ?? null),
            showUptimePercentage: Cast::bool($data['showUptimePercentage'] ?? null),
            enableFloatingStatus: Cast::bool($data['enableFloatingStatus'] ?? null),
            showOverallUptime: Cast::bool($data['showOverallUptime'] ?? null),
            showOutageUpdates: Cast::bool($data['showOutageUpdates'] ?? null),
            showOutageDetails: Cast::bool($data['showOutageDetails'] ?? null),
            enableDetailsPage: Cast::bool($data['enableDetailsPage'] ?? null),
            showMonitorUrl: Cast::bool($data['showMonitorURL'] ?? null),
            hidePausedMonitors: Cast::bool($data['hidePausedMonitors'] ?? null),
        );
    }
}
