<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: PspDto.customSettings */
final readonly class StatusPageCustomSettings implements ResponseModel
{
    public function __construct(
        public ?StatusPageCustomSettingsFont $font = null,
        public StatusPageCustomSettingsPage $page = new StatusPageCustomSettingsPage(),
        public StatusPageCustomSettingsColors $colors = new StatusPageCustomSettingsColors(),
        public StatusPageCustomSettingsFeatures $features = new StatusPageCustomSettingsFeatures(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            font: Cast::model(StatusPageCustomSettingsFont::class, $data['font'] ?? null),
            page: Cast::model(StatusPageCustomSettingsPage::class, $data['page'] ?? null) ?? new StatusPageCustomSettingsPage(),
            colors: Cast::model(StatusPageCustomSettingsColors::class, $data['colors'] ?? null) ?? new StatusPageCustomSettingsColors(),
            features: Cast::model(StatusPageCustomSettingsFeatures::class, $data['features'] ?? null) ?? new StatusPageCustomSettingsFeatures(),
        );
    }
}
