<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: FeaturesCustomSettingsDto */
final readonly class StatusPageCustomSettingsFeaturesInput implements RequestModel
{
    public function __construct(
        /** Show or hide the bar charts for uptime of a monitor on a status page home screen */
        public bool|Undefined $showBars = Undefined::Value,
        /** Show or hide the uptime percentage of a monitor near the monitor name on a status page home screen */
        public bool|Undefined $showUptimePercentage = Undefined::Value,
        /**
         * Enable or disable the floating bar sticked to the bottom with the overall count of up and down monitors
         */
        public bool|Undefined $enableFloatingStatus = Undefined::Value,
        /**
         * Show or hide the overall uptime (last 24 h, last 7 and 30 days) section below monitors list on a status page home screen
         */
        public bool|Undefined $showOverallUptime = Undefined::Value,
        /** Show outage reason details (like status code) to give more explanation for your status page users */
        public bool|Undefined $showOutageUpdates = Undefined::Value,
        /**
         * Show or hide downtimes grouped by day for a specific monitor in the Announcement feed. The latest downtime will be visible in header. This won't hide the events on a details page
         */
        public bool|Undefined $showOutageDetails = Undefined::Value,
        /** Details page contains uptime, response times and up/down event history */
        public bool|Undefined $enableDetailsPage = Undefined::Value,
        /** Show monitor URL and type to give your users more details on your Status page */
        public bool|Undefined $showMonitorUrl = Undefined::Value,
        /** Don't display paused monitors on your Status page */
        public bool|Undefined $hidePausedMonitors = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->showBars instanceof Undefined) {
            $data['showBars'] = $this->showBars;
        }

        if (!$this->showUptimePercentage instanceof Undefined) {
            $data['showUptimePercentage'] = $this->showUptimePercentage;
        }

        if (!$this->enableFloatingStatus instanceof Undefined) {
            $data['enableFloatingStatus'] = $this->enableFloatingStatus;
        }

        if (!$this->showOverallUptime instanceof Undefined) {
            $data['showOverallUptime'] = $this->showOverallUptime;
        }

        if (!$this->showOutageUpdates instanceof Undefined) {
            $data['showOutageUpdates'] = $this->showOutageUpdates;
        }

        if (!$this->showOutageDetails instanceof Undefined) {
            $data['showOutageDetails'] = $this->showOutageDetails;
        }

        if (!$this->enableDetailsPage instanceof Undefined) {
            $data['enableDetailsPage'] = $this->enableDetailsPage;
        }

        if (!$this->showMonitorUrl instanceof Undefined) {
            $data['showMonitorURL'] = $this->showMonitorUrl;
        }

        if (!$this->hidePausedMonitors instanceof Undefined) {
            $data['hidePausedMonitors'] = $this->hidePausedMonitors;
        }

        return $data;
    }
}
