<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: StormProtectionSettingsResponseDto.config */
final readonly class StormProtectionConfig implements ResponseModel
{
    public function __construct(
        public bool $groupPooling = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            groupPooling: Cast::bool($data['groupPooling'] ?? null) ?? false,
        );
    }
}
