<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UpdateStormProtectionConfigDto */
final readonly class StormProtectionConfigUpdate implements RequestModel
{
    public function __construct(
        /** When enabled, suppressed alerts are pooled into a single grouped notification. */
        public bool|Undefined $groupPooling = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->groupPooling instanceof Undefined) {
            $data['groupPooling'] = $this->groupPooling;
        }

        return $data;
    }
}
