<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\StormProtectionThresholdType;

/** Schema: UpdateStormProtectionDto */
final readonly class StormProtectionUpdate implements RequestModel
{
    public function __construct(
        /** Enable or disable storm protection (alert grouping). */
        public bool|Undefined $isEnabled = Undefined::Value,
        /** How the threshold is measured. */
        public StormProtectionThresholdType|Undefined $thresholdType = Undefined::Value,
        /**
         * Threshold that triggers grouping. Accepts 1-1000000; the stricter rule (>= 2 for "count", <= 100 for "percentage") is enforced server-side by domain validation.
         */
        public int|Undefined $thresholdValue = Undefined::Value,
        /** Rolling time window in minutes (1-15). */
        public int|Undefined $windowMinutes = Undefined::Value,
        public StormProtectionConfigUpdate|Undefined $config = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->isEnabled instanceof Undefined) {
            $data['isEnabled'] = $this->isEnabled;
        }

        if (!$this->thresholdType instanceof Undefined) {
            $data['thresholdType'] = $this->thresholdType->value;
        }

        if (!$this->thresholdValue instanceof Undefined) {
            $data['thresholdValue'] = $this->thresholdValue;
        }

        if (!$this->windowMinutes instanceof Undefined) {
            $data['windowMinutes'] = $this->windowMinutes;
        }

        if (!$this->config instanceof Undefined) {
            $data['config'] = Json::map($this->config->toArray());
        }

        return $data;
    }
}
