<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\StormProtectionThresholdType;

/** Schema: StormProtectionSettingsResponseDto */
final readonly class StormProtectionSettings implements ResponseModel
{
    public function __construct(
        public bool $isEnabled = false,
        public ?StormProtectionThresholdType $thresholdType = null,
        public int $thresholdValue = 0,
        public int $windowMinutes = 0,
        public StormProtectionConfig $config = new StormProtectionConfig(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            isEnabled: Cast::bool($data['isEnabled'] ?? null) ?? false,
            thresholdType: Cast::stringEnum(StormProtectionThresholdType::class, $data['thresholdType'] ?? null),
            thresholdValue: Cast::int($data['thresholdValue'] ?? null) ?? 0,
            windowMinutes: Cast::int($data['windowMinutes'] ?? null) ?? 0,
            config: Cast::model(StormProtectionConfig::class, $data['config'] ?? null) ?? new StormProtectionConfig(),
        );
    }
}
