<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;

/** Schema: UserDto.activeSubscription */
final readonly class Subscription implements ResponseModel
{
    public function __construct(
        /**
         * Display label for the active plan (e.g. "Free", "Solo", "Team", "Scale"). This is a human-readable label, NOT a stable identifier — it can change (e.g. "Enterprise" → "Scale"). Consumers needing stability should branch on a stable field, not on this string.
         */
        public string $plan = '',
        public int $monitorLimit = 0,
        public ?DateTimeImmutable $expirationDate = null,
        public string $status = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            plan: Cast::string($data['plan'] ?? null) ?? '',
            monitorLimit: Cast::int($data['monitorLimit'] ?? null) ?? 0,
            expirationDate: Cast::dateTime($data['expirationDate'] ?? null),
            status: Cast::string($data['status'] ?? null) ?? '',
        );
    }
}
