<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: SimpleTagPaginationDto.data[] */
final readonly class Tag implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public string $name = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null) ?? '',
        );
    }
}
