<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\MonitorStatus;

/** Schema: MonitorDto.tags[].monitors[] */
final readonly class TaggedMonitor implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $friendlyName = null,
        public ?MonitorStatus $status = null,
        public string $url = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            friendlyName: Cast::string($data['friendlyName'] ?? null),
            status: Cast::stringEnum(MonitorStatus::class, $data['status'] ?? null),
            url: Cast::string($data['url'] ?? null) ?? '',
        );
    }
}
