<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UdpConfigFieldsDto */
final readonly class UdpSettings implements RequestModel, ResponseModel
{
    /** UDP payload to send */
    public string $payload;

    /** Packet loss threshold percentage */
    public float $packetLossThreshold;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined $payload = Undefined::Value,
        float|Undefined $packetLossThreshold = Undefined::Value,
    ) {
        $this->payload = $payload instanceof Undefined ? '' : $payload;
        $this->packetLossThreshold = $packetLossThreshold instanceof Undefined ? 0.0 : $packetLossThreshold;
        $this->provided = array_filter([
            'payload' => !$payload instanceof Undefined,
            'packetLossThreshold' => !$packetLossThreshold instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            payload: Cast::string($data['payload'] ?? null) ?? Undefined::Value,
            packetLossThreshold: Cast::float($data['packetLossThreshold'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['payload'])) {
            $data['payload'] = $this->payload;
        }

        if (isset($this->provided['packetLossThreshold'])) {
            $data['packetLossThreshold'] = $this->packetLossThreshold;
        }

        return $data;
    }
}
