<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/**
 * A {@see ActivityLogEntry} of a kind this client does not know yet.
 *
 * It keeps the payload as the API sent it, so nothing is lost until the client learns the new kind.
 *
 * Schema: ActivityLogResponseDto.data[]
 */
final readonly class UnknownActivityLogEntry implements ActivityLogEntry
{
    /**
     * @param string|null $type The "type" the API sent, if any.
     * @param array<array-key, mixed> $data The payload as the API sent it.
     */
    public function __construct(
        public ?string $type = null,
        public array $data = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(Cast::string($data['type'] ?? null), $data);
    }
}
