<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\Region;

/**
 * A {@see ActivityLogEntry} of a kind this client does not know yet.
 *
 * It keeps the payload as the API sent it, so nothing is lost until the client learns the new kind,
 * and reads the properties that every kind has.
 *
 * Schema: ActivityLogResponseDto.data[]
 */
final readonly class UnknownActivityLogEntry implements ActivityLogEntry
{
    /**
     * @param string|null $type The "type" the API sent, if any.
     * @param array<array-key, mixed> $data The payload as the API sent it.
     */
    public function __construct(
        public ?string $type = null,
        public array $data = [],
        public ?DateTimeImmutable $date = null,
        public ?Region $region = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            type: Cast::string($data['type'] ?? null),
            data: $data,
            date: Cast::dateTime($data['date'] ?? null),
            region: Cast::stringEnum(Region::class, $data['region'] ?? null),
        );
    }
}
