<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UptimeStatsDto */
final readonly class UptimeStats implements ResponseModel
{
    public function __construct(
        /**
         * The uptime of all monitors as a fraction from 0 to 1, e.g. 0.9969, unlike the percentage of MonitorResource::uptime() (verified live).
         */
        public float $overallUptime = 0.0,
        public int $totalIncidents = 0,
        /** Seconds without incidents; beyond 2^31 for the time frame ALL (verified live). */
        public int $totalTimeWithoutIncidents = 0,
        public int $affectedMonitors = 0,
        /** @var list<UptimeLogEntry> */
        public array $logs = [],
        /** The mean time between failures in seconds; null without incidents (verified live). */
        public ?int $mtbf = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            overallUptime: Cast::float($data['overallUptime'] ?? null) ?? 0.0,
            totalIncidents: Cast::int($data['totalIncidents'] ?? null) ?? 0,
            totalTimeWithoutIncidents: Cast::int($data['totalTimeWithoutIncidents'] ?? null) ?? 0,
            affectedMonitors: Cast::int($data['affectedMonitors'] ?? null) ?? 0,
            logs: Cast::modelList(UptimeLogEntry::class, $data['logs'] ?? null),
            mtbf: Cast::int($data['mtbf'] ?? null),
        );
    }
}
