<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use DateTimeImmutable;
use GoSuccess\UptimeRobot\Enum\UptimeLogType;

/** Schema: UptimeStatsDto.logs[] */
final readonly class UptimeLogEntry implements ResponseModel
{
    public function __construct(
        public ?UptimeLogType $type = null,
        public ?DateTimeImmutable $datetime = null,
        /** Seconds. */
        public ?int $duration = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            type: Cast::stringEnum(UptimeLogType::class, $data['type'] ?? null),
            datetime: Cast::dateTime($data['datetime'] ?? null),
            duration: Cast::int($data['duration'] ?? null),
        );
    }
}
