<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: MonitorDto.lastDayUptimes.histogram[] */
final readonly class UptimeHistogramBucket implements ResponseModel
{
    public function __construct(
        public int $timestamp = 0,
        public float $uptime = 0.0,
        public int $changes = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            timestamp: Cast::int($data['timestamp'] ?? null) ?? 0,
            uptime: Cast::float($data['uptime'] ?? null) ?? 0.0,
            changes: Cast::int($data['changes'] ?? null) ?? 0,
        );
    }
}
