<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: MonitorDto.lastDayUptimes */
final readonly class UptimeHistogram implements ResponseModel
{
    public function __construct(
        public int $bucketSize = 0,
        public ?int $totalChanges = null,
        /** @var list<UptimeHistogramBucket> */
        public array $histogram = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            bucketSize: Cast::int($data['bucketSize'] ?? null) ?? 0,
            totalChanges: Cast::int($data['totalChanges'] ?? null),
            histogram: Cast::modelList(UptimeHistogramBucket::class, $data['histogram'] ?? null),
        );
    }
}
