<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: UserDto */
final readonly class User implements ResponseModel
{
    public function __construct(
        public string $email = '',
        public string $fullName = '',
        public int $monitorsCount = 0,
        public int $monitorLimit = 0,
        public int $smsCredits = 0,
        public Subscription $activeSubscription = new Subscription(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            email: Cast::string($data['email'] ?? null) ?? '',
            fullName: Cast::string($data['fullName'] ?? null) ?? '',
            monitorsCount: Cast::int($data['monitorsCount'] ?? null) ?? 0,
            monitorLimit: Cast::int($data['monitorLimit'] ?? null) ?? 0,
            smsCredits: Cast::int($data['smsCredits'] ?? null) ?? 0,
            activeSubscription: Cast::model(Subscription::class, $data['activeSubscription'] ?? null) ?? new Subscription(),
        );
    }
}
