<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\VisualComparisonViewport;

/** Schema: VisualComparisonFieldsDto */
final readonly class VisualComparisonSettings implements RequestModel
{
    public function __construct(
        /** Difference sensitivity threshold (0-100) */
        public int $sensitivityThreshold,
        /** Viewport profile for the capture */
        public VisualComparisonViewport $viewport,
        /** Optional rectangular region (percentage-based) to compare. Omit for full-page comparison. */
        public VisualComparisonArea|Undefined $areaCoordinates = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['sensitivityThreshold'] = $this->sensitivityThreshold;
        $data['viewport'] = $this->viewport->value;

        if (!$this->areaCoordinates instanceof Undefined) {
            $data['areaCoordinates'] = Json::map($this->areaCoordinates->toArray());
        }

        return $data;
    }
}
