<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: VisualComparisonAreaCoordinatesDto */
final readonly class VisualComparisonArea implements RequestModel, ResponseModel
{
    /** Left edge (percent) */
    public float $percentX;

    /** Top edge (percent) */
    public float $percentY;

    /** Width (percent) */
    public float $percentWidth;

    /** Height (percent) */
    public float $percentHeight;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        float|Undefined $percentX = Undefined::Value,
        float|Undefined $percentY = Undefined::Value,
        float|Undefined $percentWidth = Undefined::Value,
        float|Undefined $percentHeight = Undefined::Value,
    ) {
        $this->percentX = $percentX instanceof Undefined ? 0.0 : $percentX;
        $this->percentY = $percentY instanceof Undefined ? 0.0 : $percentY;
        $this->percentWidth = $percentWidth instanceof Undefined ? 0.0 : $percentWidth;
        $this->percentHeight = $percentHeight instanceof Undefined ? 0.0 : $percentHeight;
        $this->provided = array_filter([
            'percentX' => !$percentX instanceof Undefined,
            'percentY' => !$percentY instanceof Undefined,
            'percentWidth' => !$percentWidth instanceof Undefined,
            'percentHeight' => !$percentHeight instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            percentX: Cast::float($data['percentX'] ?? null) ?? Undefined::Value,
            percentY: Cast::float($data['percentY'] ?? null) ?? Undefined::Value,
            percentWidth: Cast::float($data['percentWidth'] ?? null) ?? Undefined::Value,
            percentHeight: Cast::float($data['percentHeight'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['percentX'])) {
            $data['percentX'] = $this->percentX;
        }

        if (isset($this->provided['percentY'])) {
            $data['percentY'] = $this->percentY;
        }

        if (isset($this->provided['percentWidth'])) {
            $data['percentWidth'] = $this->percentWidth;
        }

        if (isset($this->provided['percentHeight'])) {
            $data['percentHeight'] = $this->percentHeight;
        }

        return $data;
    }
}
