<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

/** Schema: VisualComparisonMonitorConfigDto */
final readonly class VisualComparisonMonitorConfig implements RequestModel
{
    public function __construct(
        /** Visual comparison monitor configuration */
        public VisualComparisonSettings $visualComparison,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['visualComparison'] = Json::map($this->visualComparison->toArray());

        return $data;
    }
}
