<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot\Model;

use GoSuccess\UptimeRobot\Enum\NotificationEvent;

/** Schema: UpdateWebhookIntegrationSchema ("data": UpdateWebhookIntegrationDataDto) */
final readonly class WebhookIntegrationUpdate implements IntegrationUpdate
{
    /** The "type" of this variant of {@see IntegrationUpdate}. */
    public const string TYPE = 'Webhook';

    public function __construct(
        /** The friendly name of the integration */
        public string|Undefined $friendlyName = Undefined::Value,
        /** Which status changes of its monitors the integration is alerted of. */
        public NotificationEvent|Undefined $enableNotificationsFor = Undefined::Value,
        /** Send a notification about SSL & Domain expiry */
        public bool|Undefined $sslExpirationReminder = Undefined::Value,
        /** The URL the webhook calls. */
        public string|Undefined $urlToNotify = Undefined::Value,
        /** Whether postValue is sent as a query string. */
        public bool|Undefined $sendAsQueryString = Undefined::Value,
        /**
         * The body the webhook sends, e.g. a JSON template such as {"message": "Alert: $monitorURL is $alertType"}, as the official Terraform provider's acceptance tests send it.
         */
        public string|Undefined $postValue = Undefined::Value,
        /** Whether postValue is sent as a JSON body. */
        public bool|Undefined $sendAsJson = Undefined::Value,
        /** Whether postValue is sent as form parameters. */
        public bool|Undefined $sendAsPostParameters = Undefined::Value,
        /**
         * Headers the webhook sends, by name; an empty array removes them, according to the official Terraform provider.
         *
         * @var array<array-key, string>|Undefined|null
         */
        public array|Undefined|null $customHeaders = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->friendlyName instanceof Undefined) {
            $data['friendlyName'] = $this->friendlyName;
        }

        if (!$this->enableNotificationsFor instanceof Undefined) {
            $data['enableNotificationsFor'] = $this->enableNotificationsFor->value;
        }

        if (!$this->sslExpirationReminder instanceof Undefined) {
            $data['sslExpirationReminder'] = $this->sslExpirationReminder;
        }

        if (!$this->urlToNotify instanceof Undefined) {
            $data['urlToNotify'] = $this->urlToNotify;
        }

        if (!$this->sendAsQueryString instanceof Undefined) {
            $data['sendAsQueryString'] = $this->sendAsQueryString;
        }

        if (!$this->postValue instanceof Undefined) {
            $data['postValue'] = $this->postValue;
        }

        if (!$this->sendAsJson instanceof Undefined) {
            $data['sendAsJSON'] = $this->sendAsJson;
        }

        if (!$this->sendAsPostParameters instanceof Undefined) {
            $data['sendAsPostParameters'] = $this->sendAsPostParameters;
        }

        if (!$this->customHeaders instanceof Undefined) {
            $data['customHeaders'] = $this->customHeaders === null ? null : Json::map($this->customHeaders);
        }

        return ['type' => self::TYPE, 'data' => Json::map($data)];
    }
}
