<?php

declare(strict_types=1);

namespace GoSuccess\UptimeRobot\Tests\Unit\Tools\Generator;

use GoSuccess\UptimeRobot\Tests\Support\Generator\GeneratorFixture;
use GoSuccess\UptimeRobot\Tools\Generator\Config\ApiConfig;
use GoSuccess\UptimeRobot\Tools\Generator\Generator;
use GoSuccess\UptimeRobot\Tools\Generator\Writer\CodeFile;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use RuntimeException;

/**
 * Generated code shares its directories with hand-written code (src/Model
 * holds Cast next to the models), so the generator only ever touches files
 * that start with its own header.
 */
#[CoversClass(Generator::class)]
#[CoversClass(CodeFile::class)]
final class GeneratorFilesTest extends TestCase
{
    private const string NAMESPACE = 'GoSuccess\\UptimeRobot\\Tests\\Fixture\\Files';

    private string $root;

    protected function setUp(): void
    {
        $this->root = GeneratorFixture::temporaryDirectory();
    }

    protected function tearDown(): void
    {
        GeneratorFixture::remove($this->root);
    }

    public function testWritesDeterministicallyAndOnlyWhatChanged(): void
    {
        $generator = $this->generator();

        self::assertStringContainsString('5 files written, 0 stale deleted', $generator->run());
        $first = $this->files();

        self::assertStringContainsString('0 files written, 0 stale deleted', $generator->run());
        self::assertSame($first, $this->files());
        self::assertSame([
            'src/FixtureClient.php',
            'src/Model/Thing.php',
            'src/Model/ThingOwner.php',
            'src/Model/ThingUpdate.php',
            'src/Resource/ThingResource.php',
        ], array_keys($first));

        foreach ($first as $path => $content) {
            self::assertTrue(CodeFile::isGenerated($content), $path);
            self::assertStringContainsString("// This file is generated by tools/generate.php from resources/specs/fixture.json. Do not edit.\n", $content);
        }
    }

    public function testDeletesStaleGeneratedFilesButNeverHandWrittenOnes(): void
    {
        $this->write('src/Model/Retired.php', "<?php\n\ndeclare(strict_types=1);\n\n// " . CodeFile::MARKER . " from resources/specs/fixture.json. Do not edit.\n\nnamespace X;\n");
        $this->write('src/Model/Cast.php', "<?php\n\ndeclare(strict_types=1);\n\nnamespace X;\n\nfinal class Cast {}\n");
        // Mentions the marker, but does not start with the header.
        $this->write('src/Model/Notes.php', "<?php\n\ndeclare(strict_types=1);\n\nnamespace X;\n\n/** Unlike " . CodeFile::MARKER . " files, this one is hand-written. */\nfinal class Notes {}\n");
        $this->write('src/Model/readme.txt', CodeFile::MARKER);

        self::assertStringContainsString('1 stale deleted', $this->generator()->run());

        self::assertFileDoesNotExist("{$this->root}/src/Model/Retired.php");
        self::assertFileExists("{$this->root}/src/Model/Cast.php");
        self::assertFileExists("{$this->root}/src/Model/Notes.php");
        self::assertFileExists("{$this->root}/src/Model/readme.txt");
    }

    public function testRefusesToOverwriteHandWrittenFiles(): void
    {
        $this->write('src/Model/Thing.php', "<?php\n\ndeclare(strict_types=1);\n\nnamespace X;\n\nfinal class Thing {}\n");

        try {
            $this->generator()->run();
            self::fail('Expected an exception.');
        } catch (RuntimeException $e) {
            self::assertStringContainsString("Refusing to overwrite the hand-written {$this->root}/src/Model/Thing.php", $e->getMessage());
        }

        // Nothing was written.
        self::assertFileDoesNotExist("{$this->root}/src/Model/ThingOwner.php");
    }

    public function testMixesInTheTraitOfHandWrittenMethods(): void
    {
        // The hand-written method builds its own body, so ThingUpdate is not generated.
        $config = ['schemas' => [], 'resources' => ['things' => [
            'class' => 'ThingResource',
            'description' => 'Things.',
            'handwritten' => true,
            'methods' => [
                'get' => ['operation' => 'ThingsController_get'],
                'update' => ['operation' => 'ThingsController_update', 'handwritten' => true],
            ],
        ]]];

        try {
            $this->generator($config)->run();
            self::fail('Expected an exception.');
        } catch (RuntimeException $e) {
            self::assertStringContainsString('ThingResource mixes in hand-written methods, but', $e->getMessage());
            self::assertStringContainsString('src/Resource/Handwritten/ThingOperations.php does not exist.', $e->getMessage());
        }

        $this->write('src/Resource/Handwritten/ThingOperations.php', "<?php\n\ndeclare(strict_types=1);\n\nnamespace X;\n\ntrait ThingOperations {}\n");
        $this->generator($config)->run();
        $resource = (string) file_get_contents("{$this->root}/src/Resource/ThingResource.php");

        self::assertStringContainsString('use ' . self::NAMESPACE . "\\Resource\\Handwritten\\ThingOperations;\n", $resource);
        self::assertStringContainsString("    use ThingOperations;\n", $resource);
        self::assertStringNotContainsString('function update(', $resource);
        self::assertFileDoesNotExist("{$this->root}/src/Model/ThingUpdate.php");
    }

    public function testRejectsHandWrittenMethodsOfResourcesWithoutTrait(): void
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('ThingResource::update is hand-written, but the resource does not mix in its trait.');

        $this->generator(['resources' => ['things' => ['class' => 'ThingResource', 'description' => 'Things.', 'methods' => [
            'get' => ['operation' => 'ThingsController_get'],
            'update' => ['operation' => 'ThingsController_update', 'handwritten' => true],
        ]]]])->analyze();
    }

    /**
     * @param array<string, mixed> $config
     */
    private function generator(array $config = []): Generator
    {
        $json = static fn(array $schema): array => ['description' => '', 'content' => ['application/json' => ['schema' => $schema]]];
        $spec = [
            'openapi' => '3.0.0',
            'paths' => ['/things' => [
                'get' => ['operationId' => 'ThingsController_get', 'responses' => ['200' => $json(['$ref' => '#/components/schemas/ThingDto'])]],
                'patch' => [
                    'operationId' => 'ThingsController_update',
                    'requestBody' => ['required' => true, ...$json(['$ref' => '#/components/schemas/UpdateThingDto'])],
                    'responses' => ['200' => $json(['$ref' => '#/components/schemas/ThingDto'])],
                ],
            ]],
            'components' => ['schemas' => [
                'ThingDto' => ['type' => 'object', 'properties' => ['name' => ['type' => 'string'], 'owner' => ['type' => 'object', 'properties' => ['name' => ['type' => 'string']]]]],
                'UpdateThingDto' => ['type' => 'object', 'properties' => ['name' => ['type' => 'string']]],
            ]],
        ];

        $this->write('resources/specs/fixture.json', json_encode($spec, \JSON_THROW_ON_ERROR));

        return new Generator(ApiConfig::fromArray('fixture', [
            'title' => 'Fixture API',
            'spec' => 'fixture',
            'namespace' => self::NAMESPACE,
            'client' => 'FixtureClient',
            'baseUri' => 'https://api.example.com',
            'naming' => ['stripSuffixes' => ['Dto']],
            'schemas' => ['UpdateThingDto' => 'ThingUpdate'],
            'resources' => ['things' => ['class' => 'ThingResource', 'description' => 'Things.', 'methods' => [
                'get' => ['operation' => 'ThingsController_get'],
                'update' => ['operation' => 'ThingsController_update'],
            ]]],
            ...$config,
        ]), $this->root);
    }

    private function write(string $path, string $content): void
    {
        $file = "{$this->root}/{$path}";

        if (!is_dir(\dirname($file))) {
            mkdir(\dirname($file), 0o775, true);
        }

        file_put_contents($file, $content);
    }

    /**
     * @return array<string, string> Relative path => content of the PHP files below src/.
     */
    private function files(): array
    {
        $files = [];

        foreach (glob("{$this->root}/src/{,*/,*/*/}*.php", \GLOB_BRACE) ?: [] as $file) {
            $files[substr($file, \strlen($this->root) + 1)] = (string) file_get_contents($file);
        }

        ksort($files);

        return $files;
    }
}
