<?php

declare(strict_types=1);

namespace GoSuccess\UptimeRobot\Tools\Generator\Writer;

/**
 * One PHP file being generated: tracks the imports it needs.
 */
final class CodeFile
{
    public const string MARKER = 'This file is generated by tools/generate.php';

    /** @var array<string, string> Fully qualified class => name used in code. */
    private array $imports = [];

    /** @var array<string, true> Lower-cased short names already taken. */
    private array $taken = [];

    public function __construct(
        public readonly string $namespace,
        public readonly string $className,
    ) {
        $this->taken[strtolower($className)] = true;
    }

    /**
     * Import a class and return the name to reference it by.
     */
    public function alias(string $class): string
    {
        $class = ltrim($class, '\\');
        $position = strrpos($class, '\\');
        $short = $position === false ? $class : substr($class, $position + 1);
        $namespace = $position === false ? '' : substr($class, 0, $position);

        if ($class === "{$this->namespace}\\{$this->className}") {
            return $short;
        }

        if (isset($this->imports[$class])) {
            return $this->imports[$class];
        }

        $alias = $short;

        if (isset($this->taken[strtolower($alias)]) || ($namespace !== $this->namespace && $this->sameNamespaceClashes($short))) {
            // e.g. an enum and a model of the same name: import the enum as "StatusEnum".
            $segment = $namespace === '' ? 'Php' : substr($namespace, (int) strrpos($namespace, '\\') + 1);
            $alias = $short . $segment;
        }

        $this->taken[strtolower($alias)] = true;
        $this->imports[$class] = $alias;

        return $alias;
    }

    /**
     * Whether a file's content is a generated file, recognized by the header
     * render() writes. A hand-written file that merely mentions the marker is
     * not one.
     */
    public static function isGenerated(string $content): bool
    {
        return str_starts_with($content, "<?php\n\ndeclare(strict_types=1);\n\n// " . self::MARKER . ' ');
    }

    public function render(string $body, string $source): string
    {
        $uses = [];

        foreach ($this->imports as $class => $alias) {
            $position = strrpos($class, '\\');
            $namespace = $position === false ? '' : substr($class, 0, $position);
            $short = $position === false ? $class : substr($class, $position + 1);

            if ($namespace === $this->namespace && $alias === $short) {
                continue;
            }

            $uses[] = $alias === $short ? "use {$class};" : "use {$class} as {$alias};";
        }

        sort($uses, \SORT_STRING | \SORT_FLAG_CASE);
        $useBlock = $uses === [] ? '' : implode("\n", $uses) . "\n\n";

        return "<?php\n\ndeclare(strict_types=1);\n\n// " . self::MARKER . " from {$source}. Do not edit.\n\n"
            . "namespace {$this->namespace};\n\n{$useBlock}{$body}";
    }

    /**
     * Classes in the file's own namespace are referenced without an import, so
     * an imported class of the same short name must be aliased. Only the
     * current class is known here; other same-namespace references are
     * registered through alias() and end up in $taken as well.
     */
    private function sameNamespaceClashes(string $short): bool
    {
        return strtolower($short) === strtolower($this->className);
    }
}
