<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/uptimerobot.json. Do not edit.

namespace GoSuccess\UptimeRobot;

use GoSuccess\UptimeRobot\Http\Connection;
use GoSuccess\UptimeRobot\Http\CurlHttpClient;
use GoSuccess\UptimeRobot\Http\HttpClient;
use GoSuccess\UptimeRobot\RateLimit\NullRateLimiter;
use GoSuccess\UptimeRobot\RateLimit\RateLimiter;
use GoSuccess\UptimeRobot\RateLimit\RateLimitStatus;
use GoSuccess\UptimeRobot\Resource\BulkMonitorResource;
use GoSuccess\UptimeRobot\Resource\MonitorResource;
use GoSuccess\UptimeRobot\Resource\StormProtectionResource;
use GoSuccess\UptimeRobot\Resource\TagResource;
use GoSuccess\UptimeRobot\Resource\UserResource;
use SensitiveParameter;

/**
 * Client for the UptimeRobot API v3 (`https://api.uptimerobot.com/v3`).
 *
 * Resources are created on first access, so unused ones cost nothing.
 */
final class UptimeRobot
{
    public const string DEFAULT_BASE_URI = 'https://api.uptimerobot.com/v3';

    /**
     * Monitors: create, read, change, pause, start and delete them, and read their uptime and response time statistics.
     */
    public private(set) MonitorResource $monitors {
        get => $this->monitors ??= new MonitorResource($this->connection);
    }

    /** Pause, start or change the monitors of a monitor group and/or with a tag at once. */
    public private(set) BulkMonitorResource $bulkMonitors {
        get => $this->bulkMonitors ??= new BulkMonitorResource($this->connection);
    }

    /** The account the API key belongs to: its plan and its alert contacts. */
    public private(set) UserResource $user {
        get => $this->user ??= new UserResource($this->connection);
    }

    /** Tags of monitors. They are created by naming them on a monitor. */
    public private(set) TagResource $tags {
        get => $this->tags ??= new TagResource($this->connection);
    }

    /** Storm protection: the account-wide grouping of alerts when many monitors go down at once. */
    public private(set) StormProtectionResource $stormProtection {
        get => $this->stormProtection ??= new StormProtectionResource($this->connection);
    }

    /**
     * The request quota the most recent response reported (its `x-ratelimit-*`
     * headers), or null before the first response that carried them.
     */
    public ?RateLimitStatus $rateLimit {
        get => $this->connection->rateLimit;
    }

    private readonly Connection $connection;

    /**
     * @param string          $apiKey      The main API key, or the read-only API key for read access, from the API settings of the UptimeRobot dashboard.
     * @param ClientOptions   $options     Timeouts, retries, rate-limit handling and user agent.
     * @param HttpClient|null $httpClient  Custom transport; defaults to the built-in cURL transport.
     * @param RateLimiter     $rateLimiter Client-side throttling; disabled by default.
     * @param string          $baseUri     Base URI of the API.
     */
    public function __construct(
        #[SensitiveParameter]
        string $apiKey,
        ClientOptions $options = new ClientOptions(),
        ?HttpClient $httpClient = null,
        RateLimiter $rateLimiter = new NullRateLimiter(),
        string $baseUri = self::DEFAULT_BASE_URI,
    ) {
        $this->connection = new Connection(
            $baseUri,
            $apiKey,
            $options,
            $httpClient ?? new CurlHttpClient($options->timeout, $options->connectTimeout),
            $rateLimiter,
        );
    }

    /**
     * Hide the API key from var_dump() and print_r().
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        return ['baseUri' => $this->connection->baseUri, 'apiKey' => '********', 'rateLimit' => $this->rateLimit];
    }
}
